import day001Image from '../assets/picture-describe/day-001-self-introduction.png';
import day002Image from '../assets/picture-describe/day-002-student-at-desk.png';
import day003Image from '../assets/picture-describe/day-003-question.png';
import day004Image from '../assets/picture-describe/day-004-my-friend.png';
import day005Image from '../assets/picture-describe/day-005-kind-person.png';
import day006Image from '../assets/picture-describe/day-006-study-english.png';
import day007Image from '../assets/picture-describe/day-007-week-1-scene.png';
import day008Image from '../assets/picture-describe/day-008-my-room.png';
import day009Image from '../assets/picture-describe/day-009-things-on-table.png';
import day010Image from '../assets/picture-describe/day-010-morning-at-home.png';
import day011Image from '../assets/picture-describe/day-011-kitchen-breakfast.png';
import day012Image from '../assets/picture-describe/day-012-cleaning-room.png';
import day013Image from '../assets/picture-describe/day-013-evening-at-home.png';
import day014Image from '../assets/picture-describe/day-014-home-check.png';
import day015Image from '../assets/picture-describe/day-015-morning-routine.png';
import day016Image from '../assets/picture-describe/day-016-going-to-school-work.png';
import day017Image from '../assets/picture-describe/day-017-useful-actions.png';
import day018Image from '../assets/picture-describe/day-018-time-of-day.png';
import day019Image from '../assets/picture-describe/day-019-action-order.png';
import day020Image from '../assets/picture-describe/day-020-everyday-habits.png';
import day021Image from '../assets/picture-describe/day-021-normal-day-check.png';
import day022Image from '../assets/picture-describe/day-022-food-and-drink.png';
import day023Image from '../assets/picture-describe/day-023-want-and-need.png';
import day024Image from '../assets/picture-describe/day-024-buying-simple-things.png';
import day025Image from '../assets/picture-describe/day-025-money-and-price.png';
import day026Image from '../assets/picture-describe/day-026-asking-for-help.png';
import day027Image from '../assets/picture-describe/day-027-more-enough-good.png';
import day028Image from '../assets/picture-describe/day-028-meal-shopping-check.png';
import day029Image from '../assets/picture-describe/day-029-getting-ready-to-go-out.png';
import day030Image from '../assets/picture-describe/day-030-walking-to-the-bus-place.png';
import day031Image from '../assets/picture-describe/day-031-taking-the-bus.png';
import day032Image from '../assets/picture-describe/day-032-finding-things-in-store.png';
import day033Image from '../assets/picture-describe/day-033-waiting-and-paying.png';
import day034Image from '../assets/picture-describe/day-034-coming-back-home.png';
import day035Image from '../assets/picture-describe/day-035-errand-story-recap.png';
import day036Image from '../assets/picture-describe/day-036-early-and-late-bus.png';
import day037Image from '../assets/picture-describe/day-037-no-clear-way.png';
import day038Image from '../assets/picture-describe/day-038-wrong-way.png';
import day039Image from '../assets/picture-describe/day-039-please-repeat.png';
import day040Image from '../assets/picture-describe/day-040-ask-again.png';
import day041Image from '../assets/picture-describe/day-041-polite-help.png';
import day042Image from '../assets/picture-describe/day-042-problem-story-recap.png';
import day043Image from '../assets/picture-describe/day-043-body-parts.png';
import day044Image from '../assets/picture-describe/day-044-feel-ill.png';
import day045Image from '../assets/picture-describe/day-045-body-pain.png';
import day046Image from '../assets/picture-describe/day-046-need-rest.png';
import day047Image from '../assets/picture-describe/day-047-warm-care.png';
import day048Image from '../assets/picture-describe/day-048-tell-body-problem.png';
import day049Image from '../assets/picture-describe/day-049-body-care-story.png';
import type { PictureDescribeTask } from '../domain/types';
import { week8to12PictureDescribeTasksByDayId } from './week8to12LearningTasks';

export const pictureDescribeTasksByDayId: Record<string, PictureDescribeTask> = {
  'day-001': {
    id: 'picture-day-001-self-introduction',
    dayId: 'day-001',
    title: 'Self Introduction',
    goal: 'Say who you are and what you study.',
    image: day001Image,
    targetWords: ['name', 'I', 'student', 'English'],
    suggestedPatterns: ['My name is ...', 'I am ...', 'I study ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['My name is Li.', 'I am a student.', 'I study English.'],
  },
  'day-002': {
    id: 'picture-day-002-student-at-desk',
    dayId: 'day-002',
    title: 'Student at a Desk',
    goal: 'Say what the student is doing.',
    image: day002Image,
    targetWords: ['student', 'desk', 'book', 'pencil'],
    suggestedPatterns: ['This is ...', 'He is ...', 'I can see ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is a student.', 'He is at a desk.', 'I can see a book.'],
  },
  'day-003': {
    id: 'picture-day-003-question',
    dayId: 'day-003',
    title: 'A Question',
    goal: 'Say what question you can ask.',
    image: day003Image,
    targetWords: ['question', 'book', 'desk', 'student'],
    suggestedPatterns: ['I have ...', 'This is ...', 'There is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['I have a question.', 'This is a student.', 'There is a book.'],
  },
  'day-004': {
    id: 'picture-day-004-my-friend',
    dayId: 'day-004',
    title: 'My Friend',
    goal: 'Introduce a friend in the picture.',
    image: day004Image,
    targetWords: ['friend', 'student', 'school', 'book'],
    suggestedPatterns: ['This is my ...', 'He is ...', 'She is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my friend.', 'She is a student.', 'She has a book.'],
  },
  'day-005': {
    id: 'picture-day-005-kind-person',
    dayId: 'day-005',
    title: 'A Kind Person',
    goal: 'Say what the person is like.',
    image: day005Image,
    targetWords: ['kind', 'person', 'help', 'book'],
    suggestedPatterns: ['He is ...', 'She is ...', 'This is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is a kind person.', 'He helps a friend.', 'There is a book.'],
  },
  'day-006': {
    id: 'picture-day-006-study-english',
    dayId: 'day-006',
    title: 'Study English',
    goal: 'Say why you study English.',
    image: day006Image,
    targetWords: ['study', 'English', 'book', 'want'],
    suggestedPatterns: ['I study ...', 'I want ...', 'because ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['I study English.', 'I have a book.', 'I want to learn.'],
  },
  'day-007': {
    id: 'picture-day-007-week-1-scene',
    dayId: 'day-007',
    title: 'Week 1 Scene',
    goal: 'Use Week 1 words to describe the scene.',
    image: day007Image,
    targetWords: ['name', 'student', 'friend', 'English'],
    suggestedPatterns: ['My name is ...', 'I am ...', 'I have ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['My name is Li.', 'I am a student.', 'I have a friend.'],
  },
  'day-008': {
    id: 'picture-day-008-my-room',
    dayId: 'day-008',
    title: 'My Room',
    goal: 'Say what you can see in this room.',
    image: day008Image,
    targetWords: ['room', 'bed', 'table', 'window'],
    suggestedPatterns: ['This is ...', 'There is ...', 'I can see ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my room.', 'There is a bed.', 'I can see a table.'],
  },
  'day-009': {
    id: 'picture-day-009-things-on-table',
    dayId: 'day-009',
    title: 'Things on a Table',
    goal: 'Name things on the table.',
    image: day009Image,
    targetWords: ['table', 'book', 'cup', 'pen'],
    suggestedPatterns: ['There is ...', 'There are ...', 'I have ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['There is a table.', 'There is a book.', 'I have a pen.'],
  },
  'day-010': {
    id: 'picture-day-010-morning-at-home',
    dayId: 'day-010',
    title: 'Morning at Home',
    goal: 'Say what the home looks like in the morning.',
    image: day010Image,
    targetWords: ['home', 'morning', 'door', 'window'],
    suggestedPatterns: ['This is ...', 'It is ...', 'I can see ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my home.', 'It is morning.', 'I can see a window.'],
  },
  'day-011': {
    id: 'picture-day-011-kitchen-breakfast',
    dayId: 'day-011',
    title: 'Food Room Breakfast',
    goal: 'Say what is in the food room.',
    image: day011Image,
    targetWords: ['food', 'breakfast', 'cup', 'table'],
    suggestedPatterns: ['There is ...', 'I have ...', 'This is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is a food room.', 'There is a cup.', 'I have breakfast.'],
  },
  'day-012': {
    id: 'picture-day-012-cleaning-room',
    dayId: 'day-012',
    title: 'Cleaning a Room',
    goal: 'Say what a person can do in the room.',
    image: day012Image,
    targetWords: ['clean', 'room', 'chair', 'box'],
    suggestedPatterns: ['I can ...', 'There is ...', 'It is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['I can clean the room.', 'There is a chair.', 'There is a box.'],
  },
  'day-013': {
    id: 'picture-day-013-evening-at-home',
    dayId: 'day-013',
    title: 'Evening at Home',
    goal: 'Say what is at home.',
    image: day013Image,
    targetWords: ['evening', 'home', 'book', 'friend'],
    suggestedPatterns: ['This is ...', 'I can see ...', 'It is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['It is evening.', 'This is my home.', 'I can see a book.'],
  },
  'day-014': {
    id: 'picture-day-014-home-check',
    dayId: 'day-014',
    title: 'Home Week',
    goal: 'Use Week 2 words to describe the home scene.',
    image: day014Image,
    targetWords: ['home', 'room', 'bed', 'table'],
    suggestedPatterns: ['This is ...', 'There is ...', 'I have ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my home.', 'There is a room.', 'I have a table.'],
  },
  'day-015': {
    id: 'picture-day-015-morning-routine',
    dayId: 'day-015',
    title: 'Morning Order',
    goal: 'Describe what the person does in the morning.',
    image: day015Image,
    targetWords: ['morning', 'get', 'wash', 'face', 'water', 'clothes'],
    suggestedPatterns: ['I get up in the morning.', 'I wash my face.', 'I put on my clothes.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I get up in the morning.', 'I wash my face.', 'I put on my clothes.', 'I have water.'],
  },
  'day-016': {
    id: 'picture-day-016-going-to-school-work',
    dayId: 'day-016',
    title: 'Going to School or Work',
    goal: 'Say where the person goes and what the person takes.',
    image: day016Image,
    targetWords: ['go', 'school', 'work', 'take', 'bag', 'road'],
    suggestedPatterns: ['I go to school.', 'I go to work.', 'I take my bag.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I go to school.', 'I go to work.', 'I take my bag.', 'I walk on the road.'],
  },
  'day-017': {
    id: 'picture-day-017-useful-actions',
    dayId: 'day-017',
    title: 'Doing Useful Things',
    goal: 'Describe useful actions with things on the desk.',
    image: day017Image,
    targetWords: ['open', 'read', 'write', 'book', 'pen', 'paper'],
    suggestedPatterns: ['I open the book.', 'I read a book.', 'I use a pen to write.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I open the book.', 'I read a book.', 'I write on paper.', 'I use a pen to write.'],
  },
  'day-018': {
    id: 'picture-day-018-time-of-day',
    dayId: 'day-018',
    title: 'Time of Day',
    goal: 'Describe actions at different times of day.',
    image: day018Image,
    targetWords: ['morning', 'afternoon', 'evening', 'night', 'study', 'sleep'],
    suggestedPatterns: ['In the morning, I get up.', 'In the afternoon, I study.', 'At night, I sleep.'],
    requiredSentenceCount: 4,
    simpleVersion: ['In the morning, I get up.', 'In the afternoon, I study.', 'In the evening, I read.', 'At night, I sleep.'],
  },
  'day-019': {
    id: 'picture-day-019-action-order',
    dayId: 'day-019',
    title: 'Action Order',
    goal: 'Put the person actions in a simple order.',
    image: day019Image,
    targetWords: ['first', 'then', 'next', 'last', 'open', 'close'],
    suggestedPatterns: ['First, I open the book.', 'Then I read.', 'Last, I close the book.'],
    requiredSentenceCount: 4,
    simpleVersion: ['First, I open the book.', 'Then I read.', 'Next, I write.', 'Last, I close the book.'],
  },
  'day-020': {
    id: 'picture-day-020-everyday-habits',
    dayId: 'day-020',
    title: 'Every Day Habits',
    goal: 'Describe every day study and practice habits.',
    image: day020Image,
    targetWords: ['often', 'sometimes', 'practice', 'habit', 'English', 'day'],
    suggestedPatterns: ['I practice English every day.', 'I often read.', 'I sometimes walk.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I practice English every day.', 'I often read.', 'I sometimes walk.', 'This is a good habit.'],
  },
  'day-021': {
    id: 'picture-day-021-normal-day-check',
    dayId: 'day-021',
    title: 'One Normal Day',
    goal: 'Describe one normal day from morning to evening.',
    image: day021Image,
    targetWords: ['morning', 'afternoon', 'evening', 'go', 'study', 'home'],
    suggestedPatterns: ['I get up in the morning.', 'In the afternoon, I study.', 'In the evening, I am at home.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I get up in the morning.', 'I go to school.', 'In the afternoon, I study.', 'In the evening, I am at home.'],
  },
  'day-022': {
    id: 'picture-day-022-food-and-drink',
    dayId: 'day-022',
    title: 'Food and Drink',
    goal: 'Describe food and drink on the table.',
    image: day022Image,
    targetWords: ['food', 'drink', 'bread', 'milk', 'rice', 'fruit'],
    suggestedPatterns: ['I eat bread.', 'I drink milk.', 'I have fruit.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I eat bread.', 'I drink milk.', 'I eat rice.', 'I have fruit.'],
  },
  'day-023': {
    id: 'picture-day-023-want-and-need',
    dayId: 'day-023',
    title: 'Want and Need',
    goal: 'Say what the person wants, needs, and needs help with.',
    image: day023Image,
    targetWords: ['want', 'need', 'water', 'food', 'help', 'problem'],
    suggestedPatterns: ['I want some water.', 'I need food.', 'Please help me.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I want some water.', 'I need food.', 'I need help.', 'Please help me.'],
  },
  'day-024': {
    id: 'picture-day-024-buying-simple-things',
    dayId: 'day-024',
    title: 'Buying Simple Things',
    goal: 'Describe buying simple things at a shop.',
    image: day024Image,
    targetWords: ['shop', 'buy', 'bread', 'milk', 'money', 'thing'],
    suggestedPatterns: ['I go to the shop.', 'I buy bread.', 'I get milk from the shop.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I go to the shop.', 'I buy bread.', 'I get milk from the shop.', 'I have money.'],
  },
  'day-025': {
    id: 'picture-day-025-money-and-price',
    dayId: 'day-025',
    title: 'Money and Price',
    goal: 'Describe price, paying, and change at a shop.',
    image: day025Image,
    targetWords: ['money', 'price', 'pay', 'cheap', 'dear', 'change'],
    suggestedPatterns: ['The price is cheap.', 'I pay for food.', 'I get change.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I buy food.', 'The price is good.', 'I pay for food.', 'I get change.'],
  },
  'day-026': {
    id: 'picture-day-026-asking-for-help',
    dayId: 'day-026',
    title: 'Asking for Help',
    goal: 'Ask another person for simple help.',
    image: day026Image,
    targetWords: ['ask', 'help', 'please', 'find', 'show', 'bring'],
    suggestedPatterns: ['Please help me.', 'Can you show me the book?', 'I ask for help.'],
    requiredSentenceCount: 4,
    simpleVersion: ['Please help me.', 'Can you show me the book?', 'Can you bring me the book?', 'I ask for help.'],
  },
  'day-027': {
    id: 'picture-day-027-more-enough-good',
    dayId: 'day-027',
    title: 'More, Enough, and Good',
    goal: 'Describe if food and drink are enough, full, empty, or good.',
    image: day027Image,
    targetWords: ['more', 'enough', 'full', 'empty', 'food', 'good'],
    suggestedPatterns: ['I need more water.', 'I have enough food.', 'The cup is empty.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I need more water.', 'I have enough food.', 'The cup is empty.', 'The food is good.'],
  },
  'day-028': {
    id: 'picture-day-028-meal-shopping-check',
    dayId: 'day-028',
    title: 'Meal and Shopping Week',
    goal: 'Describe a simple meal and shopping scene.',
    image: day028Image,
    targetWords: ['food', 'drink', 'shop', 'buy', 'need', 'help'],
    suggestedPatterns: ['I go to the shop.', 'I buy food.', 'Please help me.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I go to the shop.', 'I buy food.', 'I need help.', 'Please help me.'],
  },
  'day-029': {
    id: 'picture-day-029-getting-ready-to-go-out',
    dayId: 'day-029',
    title: 'Getting Ready to Go Out',
    goal: 'Say how you get ready to go out.',
    image: day029Image,
    targetWords: ['ready', 'bag', 'list', 'outside'],
    suggestedPatterns: ['I am ready.', 'I have my bag.', 'I go outside.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I am ready.', 'I have my bag.', 'I have a list.', 'I go outside.'],
  },
  'day-030': {
    id: 'picture-day-030-walking-to-the-bus-place',
    dayId: 'day-030',
    title: 'Walking to the Bus Place',
    goal: 'Say how you walk to the bus place.',
    image: day030Image,
    targetWords: ['walk', 'road', 'bus', 'seat'],
    suggestedPatterns: ['I walk on the road.', 'The bus place is near.', 'I am waiting for the bus.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I walk on the road.', 'The bus place is near.', 'I am waiting for the bus.', 'The seat is here.'],
  },
  'day-031': {
    id: 'picture-day-031-taking-the-bus',
    dayId: 'day-031',
    title: 'Left and Right Way',
    goal: 'Say the way, the road, and the turn.',
    image: day031Image,
    targetWords: ['left', 'right', 'straight', 'turn', 'way', 'road'],
    suggestedPatterns: ['I go straight.', 'I turn left.', 'The way is straight.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I go straight.', 'I turn left.', 'I turn right.', 'The road is near.'],
  },
  'day-032': {
    id: 'picture-day-032-finding-things-in-store',
    dayId: 'day-032',
    title: 'Finding Things in the Store',
    goal: 'Describe finding things in a store.',
    image: day032Image,
    targetWords: ['store', 'find', 'bread', 'milk'],
    suggestedPatterns: ['I am in the store.', 'I find bread.', 'The thing is here.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I am in the store.', 'I find bread.', 'I find milk.', 'The thing is here.'],
  },
  'day-033': {
    id: 'picture-day-033-waiting-and-paying',
    dayId: 'day-033',
    title: 'Waiting and Paying',
    goal: 'Describe being in line and paying in a store.',
    image: day033Image,
    targetWords: ['line', 'waiting', 'pay', 'change'],
    suggestedPatterns: ['I am in line.', 'I am waiting in line.', 'I pay for food.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I am in line.', 'I am waiting in line.', 'I pay for food.', 'I get change.'],
  },
  'day-034': {
    id: 'picture-day-034-coming-back-home',
    dayId: 'day-034',
    title: 'Coming Back Home',
    goal: 'Say how you come back home.',
    image: day034Image,
    targetWords: ['carry', 'bag', 'light', 'home'],
    suggestedPatterns: ['I carry my bag.', 'The bag is light.', 'I go back home.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I carry my bag.', 'The bag is light.', 'I go back home.', 'I put food on the table.'],
  },
  'day-035': {
    id: 'picture-day-035-errand-story-recap',
    dayId: 'day-035',
    title: 'Going Out Story',
    goal: 'Tell a simple outside story.',
    image: day035Image,
    targetWords: ['outside', 'list', 'bus', 'store', 'food', 'home'],
    suggestedPatterns: ['I go outside with my list.', 'I take the bus.', 'I go back home.'],
    requiredSentenceCount: 6,
    simpleVersion: [
      'I go outside with my list.',
      'I take the bus.',
      'I am in the store.',
      'I buy food at the store.',
      'I carry my bag.',
      'I go back home.',
    ],
  },
  'day-036': {
    id: 'picture-day-036-early-and-late-bus',
    dayId: 'day-036',
    title: 'Early and Late Bus',
    goal: 'Say early, late, waiting, bus, and time.',
    image: day036Image,
    targetWords: ['early', 'late', 'waiting', 'bus', 'time'],
    suggestedPatterns: ['I am early.', 'I am late.', 'I am waiting for the bus.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I am early.', 'I am late.', 'I am waiting for the bus.', 'The bus is late.'],
  },
  'day-037': {
    id: 'picture-day-037-no-clear-way',
    dayId: 'day-037',
    title: 'No Clear Way',
    goal: 'Say the way is not clear and you need help.',
    image: day037Image,
    targetWords: ['clear', 'way', 'another', 'help'],
    suggestedPatterns: ['The way is not clear.', 'I need another way.', 'Please help me.'],
    requiredSentenceCount: 4,
    simpleVersion: ['The way is not clear.', 'I need another way.', 'Please help me.', 'The way is clear.'],
  },
  'day-038': {
    id: 'picture-day-038-wrong-way',
    dayId: 'day-038',
    title: 'Wrong Way',
    goal: 'Say this way is wrong and take another way.',
    image: day038Image,
    targetWords: ['wrong', 'another', 'way', 'turn', 'straight'],
    suggestedPatterns: ['This way is wrong.', 'I need another way.', 'I turn left.'],
    requiredSentenceCount: 4,
    simpleVersion: ['This way is wrong.', 'I need another way.', 'I go straight.', 'I turn left.'],
  },
  'day-039': {
    id: 'picture-day-039-please-repeat',
    dayId: 'day-039',
    title: 'Please Repeat',
    goal: 'Ask for repeat in a help talk.',
    image: day039Image,
    targetWords: ['understand', 'repeat', 'please', 'help'],
    suggestedPatterns: ['I do not understand.', 'Please repeat.', 'I understand now.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I do not understand.', 'Please repeat.', 'I need help.', 'I understand now.'],
  },
  'day-040': {
    id: 'picture-day-040-ask-again',
    dayId: 'day-040',
    title: 'Ask Again',
    goal: 'Ask again in a simple help talk.',
    image: day040Image,
    targetWords: ['understand', 'repeat', 'again', 'please'],
    suggestedPatterns: ['I do not understand.', 'Please repeat.', 'Say it again, please.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I do not understand.', 'Please repeat.', 'Say it again, please.', 'I understand now.'],
  },
  'day-041': {
    id: 'picture-day-041-polite-help',
    dayId: 'day-041',
    title: 'Kind Help',
    goal: 'Use kind words when help is needed.',
    image: day041Image,
    targetWords: ['excuse', 'sorry', 'please', 'kind'],
    suggestedPatterns: ['Excuse me.', 'I am sorry.', 'Please help me.'],
    requiredSentenceCount: 4,
    simpleVersion: ['Excuse me.', 'I am sorry.', 'Please help me.', 'You are kind.'],
  },
  'day-042': {
    id: 'picture-day-042-problem-story-recap',
    dayId: 'day-042',
    title: 'Problem Story',
    goal: 'Tell a simple outside problem story.',
    image: day042Image,
    targetWords: ['way', 'clear', 'wrong', 'another', 'repeat', 'kind'],
    suggestedPatterns: ['The way is not clear.', 'This way is wrong.', 'I need another way.'],
    requiredSentenceCount: 6,
    simpleVersion: [
      'The way is not clear.',
      'This way is wrong.',
      'I need another way.',
      'Please repeat.',
      'I understand.',
      'I am kind.',
    ],
  },
  'day-043': {
    id: 'picture-day-043-body-parts',
    dayId: 'day-043',
    title: 'Body Parts',
    goal: 'Name simple body parts.',
    image: day043Image,
    targetWords: ['body', 'head', 'hand', 'foot'],
    suggestedPatterns: ['This is my head.', 'This is my hand.'],
    requiredSentenceCount: 4,
    simpleVersion: ['This is my head.', 'This is my hand.', 'This is my foot.', 'This is my body.'],
  },
  'day-044': {
    id: 'picture-day-044-feel-ill',
    dayId: 'day-044',
    title: 'Feel Ill',
    goal: 'Say how the body feels.',
    image: day044Image,
    targetWords: ['ill', 'tired', 'rest', 'water'],
    suggestedPatterns: ['I feel ill.', 'I am tired.', 'I need rest.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I feel ill.', 'I am tired.', 'I need rest.', 'I need water.'],
  },
  'day-045': {
    id: 'picture-day-045-body-pain',
    dayId: 'day-045',
    title: 'Body Pain',
    goal: 'Say where the body pain is.',
    image: day045Image,
    targetWords: ['pain', 'head', 'hand', 'foot'],
    suggestedPatterns: ['I have pain in my head.', 'I need care.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I have pain in my head.', 'I have pain in my hand.', 'I have pain in my foot.', 'I need care.'],
  },
  'day-046': {
    id: 'picture-day-046-need-rest',
    dayId: 'day-046',
    title: 'Need Rest',
    goal: 'Ask for rest, water, and help.',
    image: day046Image,
    targetWords: ['rest', 'water', 'tired', 'help'],
    suggestedPatterns: ['I need rest.', 'I need water.', 'Please help me.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I am tired.', 'I need rest.', 'I need water.', 'Please help me.'],
  },
  'day-047': {
    id: 'picture-day-047-warm-care',
    dayId: 'day-047',
    title: 'Warm Care',
    goal: 'Say simple care for an ill body.',
    image: day047Image,
    targetWords: ['warm', 'care', 'body', 'rest'],
    suggestedPatterns: ['I keep warm.', 'I need care.', 'I need rest.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I feel ill.', 'I need care.', 'I need rest.', 'I keep warm.'],
  },
  'day-048': {
    id: 'picture-day-048-tell-body-problem',
    dayId: 'day-048',
    title: 'Tell the Body Problem',
    goal: 'Tell a person what is wrong with your body.',
    image: day048Image,
    targetWords: ['tell', 'problem', 'body', 'help'],
    suggestedPatterns: ['I feel ill.', 'I have pain in my head.', 'Please help me.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I have a body problem.', 'I feel ill.', 'I have pain in my head.', 'Please help me.'],
  },
  'day-049': {
    id: 'picture-day-049-body-care-story',
    dayId: 'day-049',
    title: 'Body Care Story',
    goal: 'Tell a body problem story from pain to care.',
    image: day049Image,
    targetWords: ['body', 'pain', 'ill', 'care', 'rest'],
    suggestedPatterns: ['I feel ill.', 'I have pain in my head.', 'I need care.'],
    requiredSentenceCount: 6,
    simpleVersion: ['I feel ill.', 'I am tired.', 'I have pain in my head.', 'I need rest.', 'I need water.', 'I need care.'],
  },
  ...week8to12PictureDescribeTasksByDayId,
};
