import day001Image from '../assets/picture-describe/day-001-self-introduction.png';
import day002Image from '../assets/picture-describe/day-002-student-at-desk.png';
import day003Image from '../assets/picture-describe/day-003-question.png';
import day004Image from '../assets/picture-describe/day-004-my-friend.png';
import day005Image from '../assets/picture-describe/day-005-kind-person.png';
import day006Image from '../assets/picture-describe/day-006-study-english.png';
import day007Image from '../assets/picture-describe/day-007-week-1-scene.png';
import day008Image from '../assets/picture-describe/day-008-my-room.png';
import day009Image from '../assets/picture-describe/day-009-things-on-table.png';
import day010Image from '../assets/picture-describe/day-010-morning-at-home.png';
import day011Image from '../assets/picture-describe/day-011-kitchen-breakfast.png';
import day012Image from '../assets/picture-describe/day-012-cleaning-room.png';
import day013Image from '../assets/picture-describe/day-013-evening-at-home.png';
import day014Image from '../assets/picture-describe/day-014-home-check.png';
import type { PictureDescribeTask } from '../domain/types';

export const pictureDescribeTasksByDayId: Record<string, PictureDescribeTask> = {
  'day-001': {
    id: 'picture-day-001-self-introduction',
    dayId: 'day-001',
    title: 'Self Introduction',
    goal: 'Say who you are and what you study.',
    image: day001Image,
    targetWords: ['name', 'I', 'student', 'English'],
    suggestedPatterns: ['My name is ...', 'I am ...', 'I study ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['My name is Li.', 'I am a student.', 'I study English.'],
  },
  'day-002': {
    id: 'picture-day-002-student-at-desk',
    dayId: 'day-002',
    title: 'Student at a Desk',
    goal: 'Say what the student is doing.',
    image: day002Image,
    targetWords: ['student', 'desk', 'book', 'pencil'],
    suggestedPatterns: ['This is ...', 'He is ...', 'I can see ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is a student.', 'He is at a desk.', 'I can see a book.'],
  },
  'day-003': {
    id: 'picture-day-003-question',
    dayId: 'day-003',
    title: 'A Question',
    goal: 'Say what question you can ask.',
    image: day003Image,
    targetWords: ['question', 'book', 'desk', 'student'],
    suggestedPatterns: ['I have ...', 'This is ...', 'There is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['I have a question.', 'This is a student.', 'There is a book.'],
  },
  'day-004': {
    id: 'picture-day-004-my-friend',
    dayId: 'day-004',
    title: 'My Friend',
    goal: 'Introduce a friend in the picture.',
    image: day004Image,
    targetWords: ['friend', 'student', 'school', 'book'],
    suggestedPatterns: ['This is my ...', 'He is ...', 'She is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my friend.', 'She is a student.', 'She has a book.'],
  },
  'day-005': {
    id: 'picture-day-005-kind-person',
    dayId: 'day-005',
    title: 'A Kind Person',
    goal: 'Say what the person is like.',
    image: day005Image,
    targetWords: ['kind', 'person', 'help', 'book'],
    suggestedPatterns: ['He is ...', 'She is ...', 'This is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is a kind person.', 'He helps a friend.', 'There is a book.'],
  },
  'day-006': {
    id: 'picture-day-006-study-english',
    dayId: 'day-006',
    title: 'Study English',
    goal: 'Say why you study English.',
    image: day006Image,
    targetWords: ['study', 'English', 'book', 'want'],
    suggestedPatterns: ['I study ...', 'I want ...', 'because ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['I study English.', 'I have a book.', 'I want to learn.'],
  },
  'day-007': {
    id: 'picture-day-007-week-1-scene',
    dayId: 'day-007',
    title: 'Week 1 Scene',
    goal: 'Use Week 1 words to describe the scene.',
    image: day007Image,
    targetWords: ['name', 'student', 'friend', 'English'],
    suggestedPatterns: ['My name is ...', 'I am ...', 'I have ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['My name is Li.', 'I am a student.', 'I have a friend.'],
  },
  'day-008': {
    id: 'picture-day-008-my-room',
    dayId: 'day-008',
    title: 'My Room',
    goal: 'Say what you can see in this room.',
    image: day008Image,
    targetWords: ['room', 'bed', 'table', 'window'],
    suggestedPatterns: ['This is ...', 'There is ...', 'I can see ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my room.', 'There is a bed.', 'I can see a table.'],
  },
  'day-009': {
    id: 'picture-day-009-things-on-table',
    dayId: 'day-009',
    title: 'Things on a Table',
    goal: 'Name things on the table.',
    image: day009Image,
    targetWords: ['table', 'book', 'cup', 'pen'],
    suggestedPatterns: ['There is ...', 'There are ...', 'I have ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['There is a table.', 'There is a book.', 'I have a pen.'],
  },
  'day-010': {
    id: 'picture-day-010-morning-at-home',
    dayId: 'day-010',
    title: 'Morning at Home',
    goal: 'Say what the home looks like in the morning.',
    image: day010Image,
    targetWords: ['home', 'morning', 'door', 'window'],
    suggestedPatterns: ['This is ...', 'It is ...', 'I can see ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my home.', 'It is morning.', 'I can see a window.'],
  },
  'day-011': {
    id: 'picture-day-011-kitchen-breakfast',
    dayId: 'day-011',
    title: 'Kitchen Breakfast',
    goal: 'Say what is in the kitchen.',
    image: day011Image,
    targetWords: ['kitchen', 'breakfast', 'cup', 'table'],
    suggestedPatterns: ['There is ...', 'I have ...', 'This is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is a kitchen.', 'There is a cup.', 'I have breakfast.'],
  },
  'day-012': {
    id: 'picture-day-012-cleaning-room',
    dayId: 'day-012',
    title: 'Cleaning a Room',
    goal: 'Say what someone can do in the room.',
    image: day012Image,
    targetWords: ['clean', 'room', 'chair', 'box'],
    suggestedPatterns: ['I can ...', 'There is ...', 'It is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['I can clean the room.', 'There is a chair.', 'There is a box.'],
  },
  'day-013': {
    id: 'picture-day-013-evening-at-home',
    dayId: 'day-013',
    title: 'Evening at Home',
    goal: 'Say what is happening at home.',
    image: day013Image,
    targetWords: ['evening', 'home', 'book', 'friend'],
    suggestedPatterns: ['This is ...', 'I can see ...', 'It is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['It is evening.', 'This is my home.', 'I can see a book.'],
  },
  'day-014': {
    id: 'picture-day-014-home-check',
    dayId: 'day-014',
    title: 'Home Check',
    goal: 'Use Week 2 words to describe the home scene.',
    image: day014Image,
    targetWords: ['home', 'room', 'bed', 'table'],
    suggestedPatterns: ['This is ...', 'There is ...', 'I have ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my home.', 'There is a room.', 'I have a table.'],
  },
};
