import day001Image from '../assets/picture-describe/day-001-self-introduction.png';
import day002Image from '../assets/picture-describe/day-002-student-at-desk.png';
import day003Image from '../assets/picture-describe/day-003-question.png';
import day004Image from '../assets/picture-describe/day-004-my-friend.png';
import day005Image from '../assets/picture-describe/day-005-kind-person.png';
import day006Image from '../assets/picture-describe/day-006-study-english.png';
import day007Image from '../assets/picture-describe/day-007-week-1-scene.png';
import day008Image from '../assets/picture-describe/day-008-my-room.png';
import day009Image from '../assets/picture-describe/day-009-things-on-table.png';
import day010Image from '../assets/picture-describe/day-010-morning-at-home.png';
import day011Image from '../assets/picture-describe/day-011-kitchen-breakfast.png';
import day012Image from '../assets/picture-describe/day-012-cleaning-room.png';
import day013Image from '../assets/picture-describe/day-013-evening-at-home.png';
import day014Image from '../assets/picture-describe/day-014-home-check.png';
import day015Image from '../assets/picture-describe/day-015-morning-routine.png';
import day016Image from '../assets/picture-describe/day-016-going-to-school-work.png';
import day017Image from '../assets/picture-describe/day-017-useful-actions.png';
import day018Image from '../assets/picture-describe/day-018-time-of-day.png';
import day019Image from '../assets/picture-describe/day-019-action-order.png';
import day020Image from '../assets/picture-describe/day-020-everyday-habits.png';
import day021Image from '../assets/picture-describe/day-021-normal-day-check.png';
import day022Image from '../assets/picture-describe/day-022-food-and-drink.png';
import day023Image from '../assets/picture-describe/day-023-want-and-need.png';
import day024Image from '../assets/picture-describe/day-024-buying-simple-things.png';
import day025Image from '../assets/picture-describe/day-025-money-and-price.png';
import day026Image from '../assets/picture-describe/day-026-asking-for-help.png';
import day027Image from '../assets/picture-describe/day-027-more-enough-good.png';
import day028Image from '../assets/picture-describe/day-028-meal-shopping-check.png';
import type { PictureDescribeTask } from '../domain/types';

export const pictureDescribeTasksByDayId: Record<string, PictureDescribeTask> = {
  'day-001': {
    id: 'picture-day-001-self-introduction',
    dayId: 'day-001',
    title: 'Self Introduction',
    goal: 'Say who you are and what you study.',
    image: day001Image,
    targetWords: ['name', 'I', 'student', 'English'],
    suggestedPatterns: ['My name is ...', 'I am ...', 'I study ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['My name is Li.', 'I am a student.', 'I study English.'],
  },
  'day-002': {
    id: 'picture-day-002-student-at-desk',
    dayId: 'day-002',
    title: 'Student at a Desk',
    goal: 'Say what the student is doing.',
    image: day002Image,
    targetWords: ['student', 'desk', 'book', 'pencil'],
    suggestedPatterns: ['This is ...', 'He is ...', 'I can see ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is a student.', 'He is at a desk.', 'I can see a book.'],
  },
  'day-003': {
    id: 'picture-day-003-question',
    dayId: 'day-003',
    title: 'A Question',
    goal: 'Say what question you can ask.',
    image: day003Image,
    targetWords: ['question', 'book', 'desk', 'student'],
    suggestedPatterns: ['I have ...', 'This is ...', 'There is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['I have a question.', 'This is a student.', 'There is a book.'],
  },
  'day-004': {
    id: 'picture-day-004-my-friend',
    dayId: 'day-004',
    title: 'My Friend',
    goal: 'Introduce a friend in the picture.',
    image: day004Image,
    targetWords: ['friend', 'student', 'school', 'book'],
    suggestedPatterns: ['This is my ...', 'He is ...', 'She is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my friend.', 'She is a student.', 'She has a book.'],
  },
  'day-005': {
    id: 'picture-day-005-kind-person',
    dayId: 'day-005',
    title: 'A Kind Person',
    goal: 'Say what the person is like.',
    image: day005Image,
    targetWords: ['kind', 'person', 'help', 'book'],
    suggestedPatterns: ['He is ...', 'She is ...', 'This is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is a kind person.', 'He helps a friend.', 'There is a book.'],
  },
  'day-006': {
    id: 'picture-day-006-study-english',
    dayId: 'day-006',
    title: 'Study English',
    goal: 'Say why you study English.',
    image: day006Image,
    targetWords: ['study', 'English', 'book', 'want'],
    suggestedPatterns: ['I study ...', 'I want ...', 'because ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['I study English.', 'I have a book.', 'I want to learn.'],
  },
  'day-007': {
    id: 'picture-day-007-week-1-scene',
    dayId: 'day-007',
    title: 'Week 1 Scene',
    goal: 'Use Week 1 words to describe the scene.',
    image: day007Image,
    targetWords: ['name', 'student', 'friend', 'English'],
    suggestedPatterns: ['My name is ...', 'I am ...', 'I have ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['My name is Li.', 'I am a student.', 'I have a friend.'],
  },
  'day-008': {
    id: 'picture-day-008-my-room',
    dayId: 'day-008',
    title: 'My Room',
    goal: 'Say what you can see in this room.',
    image: day008Image,
    targetWords: ['room', 'bed', 'table', 'window'],
    suggestedPatterns: ['This is ...', 'There is ...', 'I can see ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my room.', 'There is a bed.', 'I can see a table.'],
  },
  'day-009': {
    id: 'picture-day-009-things-on-table',
    dayId: 'day-009',
    title: 'Things on a Table',
    goal: 'Name things on the table.',
    image: day009Image,
    targetWords: ['table', 'book', 'cup', 'pen'],
    suggestedPatterns: ['There is ...', 'There are ...', 'I have ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['There is a table.', 'There is a book.', 'I have a pen.'],
  },
  'day-010': {
    id: 'picture-day-010-morning-at-home',
    dayId: 'day-010',
    title: 'Morning at Home',
    goal: 'Say what the home looks like in the morning.',
    image: day010Image,
    targetWords: ['home', 'morning', 'door', 'window'],
    suggestedPatterns: ['This is ...', 'It is ...', 'I can see ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my home.', 'It is morning.', 'I can see a window.'],
  },
  'day-011': {
    id: 'picture-day-011-kitchen-breakfast',
    dayId: 'day-011',
    title: 'Kitchen Breakfast',
    goal: 'Say what is in the kitchen.',
    image: day011Image,
    targetWords: ['kitchen', 'breakfast', 'cup', 'table'],
    suggestedPatterns: ['There is ...', 'I have ...', 'This is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is a kitchen.', 'There is a cup.', 'I have breakfast.'],
  },
  'day-012': {
    id: 'picture-day-012-cleaning-room',
    dayId: 'day-012',
    title: 'Cleaning a Room',
    goal: 'Say what someone can do in the room.',
    image: day012Image,
    targetWords: ['clean', 'room', 'chair', 'box'],
    suggestedPatterns: ['I can ...', 'There is ...', 'It is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['I can clean the room.', 'There is a chair.', 'There is a box.'],
  },
  'day-013': {
    id: 'picture-day-013-evening-at-home',
    dayId: 'day-013',
    title: 'Evening at Home',
    goal: 'Say what is happening at home.',
    image: day013Image,
    targetWords: ['evening', 'home', 'book', 'friend'],
    suggestedPatterns: ['This is ...', 'I can see ...', 'It is ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['It is evening.', 'This is my home.', 'I can see a book.'],
  },
  'day-014': {
    id: 'picture-day-014-home-check',
    dayId: 'day-014',
    title: 'Home Check',
    goal: 'Use Week 2 words to describe the home scene.',
    image: day014Image,
    targetWords: ['home', 'room', 'bed', 'table'],
    suggestedPatterns: ['This is ...', 'There is ...', 'I have ...'],
    requiredSentenceCount: 3,
    simpleVersion: ['This is my home.', 'There is a room.', 'I have a table.'],
  },
  'day-015': {
    id: 'picture-day-015-morning-routine',
    dayId: 'day-015',
    title: 'Morning Routine',
    goal: 'Describe what the learner does in the morning.',
    image: day015Image,
    targetWords: ['morning', 'get', 'wash', 'face', 'water', 'clothes'],
    suggestedPatterns: ['I get up in the morning.', 'I wash my face.', 'I put on my clothes.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I get up in the morning.', 'I wash my face.', 'I put on my clothes.', 'I have water.'],
  },
  'day-016': {
    id: 'picture-day-016-going-to-school-work',
    dayId: 'day-016',
    title: 'Going to School or Work',
    goal: 'Say where the learner goes and what the learner takes.',
    image: day016Image,
    targetWords: ['go', 'school', 'work', 'take', 'bag', 'road'],
    suggestedPatterns: ['I go to school.', 'I go to work.', 'I take my bag.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I go to school.', 'I go to work.', 'I take my bag.', 'I walk on the road.'],
  },
  'day-017': {
    id: 'picture-day-017-useful-actions',
    dayId: 'day-017',
    title: 'Doing Useful Things',
    goal: 'Describe useful actions with things on the desk.',
    image: day017Image,
    targetWords: ['open', 'read', 'write', 'book', 'pen', 'paper'],
    suggestedPatterns: ['I open the book.', 'I read a book.', 'I use a pen to write.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I open the book.', 'I read a book.', 'I write on paper.', 'I use a pen to write.'],
  },
  'day-018': {
    id: 'picture-day-018-time-of-day',
    dayId: 'day-018',
    title: 'Time of Day',
    goal: 'Describe actions at different times of day.',
    image: day018Image,
    targetWords: ['morning', 'afternoon', 'evening', 'night', 'study', 'sleep'],
    suggestedPatterns: ['In the morning, I get up.', 'In the afternoon, I study.', 'At night, I sleep.'],
    requiredSentenceCount: 4,
    simpleVersion: ['In the morning, I get up.', 'In the afternoon, I study.', 'In the evening, I read.', 'At night, I sleep.'],
  },
  'day-019': {
    id: 'picture-day-019-action-order',
    dayId: 'day-019',
    title: 'Action Order',
    goal: 'Put the learner actions in a simple order.',
    image: day019Image,
    targetWords: ['first', 'then', 'next', 'last', 'open', 'close'],
    suggestedPatterns: ['First, I open the book.', 'Then I read.', 'Last, I close the book.'],
    requiredSentenceCount: 4,
    simpleVersion: ['First, I open the book.', 'Then I read.', 'Next, I write.', 'Last, I close the book.'],
  },
  'day-020': {
    id: 'picture-day-020-everyday-habits',
    dayId: 'day-020',
    title: 'Everyday Habits',
    goal: 'Describe everyday study and practice habits.',
    image: day020Image,
    targetWords: ['often', 'sometimes', 'practice', 'habit', 'English', 'day'],
    suggestedPatterns: ['I practice English every day.', 'I often read.', 'I sometimes walk.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I practice English every day.', 'I often read.', 'I sometimes walk.', 'This is a good habit.'],
  },
  'day-021': {
    id: 'picture-day-021-normal-day-check',
    dayId: 'day-021',
    title: 'One Normal Day',
    goal: 'Describe one normal day from morning to evening.',
    image: day021Image,
    targetWords: ['morning', 'afternoon', 'evening', 'go', 'study', 'home'],
    suggestedPatterns: ['I get up in the morning.', 'In the afternoon, I study.', 'In the evening, I am at home.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I get up in the morning.', 'I go to school.', 'In the afternoon, I study.', 'In the evening, I am at home.'],
  },
  'day-022': {
    id: 'picture-day-022-food-and-drink',
    dayId: 'day-022',
    title: 'Food and Drink',
    goal: 'Describe food and drink on the table.',
    image: day022Image,
    targetWords: ['food', 'drink', 'bread', 'milk', 'rice', 'fruit'],
    suggestedPatterns: ['I eat bread.', 'I drink milk.', 'I have fruit.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I eat bread.', 'I drink milk.', 'I eat rice.', 'I have fruit.'],
  },
  'day-023': {
    id: 'picture-day-023-want-and-need',
    dayId: 'day-023',
    title: 'Want and Need',
    goal: 'Say what the learner wants, needs, and needs help with.',
    image: day023Image,
    targetWords: ['want', 'need', 'water', 'food', 'help', 'problem'],
    suggestedPatterns: ['I want some water.', 'I need food.', 'Please help me.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I want some water.', 'I need food.', 'I need help.', 'Please help me.'],
  },
  'day-024': {
    id: 'picture-day-024-buying-simple-things',
    dayId: 'day-024',
    title: 'Buying Simple Things',
    goal: 'Describe buying simple things at a shop.',
    image: day024Image,
    targetWords: ['shop', 'buy', 'bread', 'milk', 'money', 'thing'],
    suggestedPatterns: ['I go to the shop.', 'I buy bread.', 'I get milk from the shop.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I go to the shop.', 'I buy bread.', 'I get milk from the shop.', 'I have money.'],
  },
  'day-025': {
    id: 'picture-day-025-money-and-price',
    dayId: 'day-025',
    title: 'Money and Price',
    goal: 'Describe price, paying, and change at a shop.',
    image: day025Image,
    targetWords: ['money', 'price', 'pay', 'cheap', 'dear', 'change'],
    suggestedPatterns: ['The price is cheap.', 'I pay for food.', 'I get change.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I buy food.', 'The price is good.', 'I pay for food.', 'I get change.'],
  },
  'day-026': {
    id: 'picture-day-026-asking-for-help',
    dayId: 'day-026',
    title: 'Asking for Help',
    goal: 'Ask another person for simple help.',
    image: day026Image,
    targetWords: ['ask', 'help', 'please', 'find', 'show', 'bring'],
    suggestedPatterns: ['Please help me.', 'Can you show me the book?', 'I ask for help.'],
    requiredSentenceCount: 4,
    simpleVersion: ['Please help me.', 'Can you show me the book?', 'Can you bring me the book?', 'I ask for help.'],
  },
  'day-027': {
    id: 'picture-day-027-more-enough-good',
    dayId: 'day-027',
    title: 'More, Enough, and Good',
    goal: 'Describe if food and drink are enough, full, empty, or good.',
    image: day027Image,
    targetWords: ['more', 'enough', 'full', 'empty', 'food', 'good'],
    suggestedPatterns: ['I need more water.', 'I have enough food.', 'The cup is empty.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I need more water.', 'I have enough food.', 'The cup is empty.', 'The food is good.'],
  },
  'day-028': {
    id: 'picture-day-028-meal-shopping-check',
    dayId: 'day-028',
    title: 'Meal and Shopping Check',
    goal: 'Describe a simple meal and shopping scene.',
    image: day028Image,
    targetWords: ['food', 'drink', 'shop', 'buy', 'need', 'help'],
    suggestedPatterns: ['I go to the shop.', 'I buy food.', 'Please help me.'],
    requiredSentenceCount: 4,
    simpleVersion: ['I go to the shop.', 'I buy food.', 'I need help.', 'Please help me.'],
  },
};
