import type { ScenarioCapability, ScenarioWeek } from '../domain/types';

export const scenarioWeekMap: ScenarioWeek[] = [
  { weekNumber: 1, theme: 'Person & Self', expressionOutcome: 'Say who you are and who another person is.' },
  { weekNumber: 2, theme: 'Home & Things', expressionOutcome: 'Describe your room, things, and where things are.' },
  { weekNumber: 3, theme: 'Every Day', expressionOutcome: 'Say what you do every day.' },
  { weekNumber: 4, theme: 'Food & Shopping', expressionOutcome: 'Order food and buy simple things.' },
  { weekNumber: 5, theme: 'Going Out Story', expressionOutcome: 'Tell a complete going out story.' },
  { weekNumber: 6, theme: 'Problems Outside', expressionOutcome: 'Describe outside problems and ask for help in a kind way.' },
  { weekNumber: 7, theme: 'Problems & Help', expressionOutcome: 'Tell a problem and ask for help.' },
  { weekNumber: 8, theme: 'Body', expressionOutcome: 'Describe simple body problems.' },
  { weekNumber: 9, theme: 'Yesterday Ideas', expressionOutcome: 'Tell a yesterday story.' },
  { weekNumber: 10, theme: 'Tomorrow', expressionOutcome: 'Say what you will do tomorrow or after tomorrow.' },
  { weekNumber: 11, theme: 'Opinions & Reasons', expressionOutcome: 'Say what you like, do not like, and why.' },
  { weekNumber: 12, theme: 'Last Practice', expressionOutcome: 'Answer daily practice questions.' },
];

export const scenarioCapabilities: ScenarioCapability[] = [
  {
    id: 'introduce-myself',
    title: 'I can say who I am.',
    description: 'Say your name, place, and student self.',
    unlockedByDayIds: ['day-001'],
    exampleOutputs: ['My name is Li.', 'I am from China.'],
  },
  {
    id: 'introduce-another-person',
    title: 'I can introduce another person.',
    description: 'Introduce a friend or family person.',
    unlockedByDayIds: ['day-004'],
    exampleOutputs: ['This is my friend.', 'She is kind.'],
  },
  {
    id: 'say-why-i-study-english',
    title: 'I can say why I study English.',
    description: 'Give a simple reason for learning English.',
    unlockedByDayIds: ['day-006'],
    exampleOutputs: ['I study English because it is useful.'],
  },
  {
    id: 'describe-my-room',
    title: 'I can describe my room.',
    description: 'Say simple facts about your room.',
    unlockedByDayIds: ['day-008'],
    exampleOutputs: ['This is my room.', 'My room is small.'],
  },
  {
    id: 'say-things-in-my-room',
    title: 'I can say what things are in my room.',
    description: 'Say what things are in your room.',
    unlockedByDayIds: ['day-009'],
    exampleOutputs: ['There is a book in my room.'],
  },
  {
    id: 'say-where-things-are',
    title: 'I can say where things are.',
    description: 'Use in, on, under, and near.',
    unlockedByDayIds: ['day-010'],
    exampleOutputs: ['The book is on the table.'],
  },
  {
    id: 'describe-study-things',
    title: 'I can describe study things on my table.',
    description: 'Describe a table and study things.',
    unlockedByDayIds: ['day-011'],
    exampleOutputs: ['There is a pen on my table.'],
  },
  {
    id: 'describe-personal-things',
    title: 'I can describe personal things in my bag.',
    description: 'Describe personal things used every day.',
    unlockedByDayIds: ['day-012'],
    exampleOutputs: ['My phone is in my bag.'],
  },
  {
    id: 'describe-important-things',
    title: 'I can describe important things in my day.',
    description: 'Say why a thing is useful or important.',
    unlockedByDayIds: ['day-014'],
    exampleOutputs: ['It is important.', 'I use it every day.'],
  },
  {
    id: 'describe-my-morning',
    title: 'I can describe my morning.',
    description: 'Say simple actions from getting up to going out from home.',
    unlockedByDayIds: ['day-015'],
    exampleOutputs: ['I get up in the morning.', 'I wash my face.'],
  },
  {
    id: 'say-where-i-go-every-day',
    title: 'I can say where I go every day.',
    description: 'Say where you go and what you take.',
    unlockedByDayIds: ['day-016'],
    exampleOutputs: ['I go to school.', 'I take my bag.'],
  },
  {
    id: 'describe-common-actions',
    title: 'I can say what I do with common things.',
    description: 'Use things to describe simple daily actions.',
    unlockedByDayIds: ['day-017'],
    exampleOutputs: ['I use a pen to write.', 'I open the book.'],
  },
  {
    id: 'describe-normal-day-in-order',
    title: 'I can describe one normal day in order.',
    description: 'Use time and order words to describe a day.',
    unlockedByDayIds: ['day-021'],
    exampleOutputs: ['First, I get up.', 'In the evening, I read.'],
  },
  {
    id: 'talk-about-food-and-drink',
    title: 'I can talk about food and drink.',
    description: 'Say what you eat and drink.',
    unlockedByDayIds: ['day-022'],
    exampleOutputs: ['I eat bread.', 'I drink water.'],
  },
  {
    id: 'say-wants-and-needs',
    title: 'I can say what I want and need.',
    description: 'Use want and need for daily things.',
    unlockedByDayIds: ['day-023'],
    exampleOutputs: ['I want some water.', 'I need help.'],
  },
  {
    id: 'buy-simple-things',
    title: 'I can buy simple things.',
    description: 'Describe getting things from a shop.',
    unlockedByDayIds: ['day-024'],
    exampleOutputs: ['I go to the shop.', 'I buy bread.'],
  },
  {
    id: 'ask-for-help',
    title: 'I can ask for help.',
    description: 'Ask another person for simple help.',
    unlockedByDayIds: ['day-026'],
    exampleOutputs: ['Please help me.', 'Can you show me the book?'],
  },
  {
    id: 'describe-meal-or-shopping-scene',
    title: 'I can describe a meal or shopping scene.',
    description: 'Put together food, shopping, wants, needs, and help.',
    unlockedByDayIds: ['day-028'],
    exampleOutputs: ['I buy food.', 'I need more water.'],
  },
  {
    id: 'errand-story',
    title: 'I can tell a going out story.',
    description: 'Tell how you go out, take a bus, buy things at a store, and come home.',
    unlockedByDayIds: ['day-035'],
    exampleOutputs: ['I go out with my list.', 'I take the bus.', 'I buy bread at the store.', 'I come home.'],
  },
  {
    id: 'outside-problems',
    title: 'I can ask for help outside.',
    description: 'Ask for help in a kind way when there is a problem outside.',
    unlockedByDayIds: ['day-042'],
    exampleOutputs: ['I have a problem outside.', 'Please help me.', 'I ask for help.', 'I am kind.'],
  },
];
