import type { Pattern, Week, Word } from '../domain/types';

export const week3Words: Word[] = [
  { id: 'morning', text: 'morning', category: 'general_thing', definition: 'the early part of the day', phonetic: '/\u02c8m\u0254\u02d0n\u026a\u014b/', chinese: '早上', example: 'I get up in the morning.', weekIntroduced: 3, tags: ['time', 'routine'] },
  { id: 'get', text: 'get', category: 'operation', definition: 'to come to have something', phonetic: '/\u0261et/', chinese: '得到；到达', example: 'I get up in the morning.', weekIntroduced: 3, tags: ['action'] },
  { id: 'up', text: 'up', category: 'structure', definition: 'to a high place or out of bed', phonetic: '/\u028cp/', chinese: '向上；起身', example: 'I get up.', weekIntroduced: 3, tags: ['action'] },
  { id: 'wash', text: 'wash', category: 'operation', definition: 'to make clean with water', phonetic: '/w\u0252\u0283/', chinese: '洗', example: 'I wash my face.', weekIntroduced: 3, tags: ['routine'] },
  { id: 'face', text: 'face', category: 'picturable_thing', definition: 'the front part of the head', phonetic: '/fe\u026as/', chinese: '脸', example: 'I wash my face.', weekIntroduced: 3, tags: ['body'] },
  { id: 'water', text: 'water', category: 'general_thing', definition: 'clear drink used for washing', phonetic: '/\u02c8w\u0254\u02d0t\u0259/', chinese: '水', example: 'I drink water.', weekIntroduced: 3, tags: ['daily'] },
  { id: 'put', text: 'put', category: 'operation', definition: 'to move something to a place', phonetic: '/p\u028at/', chinese: '放', example: 'I put my book in my bag.', weekIntroduced: 3, tags: ['action'] },
  { id: 'clothes', text: 'clothes', category: 'general_thing', definition: 'things on a person', phonetic: '/kl\u0259\u028a\u00f0z/', chinese: '衣服', example: 'I put on my clothes.', weekIntroduced: 3, tags: ['daily'] },
  { id: 'go', text: 'go', category: 'operation', definition: 'to move from one place to another', phonetic: '/\u0261\u0259\u028a/', chinese: '去', example: 'I go to school.', weekIntroduced: 3, tags: ['movement'] },
  { id: 'school', text: 'school', category: 'general_thing', definition: 'a place where persons study', phonetic: '/sku\u02d0l/', chinese: '学校', example: 'I go to school.', weekIntroduced: 3, tags: ['place'] },
  { id: 'work', text: 'work', category: 'operation', definition: 'to do a useful act', phonetic: '/w\u025c\u02d0k/', chinese: '工作', example: 'I go to work.', weekIntroduced: 3, tags: ['daily'] },
  { id: 'take', text: 'take', category: 'operation', definition: 'to carry or bring something with you', phonetic: '/te\u026ak/', chinese: '带；拿', example: 'I take my bag.', weekIntroduced: 3, tags: ['action'] },
  { id: 'road', text: 'road', category: 'picturable_thing', definition: 'a way for walking or moving', phonetic: '/r\u0259\u028ad/', chinese: '路', example: 'I walk on the road.', weekIntroduced: 3, tags: ['place'] },
  { id: 'bus', text: 'bus', category: 'picturable_thing', definition: 'a great carriage for persons', phonetic: '/b\u028cs/', chinese: '公交车', example: 'I go by bus.', weekIntroduced: 3, tags: ['travel'] },
  { id: 'walk', text: 'walk', category: 'operation', definition: 'to move on foot', phonetic: '/w\u0254\u02d0k/', chinese: '走路', example: 'I walk to school.', weekIntroduced: 3, tags: ['movement'] },
  { id: 'with', text: 'with', category: 'structure', definition: 'together with another person or thing', phonetic: '/w\u026a\u00f0/', chinese: '和；带着', example: 'I go with my friend.', weekIntroduced: 3, tags: ['structure'] },
  { id: 'do', text: 'do', category: 'operation', definition: 'to make an act', phonetic: '/du\u02d0/', chinese: '做', example: 'I do my work.', weekIntroduced: 3, tags: ['action'] },
  { id: 'make', text: 'make', category: 'operation', definition: 'to put together or get ready', phonetic: '/me\u026ak/', chinese: '做；制作', example: 'I make food.', weekIntroduced: 3, tags: ['action'] },
  { id: 'open', text: 'open', category: 'operation', definition: 'to move something so it is not closed', phonetic: '/\u02c8\u0259\u028ap\u0259n/', chinese: '打开', example: 'I open the book.', weekIntroduced: 3, tags: ['action'] },
  { id: 'close', text: 'close', category: 'operation', definition: 'to shut something', phonetic: '/kl\u0259\u028az/', chinese: '关闭', example: 'I close the door.', weekIntroduced: 3, tags: ['action'] },
  { id: 'give', text: 'give', category: 'operation', definition: 'to let another person have something', phonetic: '/\u0261\u026av/', chinese: '给', example: 'I give a book to my friend.', weekIntroduced: 3, tags: ['action'] },
  { id: 'see', text: 'see', category: 'operation', definition: 'to use your eyes', phonetic: '/si\u02d0/', chinese: '看见', example: 'I see a bus.', weekIntroduced: 3, tags: ['action'] },
  { id: 'read', text: 'read', category: 'operation', definition: 'to get meaning from words', phonetic: '/ri\u02d0d/', chinese: '读', example: 'I read a book.', weekIntroduced: 3, tags: ['study'] },
  { id: 'write', text: 'write', category: 'operation', definition: 'to make words with a pen', phonetic: '/ra\u026at/', chinese: '写', example: 'I write on paper.', weekIntroduced: 3, tags: ['study'] },
  { id: 'afternoon', text: 'afternoon', category: 'general_thing', definition: 'the part of the day after morning', phonetic: '/\u02cc\u0251\u02d0ft\u0259\u02c8nu\u02d0n/', chinese: '下午', example: 'I study in the afternoon.', weekIntroduced: 3, tags: ['time'] },
  { id: 'evening', text: 'evening', category: 'general_thing', definition: 'the late part of the day before night', phonetic: '/\u02c8i\u02d0vn\u026a\u014b/', chinese: '晚上', example: 'I am at home in the evening.', weekIntroduced: 3, tags: ['time'] },
  { id: 'night', text: 'night', category: 'general_thing', definition: 'the dark part of the day', phonetic: '/na\u026at/', chinese: '夜晚', example: 'I sleep at night.', weekIntroduced: 3, tags: ['time'] },
  { id: 'time', text: 'time', category: 'general_thing', definition: 'when something happens', phonetic: '/ta\u026am/', chinese: '时间', example: 'This is study time.', weekIntroduced: 3, tags: ['time'] },
  { id: 'before', text: 'before', category: 'structure', definition: 'in front of another time or action', phonetic: '/b\u026a\u02c8f\u0254\u02d0/', chinese: '在……之前', example: 'I wash before I go.', weekIntroduced: 3, tags: ['time'] },
  { id: 'after', text: 'after', category: 'structure', definition: 'coming past another time or action', phonetic: '/\u02c8\u0251\u02d0ft\u0259/', chinese: '在……之后', example: 'I study after food.', weekIntroduced: 3, tags: ['time'] },
  { id: 'sleep', text: 'sleep', category: 'operation', definition: 'to rest with eyes closed at night', phonetic: '/sli\u02d0p/', chinese: '睡觉', example: 'I sleep at night.', weekIntroduced: 3, tags: ['routine'] },
  { id: 'meal', text: 'meal', category: 'general_thing', definition: 'food at one time', phonetic: '/mi\u02d0l/', chinese: '一餐', example: 'I have a meal.', weekIntroduced: 3, tags: ['food'] },
  { id: 'first', text: 'first', category: 'structure', definition: 'before all others in order', phonetic: '/f\u025c\u02d0st/', chinese: '首先', example: 'First, I open my book.', weekIntroduced: 3, tags: ['sequence'] },
  { id: 'then', text: 'then', category: 'structure', definition: 'after that', phonetic: '/\u00f0en/', chinese: '然后', example: 'Then I write.', weekIntroduced: 3, tags: ['sequence'] },
  { id: 'next', text: 'next', category: 'structure', definition: 'coming after this one', phonetic: '/nekst/', chinese: '接着；下一个', example: 'Next, I close the book.', weekIntroduced: 3, tags: ['sequence'] },
  { id: 'last', text: 'last', category: 'structure', definition: 'after all others in order', phonetic: '/l\u0251\u02d0st/', chinese: '最后', example: 'Last, I put the book in my bag.', weekIntroduced: 3, tags: ['sequence'] },
  { id: 'start', text: 'start', category: 'operation', definition: 'to come to the first part', phonetic: '/st\u0251\u02d0t/', chinese: '开始', example: 'I start my work.', weekIntroduced: 3, tags: ['sequence'] },
  { id: 'finish', text: 'finish', category: 'operation', definition: 'to come to the end of an action', phonetic: '/\u02c8f\u026an\u026a\u0283/', chinese: '完成', example: 'I finish my work.', weekIntroduced: 3, tags: ['sequence'] },
  { id: 'same', text: 'same', category: 'quality', definition: 'not different', phonetic: '/se\u026am/', chinese: '相同的', example: 'I do the same thing every day.', weekIntroduced: 3, tags: ['quality'] },
  { id: 'order', text: 'order', category: 'general_thing', definition: 'the way things come one after another', phonetic: '/\u02c8\u0254\u02d0d\u0259/', chinese: '顺序', example: 'This is the order.', weekIntroduced: 3, tags: ['sequence'] },
  { id: 'always', text: 'always', category: 'structure', definition: 'at all times', phonetic: '/\u02c8\u0254\u02d0lwe\u026az/', chinese: '总是', example: 'I always study in the morning.', weekIntroduced: 3, tags: ['frequency'] },
  { id: 'often', text: 'often', category: 'structure', definition: 'much of the time', phonetic: '/\u02c8\u0252f\u0259n/', chinese: '经常', example: 'I often read.', weekIntroduced: 3, tags: ['frequency'] },
  { id: 'sometimes', text: 'sometimes', category: 'structure', definition: 'at some times but not always', phonetic: '/\u02c8s\u028cmta\u026amz/', chinese: '有时', example: 'I sometimes walk to school.', weekIntroduced: 3, tags: ['frequency'] },
  { id: 'never', text: 'never', category: 'structure', definition: 'not at any time', phonetic: '/\u02c8nev\u0259/', chinese: '从不', example: 'I never sleep at school.', weekIntroduced: 3, tags: ['frequency'] },
  { id: 'usually', text: 'usually', category: 'structure', definition: 'in the normal way or most times', phonetic: '/\u02c8ju\u02d0\u0292u\u0259li/', chinese: '通常', example: 'I usually go by bus.', weekIntroduced: 3, tags: ['frequency'] },
  { id: 'again', text: 'again', category: 'structure', definition: 'one more time', phonetic: '/\u0259\u02c8\u0261en/', chinese: '再次', example: 'I practice again.', weekIntroduced: 3, tags: ['frequency'] },
  { id: 'practice', text: 'practice', category: 'operation', definition: 'to do something again to get good at it', phonetic: '/\u02c8pr\u00e6kt\u026as/', chinese: '练习', example: 'I practice English every day.', weekIntroduced: 3, tags: ['study'] },
  { id: 'habit', text: 'habit', category: 'general_thing', definition: 'something you do often or every day', phonetic: '/\u02c8h\u00e6b\u026at/', chinese: '习惯', example: 'Study is a good habit.', weekIntroduced: 3, tags: ['routine'] },
];

export const week3Patterns: Pattern[] = [
  { id: 'i-get-up-in-morning', title: 'I get up in the morning.', use: 'Say a morning action.', structure: 'I get up in the morning.', examples: ['I get up in the morning.'], slots: [] },
  { id: 'i-wash-my', title: 'I wash my ___.', use: 'Say what you wash.', structure: 'I wash my {thing}.', examples: ['I wash my face.', 'I wash my hands.'], slots: ['thing'] },
  { id: 'i-put-on-my', title: 'I put on my ___.', use: 'Say what clothes you put on.', structure: 'I put on my {thing}.', examples: ['I put on my clothes.', 'I put on my bag.'], slots: ['thing'] },
  { id: 'i-go-to', title: 'I go to ___.', use: 'Say where you go.', structure: 'I go to {place}.', examples: ['I go to school.', 'I go to work.'], slots: ['place'] },
  { id: 'i-take-my', title: 'I take my ___.', use: 'Say what you carry with you.', structure: 'I take my {thing}.', examples: ['I take my bag.', 'I take my book.'], slots: ['thing'] },
  { id: 'i-go-with', title: 'I go with ___.', use: 'Say who goes with you.', structure: 'I go with {person}.', examples: ['I go with my friend.', 'I go with a student.'], slots: ['person'] },
  { id: 'i-use-to', title: 'I use ___ to ___.', use: 'Say what thing helps an action.', structure: 'I use {thing} to {action}.', examples: ['I use a pen to write.', 'I use water to wash.'], slots: ['thing', 'action'] },
  { id: 'i-open-the', title: 'I open the ___.', use: 'Say what you open.', structure: 'I open the {thing}.', examples: ['I open the book.', 'I open the door.'], slots: ['thing'] },
  { id: 'i-give-to', title: 'I give ___ to ___.', use: 'Say giving.', structure: 'I give {thing} to {person}.', examples: ['I give a book to my friend.', 'I give water to a student.'], slots: ['thing', 'person'] },
  { id: 'in-the-time-i', title: 'In the ___, I ___.', use: 'Say what you do at a time of day.', structure: 'In the {time}, I {action}.', examples: ['In the morning, I get up.', 'In the evening, I read.'], slots: ['time', 'action'] },
  { id: 'first-then-after', title: 'First, I ___. Then I ___.', use: 'Put actions in order.', structure: 'First, I {firstAction}. Then I {secondAction}.', examples: ['First, I open the book. Then I read.', 'First, I wash. Then I go.'], slots: ['firstAction', 'secondAction'] },
  { id: 'i-often', title: 'I often ___.', use: 'Say a repeated action.', structure: 'I often {action}.', examples: ['I often read.', 'I often walk to school.'], slots: ['action'] },
  { id: 'i-sometimes', title: 'I sometimes ___.', use: 'Say an action that happens at some times.', structure: 'I sometimes {action}.', examples: ['I sometimes walk.', 'I sometimes drink tea.'], slots: ['action'] },
  { id: 'i-practice-every-day', title: 'I practice ___ every day.', use: 'Say a daily practice habit.', structure: 'I practice {thing} every day.', examples: ['I practice English every day.', 'I practice writing every day.'], slots: ['thing'] },
];

export const week3: Week = {
  id: 'week-03',
  number: 3,
  title: 'Every Day and Time',
  goal: 'Say what you do every day, when you do it, and in what order.',
  days: [
    {
      id: 'day-015',
      weekId: 'week-03',
      dayNumber: 15,
      title: 'Morning Acts',
      goal: 'Describe simple things you do in the morning.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['morning', 'get', 'up', 'wash', 'face', 'water', 'put', 'clothes'],
      patternIds: ['i-get-up-in-morning', 'i-wash-my', 'i-put-on-my'],
      exercises: [
        { type: 'choice', id: 'day-015-choice-001', prompt: 'Which sentence is about morning?', options: ['I get up in the morning.', 'The book is under the table.', 'My key is important.'], correctOption: 'I get up in the morning.' },
        { type: 'fill_blank', id: 'day-015-fill-001', prompt: 'I wash my ___.', acceptedAnswers: ['face'] },
        { type: 'replacement', id: 'day-015-replace-001', patternId: 'i-wash-my', slotValues: { thing: 'face' }, referenceAnswer: 'I wash my face.' },
        { type: 'replacement', id: 'day-015-replace-002', patternId: 'i-put-on-my', slotValues: { thing: 'clothes' }, referenceAnswer: 'I put on my clothes.' },
        { type: 'sentence_order', id: 'day-015-order-001', tokens: ['up', 'get', 'I'], correctOrder: ['I', 'get', 'up'], finalSentence: 'I get up.' },
        { type: 'translation', id: 'day-015-translation-001', chinesePrompt: '我早上起床。我洗脸。', coreMeaningHint: 'Describe your morning.', suggestedPatternIds: ['i-get-up-in-morning', 'i-wash-my'], referenceAnswers: ['I get up in the morning. I wash my face.'] },
      ],
      outputTask: {
        id: 'day-015-output',
        topic: 'My Morning',
        prompts: ['What do you do in the morning?', 'What do you wash or put on?'],
        template: ['I get up in the morning.', 'I wash my ___.', 'I put on my ___.', 'I drink water.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-016',
      weekId: 'week-03',
      dayNumber: 16,
      title: 'Going to School or Work',
      goal: 'Say where you go and what you take with you.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['go', 'school', 'work', 'take', 'road', 'bus', 'walk', 'with', 'bag', 'book'],
      patternIds: ['i-go-to', 'i-take-my', 'i-go-with'],
      exercises: [
        { type: 'choice', id: 'day-016-choice-001', prompt: 'Which sentence says where you go?', options: ['I go to school.', 'I wash my face.', 'The cup is empty.'], correctOption: 'I go to school.' },
        { type: 'fill_blank', id: 'day-016-fill-001', prompt: 'I go to ___.', acceptedAnswers: ['school', 'work'] },
        { type: 'replacement', id: 'day-016-replace-001', patternId: 'i-go-to', slotValues: { place: 'school' }, referenceAnswer: 'I go to school.' },
        { type: 'replacement', id: 'day-016-replace-002', patternId: 'i-take-my', slotValues: { thing: 'bag' }, referenceAnswer: 'I take my bag.' },
        { type: 'sentence_order', id: 'day-016-order-001', tokens: ['my', 'take', 'I', 'book'], correctOrder: ['I', 'take', 'my', 'book'], finalSentence: 'I take my book.' },
        { type: 'translation', id: 'day-016-translation-001', chinesePrompt: '我去学校。我带着我的包。', coreMeaningHint: 'Say where you go and what you take.', suggestedPatternIds: ['i-go-to', 'i-take-my'], referenceAnswers: ['I go to school. I take my bag.'] },
      ],
      outputTask: {
        id: 'day-016-output',
        topic: 'Going Out',
        prompts: ['Where do you go?', 'What do you take?'],
        template: ['I go to ___.', 'I take my ___.', 'I walk on the road.', 'I go with ___.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-017',
      weekId: 'week-03',
      dayNumber: 17,
      title: 'Doing Useful Things',
      goal: 'Describe common actions with things.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['do', 'make', 'open', 'close', 'give', 'see', 'read', 'write', 'book', 'pen', 'paper'],
      patternIds: ['i-use-to', 'i-open-the', 'i-give-to'],
      exercises: [
        { type: 'choice', id: 'day-017-choice-001', prompt: 'Which sentence uses a thing to do an action?', options: ['I use a pen to write.', 'I am from China.', 'The bag is under the chair.'], correctOption: 'I use a pen to write.' },
        { type: 'fill_blank', id: 'day-017-fill-001', prompt: 'I ___ the book.', acceptedAnswers: ['open', 'close', 'read'] },
        { type: 'replacement', id: 'day-017-replace-001', patternId: 'i-use-to', slotValues: { thing: 'a pen', action: 'write' }, referenceAnswer: 'I use a pen to write.' },
        { type: 'replacement', id: 'day-017-replace-002', patternId: 'i-open-the', slotValues: { thing: 'book' }, referenceAnswer: 'I open the book.' },
        { type: 'sentence_order', id: 'day-017-order-001', tokens: ['read', 'I', 'book', 'a'], correctOrder: ['I', 'read', 'a', 'book'], finalSentence: 'I read a book.' },
        { type: 'translation', id: 'day-017-translation-001', chinesePrompt: '我用笔写字。我打开书。', coreMeaningHint: 'Describe actions with things.', suggestedPatternIds: ['i-use-to', 'i-open-the'], referenceAnswers: ['I use a pen to write. I open the book.'] },
      ],
      outputTask: {
        id: 'day-017-output',
        topic: 'Things I Do',
        prompts: ['What do you open, read, or write?', 'What do you use?'],
        template: ['I open the ___.', 'I read ___.', 'I use ___ to ___.', 'I give ___ to ___.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-018',
      weekId: 'week-03',
      dayNumber: 18,
      title: 'Time of Day',
      goal: 'Say what happens in the morning, afternoon, and evening.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['morning', 'afternoon', 'evening', 'night', 'time', 'before', 'after', 'sleep', 'meal', 'study'],
      patternIds: ['in-the-time-i'],
      exercises: [
        { type: 'choice', id: 'day-018-choice-001', prompt: 'Which sentence uses a time of day?', options: ['In the afternoon, I study.', 'The key is in the bag.', 'This is my cup.'], correctOption: 'In the afternoon, I study.' },
        { type: 'fill_blank', id: 'day-018-fill-001', prompt: 'In the ___, I sleep.', acceptedAnswers: ['night'] },
        { type: 'replacement', id: 'day-018-replace-001', patternId: 'in-the-time-i', slotValues: { time: 'morning', action: 'wash my face' }, referenceAnswer: 'In the morning, I wash my face.' },
        { type: 'replacement', id: 'day-018-replace-002', patternId: 'in-the-time-i', slotValues: { time: 'evening', action: 'read' }, referenceAnswer: 'In the evening, I read.' },
        { type: 'sentence_order', id: 'day-018-order-001', tokens: ['evening', 'the', 'read', 'I', 'In'], correctOrder: ['In', 'the', 'evening', 'I', 'read'], finalSentence: 'In the evening I read.' },
        { type: 'translation', id: 'day-018-translation-001', chinesePrompt: '早上我洗脸。晚上我读书。', coreMeaningHint: 'Use time-of-day words.', suggestedPatternIds: ['in-the-time-i'], referenceAnswers: ['In the morning, I wash my face. In the evening, I read.'] },
      ],
      outputTask: {
        id: 'day-018-output',
        topic: 'My Day Time',
        prompts: ['What do you do in the morning?', 'What do you do in the afternoon and evening?'],
        template: ['In the morning, I ___.', 'In the afternoon, I ___.', 'In the evening, I ___.', 'At night, I sleep.'],
        requiredSentenceCount: 5,
      },
    },
    {
      id: 'day-019',
      weekId: 'week-03',
      dayNumber: 19,
      title: 'First, Then, After',
      goal: 'Put daily actions in a simple order.',
      estimatedMinutes: 30,
      review: { wordCount: 7, patternCount: 3 },
      wordIds: ['first', 'then', 'next', 'last', 'start', 'finish', 'same', 'order', 'open', 'read', 'write', 'close'],
      patternIds: ['first-then-after'],
      exercises: [
        { type: 'choice', id: 'day-019-choice-001', prompt: 'Which word starts an ordered action?', options: ['First', 'Under', 'Dear'], correctOption: 'First' },
        { type: 'fill_blank', id: 'day-019-fill-001', prompt: 'First, I open the book. ___ I read.', acceptedAnswers: ['Then', 'then'] },
        { type: 'replacement', id: 'day-019-replace-001', patternId: 'first-then-after', slotValues: { firstAction: 'open the book', secondAction: 'read' }, referenceAnswer: 'First, I open the book. Then I read.' },
        { type: 'sentence_order', id: 'day-019-order-001', tokens: ['I', 'write', 'Then'], correctOrder: ['Then', 'I', 'write'], finalSentence: 'Then I write.' },
        { type: 'fill_blank', id: 'day-019-fill-002', prompt: 'Last, I ___ the book.', acceptedAnswers: ['close'] },
        { type: 'translation', id: 'day-019-translation-001', chinesePrompt: '首先，我打开书。然后我读。', coreMeaningHint: 'Put actions in order.', suggestedPatternIds: ['first-then-after'], referenceAnswers: ['First, I open the book. Then I read.'] },
      ],
      outputTask: {
        id: 'day-019-output',
        topic: 'Action Order',
        prompts: ['What do you do first?', 'What do you do next or last?'],
        template: ['First, I ___.', 'Then I ___.', 'Next, I ___.', 'Last, I ___.'],
        requiredSentenceCount: 5,
      },
    },
    {
      id: 'day-020',
      weekId: 'week-03',
      dayNumber: 20,
      title: 'Every Day Habits',
      goal: 'Describe things you do every day.',
      estimatedMinutes: 30,
      review: { wordCount: 7, patternCount: 3 },
      wordIds: ['always', 'often', 'sometimes', 'never', 'usually', 'again', 'practice', 'habit', 'every', 'day', 'english'],
      patternIds: ['i-often', 'i-sometimes', 'i-practice-every-day'],
      exercises: [
        { type: 'choice', id: 'day-020-choice-001', prompt: 'Which sentence describes a habit?', options: ['I practice English every day.', 'The book is on the table.', 'This is my key.'], correctOption: 'I practice English every day.' },
        { type: 'fill_blank', id: 'day-020-fill-001', prompt: 'I ___ read in the evening.', acceptedAnswers: ['often', 'sometimes', 'usually'] },
        { type: 'replacement', id: 'day-020-replace-001', patternId: 'i-often', slotValues: { action: 'read' }, referenceAnswer: 'I often read.' },
        { type: 'replacement', id: 'day-020-replace-002', patternId: 'i-practice-every-day', slotValues: { thing: 'English' }, referenceAnswer: 'I practice English every day.' },
        { type: 'sentence_order', id: 'day-020-order-001', tokens: ['often', 'I', 'read'], correctOrder: ['I', 'often', 'read'], finalSentence: 'I often read.' },
        { type: 'translation', id: 'day-020-translation-001', chinesePrompt: '我每天练习英语。我有时走路去学校。', coreMeaningHint: 'Describe habits.', suggestedPatternIds: ['i-sometimes', 'i-practice-every-day'], referenceAnswers: ['I practice English every day. I sometimes walk to school.'] },
      ],
      outputTask: {
        id: 'day-020-output',
        topic: 'My Habits',
        prompts: ['What do you do every day?', 'What do you often or sometimes do?'],
        template: ['I ___ every day.', 'I often ___.', 'I sometimes ___.', 'This is a good habit.'],
        requiredSentenceCount: 5,
      },
    },
    {
      id: 'day-021',
      weekId: 'week-03',
      dayNumber: 21,
      title: 'Week 3 Story',
      goal: 'Describe one normal day from morning to evening.',
      estimatedMinutes: 35,
      review: { wordCount: 8, patternCount: 4 },
      wordIds: ['morning', 'afternoon', 'evening', 'get', 'go', 'do', 'read', 'write', 'first', 'then', 'after', 'every'],
      patternIds: ['i-get-up-in-morning', 'in-the-time-i', 'first-then-after', 'i-practice-every-day'],
      exercises: [
        { type: 'choice', id: 'day-021-choice-001', prompt: 'Which sentence describes a normal day?', options: ['First, I get up. Then I go to school.', 'The key is under the chair.', 'My cup is red.'], correctOption: 'First, I get up. Then I go to school.' },
        { type: 'fill_blank', id: 'day-021-fill-001', prompt: 'In the ___, I get up.', acceptedAnswers: ['morning'] },
        { type: 'replacement', id: 'day-021-replace-001', patternId: 'in-the-time-i', slotValues: { time: 'afternoon', action: 'study' }, referenceAnswer: 'In the afternoon, I study.' },
        { type: 'replacement', id: 'day-021-replace-002', patternId: 'first-then-after', slotValues: { firstAction: 'get up', secondAction: 'go to school' }, referenceAnswer: 'First, I get up. Then I go to school.' },
        { type: 'sentence_order', id: 'day-021-order-001', tokens: ['practice', 'English', 'every', 'I', 'day'], correctOrder: ['I', 'practice', 'English', 'every', 'day'], finalSentence: 'I practice English every day.' },
        { type: 'translation', id: 'day-021-translation-001', chinesePrompt: '早上我起床。下午我学习。晚上我在家。', coreMeaningHint: 'Describe one normal day.', suggestedPatternIds: ['i-get-up-in-morning', 'in-the-time-i'], referenceAnswers: ['I get up in the morning. In the afternoon, I study. In the evening, I am at home.'] },
      ],
      outputTask: {
        id: 'day-021-output',
        topic: 'One Normal Day',
        prompts: ['What do you do from morning to evening?', 'What is the order?'],
        template: ['I get up in the morning.', 'First, I ___.', 'Then I ___.', 'In the afternoon, I ___.', 'In the evening, I ___.', 'This is my normal day.'],
        requiredSentenceCount: 6,
      },
      weeklyCheckRubric: {
        scale: { min: 0, max: 2 },
        pass: { minimumTotalScore: 7, minimumMeaningScore: 1, minimumSentenceCount: 6 },
        criteria: [
          { id: 'meaning', label: 'Meaning', scores: ['hard to understand', 'partly clear', 'clear'] },
          { id: 'time-order', label: 'Time order', scores: ['no clear order', 'some order words', 'clear morning-to-evening order'] },
          { id: 'target-patterns', label: 'Form use', scores: ['not used', 'used with help', 'used with no help'] },
          { id: 'word-use', label: 'Word use', scores: ['little day words', 'some day words', 'much day words'] },
          { id: 'independence', label: 'My words', scores: ['same as example', 'some change from example', 'all my words'] },
        ],
      },
    },
  ],
};
