import type { Pattern, Week, Word } from '../domain/types';

export const week6Words: Word[] = [
  { id: 'late', text: 'late', category: 'quality', definition: 'after the right time', phonetic: '/le\u026at/', chinese: '迟到的；晚的', example: 'I am late.', weekIntroduced: 6, tags: ['problem'] },
  { id: 'early', text: 'early', category: 'quality', definition: 'before the right time', phonetic: '/\u02c8\u025c\u02d0li/', chinese: '早的', example: 'I am early.', weekIntroduced: 6, tags: ['time'] },
  { id: 'clear', text: 'clear', category: 'quality', definition: 'simple to see or understand', phonetic: '/kl\u026a\u0259/', chinese: '清楚的', example: 'The way is clear.', weekIntroduced: 6, tags: ['problem'] },
  { id: 'wrong', text: 'wrong', category: 'quality', definition: 'not right or not correct', phonetic: '/r\u0252\u014b/', chinese: '错误的', example: 'This way is wrong.', weekIntroduced: 6, tags: ['problem'] },
  { id: 'another', text: 'another', category: 'structure', definition: 'one more or a different one', phonetic: '/\u0259\u02c8n\u028c\u00f0\u0259/', chinese: '另一个', example: 'I need another way.', weekIntroduced: 6, tags: ['problem'] },
  { id: 'understand', text: 'understand', category: 'operation', definition: 'to get the meaning', phonetic: '/\u02cc\u028cnd\u0259\u02c8st\u00e6nd/', chinese: '理解；明白', example: 'I understand.', weekIntroduced: 6, tags: ['communication'] },
  { id: 'repeat', text: 'repeat', category: 'operation', definition: 'to say or do again', phonetic: '/r\u026a\u02c8pi\u02d0t/', chinese: '重复；再说一遍', example: 'Please repeat.', weekIntroduced: 6, tags: ['communication'] },
  { id: 'sorry', text: 'sorry', category: 'structure', definition: 'a word for a wrong act or trouble', phonetic: '/\u02c8s\u0252ri/', chinese: '对不起', example: 'I am sorry.', weekIntroduced: 6, tags: ['polite'] },
  { id: 'excuse', text: 'excuse', category: 'operation', definition: 'to ask politely for attention', phonetic: '/\u026ak\u02c8skju\u02d0z/', chinese: '打扰一下', example: 'Excuse me.', weekIntroduced: 6, tags: ['polite'] },
  { id: 'safe', text: 'safe', category: 'quality', definition: 'free from danger', phonetic: '/se\u026af/', chinese: '安全的', example: 'The way is safe.', weekIntroduced: 6, tags: ['problem'] },
];

export const week6Patterns: Pattern[] = [
  { id: 'i-am-late', title: 'I am late.', use: 'Say you are after the right time.', structure: 'I am late.', examples: ['I am late.'], slots: [] },
  { id: 'i-am-early', title: 'I am early.', use: 'Say you are before the right time.', structure: 'I am early.', examples: ['I am early.'], slots: [] },
  { id: 'the-way-is-not-clear', title: 'The way is not clear.', use: 'Say you have no clear way.', structure: 'The way is not clear.', examples: ['The way is not clear.'], slots: [] },
  { id: 'this-is-wrong', title: 'This is wrong.', use: 'Say something is not right.', structure: 'This is wrong.', examples: ['This is wrong.', 'This way is wrong.'], slots: [] },
  { id: 'i-need-another', title: 'I need another ___.', use: 'Ask for one more or a different thing.', structure: 'I need another {thing}.', examples: ['I need another way.', 'I need another seat.'], slots: ['thing'] },
  { id: 'i-understand', title: 'I understand.', use: 'Say the meaning is clear.', structure: 'I understand.', examples: ['I understand.'], slots: [] },
  { id: 'i-do-not-understand', title: 'I do not understand.', use: 'Say the meaning is not clear.', structure: 'I do not understand.', examples: ['I do not understand.'], slots: [] },
  { id: 'please-repeat', title: 'Please repeat.', use: 'Ask a person to say it again.', structure: 'Please repeat.', examples: ['Please repeat.'], slots: [] },
  { id: 'sorry-excuse-me', title: 'Sorry. Excuse me.', use: 'Use kind words for a problem.', structure: 'Sorry. Excuse me.', examples: ['Sorry. Excuse me.'], slots: [] },
  { id: 'i-am-kind', title: 'I am kind.', use: 'Close a help talk with kind words.', structure: 'I am kind.', examples: ['I am kind.'], slots: [] },
];

export const week6: Week = {
  id: 'week-06',
  number: 6,
  title: 'Problems Outside',
  goal: 'Answer simple problems outside with clear and kind English.',
  days: [
    {
      id: 'day-036',
      weekId: 'week-06',
      dayNumber: 36,
      title: 'Early and Late',
      goal: 'Say if you are early or late.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['early', 'late', 'time', 'waiting', 'bus', 'school', 'work'],
      patternIds: ['i-am-early', 'i-am-late', 'i-am-waiting-for'],
      exercises: [
        { type: 'choice', id: 'day-036-choice-001', prompt: 'Which sentence says a time problem?', options: ['I am late.', 'The bag is light.', 'I eat bread.'], correctOption: 'I am late.' },
        { type: 'fill_blank', id: 'day-036-fill-001', prompt: 'I am ___.', acceptedAnswers: ['early', 'late'] },
        { type: 'replacement', id: 'day-036-replace-001', patternId: 'i-am-waiting-for', slotValues: { thing: 'the bus' }, referenceAnswer: 'I am waiting for the bus.' },
        { type: 'sentence_order', id: 'day-036-order-001', tokens: ['am', 'late', 'I'], correctOrder: ['I', 'am', 'late'], finalSentence: 'I am late.' },
        { type: 'fill_blank', id: 'day-036-fill-002', prompt: 'I am ___ for school.', acceptedAnswers: ['early', 'late'] },
        { type: 'translation', id: 'day-036-translation-001', chinesePrompt: '我迟到了，正在等公共汽车。', coreMeaningHint: 'Say a time problem.', suggestedPatternIds: ['i-am-late', 'i-am-waiting-for'], referenceAnswers: ['I am late. I am waiting for the bus.'] },
      ],
      outputTask: {
        id: 'day-036-output',
        topic: 'Late or Early',
        prompts: ['Are you early or late?', 'What are you waiting for?'],
        template: ['I am ___.', 'I am waiting for ___.', 'The bus is ___.', 'I go to ___.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about being early or late and waiting outside.',
      },
    },
    {
      id: 'day-037',
      weekId: 'week-06',
      dayNumber: 37,
      title: 'No Clear Way',
      goal: 'Say that the way is not clear and you need a way.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['clear', 'way', 'outside', 'road', 'near', 'far', 'help'],
      patternIds: ['the-way-is-not-clear', 'i-need-another', 'please-help-me'],
      exercises: [
        { type: 'choice', id: 'day-037-choice-001', prompt: 'Which sentence asks for help outside?', options: ['The way is not clear. Please help me.', 'I drink tea.', 'The cup is on the table.'], correctOption: 'The way is not clear. Please help me.' },
        { type: 'fill_blank', id: 'day-037-fill-001', prompt: 'The way is not ___.', acceptedAnswers: ['clear'] },
        { type: 'replacement', id: 'day-037-replace-001', patternId: 'i-need-another', slotValues: { thing: 'way' }, referenceAnswer: 'I need another way.' },
        { type: 'sentence_order', id: 'day-037-order-001', tokens: ['clear', 'not', 'is', 'way', 'The'], correctOrder: ['The', 'way', 'is', 'not', 'clear'], finalSentence: 'The way is not clear.' },
        { type: 'fill_blank', id: 'day-037-fill-002', prompt: 'Please ___ me.', acceptedAnswers: ['help'] },
        { type: 'translation', id: 'day-037-translation-001', chinesePrompt: '路线不清楚，我需要另一条路。', coreMeaningHint: 'Ask for help when the way is not clear.', suggestedPatternIds: ['the-way-is-not-clear', 'i-need-another', 'please-help-me'], referenceAnswers: ['The way is not clear. I need another way. Please help me.'] },
      ],
      outputTask: {
        id: 'day-037-output',
        topic: 'No Clear Way',
        prompts: ['What is the problem?', 'What do you need?'],
        template: ['The way is not clear.', 'I need another ___.', 'Please help me.', 'The way is ___.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about having no clear way outside and asking for help.',
      },
    },
    {
      id: 'day-038',
      weekId: 'week-06',
      dayNumber: 38,
      title: 'Wrong Way',
      goal: 'Say that something is wrong and choose another way.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['wrong', 'another', 'way', 'left', 'right', 'straight', 'turn'],
      patternIds: ['this-is-wrong', 'i-need-another', 'i-turn', 'i-go-straight'],
      exercises: [
        { type: 'choice', id: 'day-038-choice-001', prompt: 'Which sentence says a direction problem?', options: ['This way is wrong.', 'The food is good.', 'I have a red pen.'], correctOption: 'This way is wrong.' },
        { type: 'fill_blank', id: 'day-038-fill-001', prompt: 'This way is ___.', acceptedAnswers: ['wrong'] },
        { type: 'replacement', id: 'day-038-replace-001', patternId: 'i-need-another', slotValues: { thing: 'way' }, referenceAnswer: 'I need another way.' },
        { type: 'replacement', id: 'day-038-replace-002', patternId: 'i-turn', slotValues: { side: 'left' }, referenceAnswer: 'I turn left.' },
        { type: 'sentence_order', id: 'day-038-order-001', tokens: ['is', 'wrong', 'This'], correctOrder: ['This', 'is', 'wrong'], finalSentence: 'This is wrong.' },
        { type: 'translation', id: 'day-038-translation-001', chinesePrompt: '这条路错了，我需要另一条路。', coreMeaningHint: 'Change a wrong way.', suggestedPatternIds: ['this-is-wrong', 'i-need-another', 'i-turn'], referenceAnswers: ['This is wrong. I need another way. I turn left.'] },
      ],
      outputTask: {
        id: 'day-038-output',
        topic: 'Another Way',
        prompts: ['What is wrong?', 'Which way do you take?'],
        template: ['This way is wrong.', 'I need another ___.', 'I go straight.', 'I turn ___.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about a wrong way and another way outside.',
      },
    },
    {
      id: 'day-039',
      weekId: 'week-06',
      dayNumber: 39,
      title: 'Repeat Please',
      goal: 'Ask a person to repeat when you do not understand.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['understand', 'repeat', 'please', 'answer', 'question', 'tell', 'help'],
      patternIds: ['i-understand', 'i-do-not-understand', 'please-repeat'],
      exercises: [
        { type: 'choice', id: 'day-039-choice-001', prompt: 'Which sentence asks for words again?', options: ['Please repeat.', 'I buy bread.', 'The bag has much weight.'], correctOption: 'Please repeat.' },
        { type: 'fill_blank', id: 'day-039-fill-001', prompt: 'I do not ___.', acceptedAnswers: ['understand'] },
        { type: 'sentence_order', id: 'day-039-order-001', tokens: ['repeat', 'Please'], correctOrder: ['Please', 'repeat'], finalSentence: 'Please repeat.' },
        { type: 'fill_blank', id: 'day-039-fill-002', prompt: 'I ___ now.', acceptedAnswers: ['understand'] },
        { type: 'choice', id: 'day-039-choice-002', prompt: 'Which sentence says the meaning is clear?', options: ['I understand.', 'I am late.', 'The bus is far.'], correctOption: 'I understand.' },
        { type: 'translation', id: 'day-039-translation-001', chinesePrompt: '我不明白，请再说一遍。', coreMeaningHint: 'Ask to get words again.', suggestedPatternIds: ['i-do-not-understand', 'please-repeat'], referenceAnswers: ['I do not understand. Please repeat.'] },
      ],
      outputTask: {
        id: 'day-039-output',
        topic: 'Please Repeat',
        prompts: ['Do you understand?', 'What do you ask?'],
        template: ['I do not understand.', 'Please repeat.', 'I understand now.', 'I am kind.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about not understanding, asking for repeat, and understanding.',
      },
    },
    {
      id: 'day-040',
      weekId: 'week-06',
      dayNumber: 40,
      title: 'Sorry and Excuse Me',
      goal: 'Use kind words for a small problem outside.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['sorry', 'excuse', 'problem', 'wrong', 'line', 'seat', 'please'],
      patternIds: ['sorry-excuse-me', 'this-is-wrong', 'please-help-me'],
      exercises: [
        { type: 'choice', id: 'day-040-choice-001', prompt: 'Which sentence uses kind words?', options: ['Sorry. Excuse me.', 'The road is straight.', 'I have milk.'], correctOption: 'Sorry. Excuse me.' },
        { type: 'fill_blank', id: 'day-040-fill-001', prompt: 'I am ___.', acceptedAnswers: ['sorry'] },
        { type: 'sentence_order', id: 'day-040-order-001', tokens: ['me', 'Excuse'], correctOrder: ['Excuse', 'me'], finalSentence: 'Excuse me.' },
        { type: 'choice', id: 'day-040-choice-002', prompt: 'Which sentence tells a problem?', options: ['This is wrong.', 'I eat rice.', 'The cup is empty.'], correctOption: 'This is wrong.' },
        { type: 'fill_blank', id: 'day-040-fill-002', prompt: 'Please ___ me.', acceptedAnswers: ['help'] },
        { type: 'translation', id: 'day-040-translation-001', chinesePrompt: '我说对不起和打扰一下，并请求帮助。', coreMeaningHint: 'Use kind words for a problem.', suggestedPatternIds: ['sorry-excuse-me', 'please-help-me'], referenceAnswers: ['Sorry. Excuse me. Please help me.'] },
      ],
      outputTask: {
        id: 'day-040-output',
        topic: 'Kind Problem',
        prompts: ['What kind words do you use?', 'What help do you need?'],
        template: ['Sorry.', 'Excuse me.', 'I have a problem.', 'Please help me.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about a small problem outside and kind words.',
      },
    },
    {
      id: 'day-041',
      weekId: 'week-06',
      dayNumber: 41,
      title: 'Kind After Help',
      goal: 'Use kind words after getting help.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['kind', 'help', 'understand', 'repeat', 'answer', 'friend', 'question'],
      patternIds: ['i-am-kind', 'i-understand', 'please-repeat'],
      exercises: [
        { type: 'choice', id: 'day-041-choice-001', prompt: 'Which sentence uses kind words?', options: ['I am kind.', 'I turn right.', 'The shop is far.'], correctOption: 'I am kind.' },
        { type: 'fill_blank', id: 'day-041-fill-001', prompt: 'I am ___.', acceptedAnswers: ['kind'] },
        { type: 'sentence_order', id: 'day-041-order-001', tokens: ['kind', 'am', 'I'], correctOrder: ['I', 'am', 'kind'], finalSentence: 'I am kind.' },
        { type: 'choice', id: 'day-041-choice-002', prompt: 'Which sentence says the answer is clear?', options: ['I understand.', 'I am late.', 'I need food.'], correctOption: 'I understand.' },
        { type: 'fill_blank', id: 'day-041-fill-002', prompt: 'Please ___.', acceptedAnswers: ['repeat'] },
        { type: 'translation', id: 'day-041-translation-001', chinesePrompt: '我请对方重复，明白了，并保持友善。', coreMeaningHint: 'Close a help talk.', suggestedPatternIds: ['please-repeat', 'i-understand', 'i-am-kind'], referenceAnswers: ['Please repeat. I understand. I am kind.'] },
      ],
      outputTask: {
        id: 'day-041-output',
        topic: 'Kind Help',
        prompts: ['What do you ask?', 'How are you kind?'],
        template: ['Please repeat.', 'I understand.', 'I am kind.', 'You help me.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about getting help, understanding, and being kind.',
      },
    },
    {
      id: 'day-042',
      weekId: 'week-06',
      dayNumber: 42,
      title: 'Week 6 Story',
      goal: 'Answer a problem outside from the first problem to the kind close.',
      estimatedMinutes: 35,
      review: { wordCount: 10, patternCount: 5 },
      wordIds: ['late', 'clear', 'wrong', 'another', 'understand', 'repeat', 'sorry', 'excuse', 'safe', 'help', 'way', 'outside'],
      patternIds: ['the-way-is-not-clear', 'this-is-wrong', 'i-need-another', 'please-repeat', 'i-am-kind'],
      exercises: [
        { type: 'choice', id: 'day-042-choice-001', prompt: 'Which sentence is good for a problem outside?', options: ['The way is not clear. This way is wrong.', 'I drink milk at home.', 'The pen is on the desk.'], correctOption: 'The way is not clear. This way is wrong.' },
        { type: 'fill_blank', id: 'day-042-fill-001', prompt: 'I need another ___.', acceptedAnswers: ['way', 'seat'] },
        { type: 'replacement', id: 'day-042-replace-001', patternId: 'i-need-another', slotValues: { thing: 'way' }, referenceAnswer: 'I need another way.' },
        { type: 'sentence_order', id: 'day-042-order-001', tokens: ['repeat', 'Please'], correctOrder: ['Please', 'repeat'], finalSentence: 'Please repeat.' },
        { type: 'fill_blank', id: 'day-042-fill-002', prompt: 'I am ___.', acceptedAnswers: ['kind'] },
        { type: 'translation', id: 'day-042-translation-001', chinesePrompt: '路线不清楚，我需要另一条路；请再说一遍。', coreMeaningHint: 'Answer an outside problem with kind words.', suggestedPatternIds: ['the-way-is-not-clear', 'i-need-another', 'please-repeat', 'i-am-kind'], referenceAnswers: ['The way is not clear. I need another way. Please repeat. I am kind.'] },
      ],
      outputTask: {
        id: 'day-042-output',
        topic: 'Problem Outside Story',
        prompts: ['What is the problem?', 'What do you ask?', 'How do you close with kind words?'],
        template: ['The way is not clear.', 'This way is wrong.', 'I need another way.', 'Please repeat.', 'I understand.', 'I am kind.'],
        requiredSentenceCount: 6,
        storyMode: 'recap',
        storyPrompt: 'Make a full story about a problem outside, asking for another way, understanding, and being kind.',
      },
      weeklyCheckRubric: {
        scale: { min: 0, max: 2 },
        pass: { minimumTotalScore: 7, minimumMeaningScore: 1, minimumSentenceCount: 6 },
        criteria: [
          { id: 'meaning', label: 'Meaning', scores: ['hard to understand', 'partly clear', 'clear'] },
          { id: 'problem-handling', label: 'Problem answer', scores: ['problem is not clear', 'some problem and help language', 'clear problem and help order'] },
          { id: 'target-patterns', label: 'Form use', scores: ['not used', 'used with help', 'used with no help'] },
          { id: 'word-use', label: 'Word use', scores: ['little problem words', 'some problem words', 'much problem words'] },
          { id: 'independence', label: 'My words', scores: ['same as example', 'some change from example', 'all my words'] },
        ],
      },
    },
  ],
};
