import type { Day, Pattern, Week, Word } from '../domain/types';

type Entry = [string, string, string, string, string];
const entries: Entry[] = [
  ['black','quality','a dark color','黑色的','The bag is black.'],['blue','quality','the color of a clear sky','蓝色的','The cup is blue.'],['brown','quality','a dark earth color','棕色的','The chair is brown.'],['bright','quality','full of light','明亮的','The room is bright.'],['color','general_thing','a red or blue quality','颜色','The color is clear.'],['dark','quality','with little light','暗的','The room is dark.'],['green','quality','the color of grass','绿色的','The tree is green.'],['gray','quality','a color between black and white','灰色的','The room is gray.'],['loud','quality','with much sound','响亮的','The sound is loud.'],['red','quality','the color of fire','红色的','The apple is red.'],['shade','picturable_thing','a dark place under a tree','阴影','The tree has shade.'],['white','quality','the color of snow','白色的','The shirt is white.'],['yellow','quality','the color of the sun','黄色的','The flower is yellow.'],['eye','picturable_thing','a part that lets a person see','眼睛','My eye is open.'],['hair','picturable_thing','what is on the head','头发','My hair is short.'],['smile','action','a happy look on the face','微笑','I smile.'],['soft','quality','not hard to touch','柔软的','The cloth is soft.'],
  ['dress','picturable_thing','clothes for a person','连衣裙','The dress is red.'],['collar','picturable_thing','the part by the neck','衣领','The collar is white.'],['pocket','picturable_thing','a small place in clothes','口袋','The key is in the pocket.'],['skirt','picturable_thing','clothes for the body','裙子','The skirt is blue.'],['stocking','picturable_thing','clothes for a leg','长袜','The stocking is long.'],['trousers','picturable_thing','clothes for the legs','裤子','My trousers are clean.'],['finger','picturable_thing','a small part of the hand','手指','My finger is clean.'],['knee','picturable_thing','the middle part of the leg','膝盖','My knee is safe.'],['leg','picturable_thing','a body part for walking','腿','My leg is safe.'],['lip','picturable_thing','the soft part by the mouth','嘴唇','My lip is dry.'],['neck','picturable_thing','the part below the head','脖子','My neck is warm.'],['nose','picturable_thing','the part for smell','鼻子','My nose is cold.'],['tooth','picturable_thing','a hard part in the mouth','牙齿','My tooth is white.'],['thumb','picturable_thing','the short finger at the side of the hand','拇指','My thumb is strong.'],['toe','picturable_thing','a small part at the end of the foot','脚趾','My toe is small.'],['watch','picturable_thing','a thing for time','手表','I look at my watch.'],['ring','picturable_thing','a small circle on a finger','戒指','The ring is gold.'],
  ['cook','action','to make food with heat','烹饪','I cook food.'],['cheese','picturable_thing','food from milk','奶酪','The cheese is good.'],['butter','picturable_thing','soft yellow food','黄油','The butter is soft.'],['egg','picturable_thing','food from a bird','鸡蛋','The egg is white.'],['meat','picturable_thing','food from an animal','肉','The meat is warm.'],['oven','picturable_thing','a thing for cooking with heat','烤箱','The food is in the oven.'],['pot','picturable_thing','a deep thing for cooking','锅','The pot is on the table.'],['potato','picturable_thing','a brown food from the earth','土豆','The potato is in the pot.'],['salt','picturable_thing','a white thing for food','盐','I put salt on food.'],['sugar','picturable_thing','a white food for a sweet taste','糖','The sugar is in the cup.'],['soup','picturable_thing','warm liquid food','汤','The soup is warm.'],['oil','picturable_thing','a liquid used for cooking','油','The oil is in the pot.'],['paste','picturable_thing','a soft food or material','糊；酱','The paste is soft.'],['tin','picturable_thing','a metal food box','罐头盒','The tin is on the table.'],['tray','picturable_thing','a flat thing for carrying food','托盘','The tray has food.'],['cork','picturable_thing','a thing that closes a bottle','软木塞','The cork is in the bottle.'],['orange','picturable_thing','a round fruit and color','橙子；橙色','I eat an orange.'],
];
const phonetics: Record<string,string> = Object.fromEntries(entries.map(([id])=>[id,`/${id}/`]));
const makeWords=(items:Entry[],weekIntroduced:number,tags:string[])=>items.map(([id,category,definition,chinese,example])=>({id,text:id,category:category as Word['category'],definition,chinese,example,phonetic:phonetics[id],weekIntroduced,tags}));
export const week17Words=makeWords(entries.slice(0,17),17,['look','color']);
export const week18Words=makeWords(entries.slice(17,34),18,['clothes','body']);
export const week19Words=makeWords(entries.slice(34),19,['food','cooking']);
export const week17to19Patterns:Pattern[]=[
 {id:'look-quality',title:'The ___ is ___.',use:'Describe a thing.',structure:'The {thing} is {quality}.',examples:['The cup is blue.','The room is bright.'],slots:['thing','quality']},
 {id:'body-quality',title:'My ___ is ___.',use:'Describe clothes or a body part.',structure:'My {thing} is {quality}.',examples:['My hair is short.','My shirt is white.'],slots:['thing','quality']},
 {id:'cook-food',title:'I ___ ___.',use:'Say what you do with food.',structure:'I {action} {thing}.',examples:['I cook food.','I eat an orange.'],slots:['action','thing']},
 {id:'food-quality',title:'The ___ is ___.',use:'Describe food.',structure:'The {thing} is {quality}.',examples:['The soup is warm.','The butter is soft.'],slots:['thing','quality']},
];
function day(n:number,weekId:string,title:string,words:string[],sentence:string,answer:string,goal:string,patterns:string[]):Day { const first=words[0],second=words[1]??first; return {id:`day-${String(n).padStart(3,'0')}`,weekId,dayNumber:n,title,goal,estimatedMinutes:30,review:{wordCount:words.length,patternCount:2},wordIds:words,patternIds:patterns,exercises:[{type:'choice',id:`day-${n}-choice`,prompt:`Which sentence uses ${first}?`,options:[sentence,'The weather is cold.','I will go tomorrow.'],correctOption:sentence},{type:'fill_blank',id:`day-${n}-fill`,prompt:sentence.replace(first,'___'),acceptedAnswers:[answer]},{type:'sentence_order',id:`day-${n}-order`,tokens:sentence.replace('.','').split(' ').reverse(),correctOrder:sentence.replace('.','').split(' '),finalSentence:sentence},{type:'translation',id:`day-${n}-translation`,chinesePrompt:`请用 ${first} 描述一个简单场景。`,coreMeaningHint:goal,suggestedPatternIds:[patterns[0]],referenceAnswers:[sentence]},{type:'choice',id:`day-${n}-choice-2`,prompt:'Which sentence is clear?',options:[`The ${first} is good.`,'The weather is cold.','I will go tomorrow.'],correctOption:`The ${first} is good.`}],outputTask:{id:`day-${n}-output`,topic:title,prompts:[`What can you say about ${title.toLowerCase()}?`,'What is one thing like?'],template:[sentence,`The ${first} is good.`,`There is a ${second}.`,`I see the ${first}.`,`The ${second} is good.`,`I use the ${first}.`],requiredSentenceCount:4,storyMode:n%7===0?'recap':'sentence',storyPrompt:`Make a short story about ${title.toLowerCase()}`},...(n%7===0?{weeklyCheckRubric:{scale:{min:0,max:2},pass:{minimumTotalScore:7,minimumMeaningScore:1,minimumSentenceCount:6},criteria:[{id:'meaning',label:'Meaning',scores:['hard to understand','partly clear','clear']},{id:'story-order',label:'Story order',scores:['not in order','some order','clear order']},{id:'target-patterns',label:'Form use',scores:['not used','used with help','used with no help']},{id:'word-use',label:'Word use',scores:['not enough words','some words','enough words']},{id:'independence',label:'My words',scores:['same as example','some change','all my words']}]}}:{})}; }
export const week17:Week={id:'week-17',number:17,title:'Light, Color, and Look',goal:'Describe color, light, and simple qualities.',days:[day(113,'week-17','Dark and Light',['black','dark','loud','bright','color','room','shade'],'The room is bright.','bright','Describe light and dark places.',['look-quality','food-quality']),day(114,'week-17','Blue and Green',['blue','green','color','tree','good','bright'],'The tree is green.','green','Describe colors outside.',['look-quality','food-quality']),day(115,'week-17','Red and Yellow',['red','yellow','apple','apple','flower','color'],'The apple is red.','red','Describe food and flowers by color.',['look-quality','food-quality']),day(116,'week-17','Gray and Brown',['gray','brown','room','chair','table','dark'],'The room is gray.','gray','Describe things at home by color.',['look-quality','food-quality']),day(117,'week-17','Eye and Hair',['eye','hair','face','see','short','clean'],'My hair is short.','hair','Describe what you see.',['body-quality','look-quality']),day(118,'week-17','Happy Look',['smile','happy','face','good','soft','bright'],'I smile.','smile','Describe a happy look.',['body-quality','look-quality']),day(119,'week-17','Week 17 Look Story',['black','blue','green','red','loud','smile'],'The room is bright.','bright','Tell a story about color and look.',['look-quality','body-quality'])]};
export const week18:Week={id:'week-18',number:18,title:'Clothes and Personal Things',goal:'Talk about clothes, body parts, and personal things.',days:[day(120,'week-18','A Dress and Collar',['dress','collar','red','white','clothes','clean'],'The dress is red.','dress','Describe clothes.',['body-quality','look-quality']),day(121,'week-18','Pockets and Skirts',['pocket','skirt','key','blue','small','clothes'],'The skirt is blue.','skirt','Describe clothes and a pocket.',['body-quality','look-quality']),day(122,'week-18','Leg Clothes',['stocking','trousers','leg','long','clean','clothes'],'My trousers are clean.','trousers','Describe clothes for the legs.',['body-quality','look-quality']),day(123,'week-18','Hand and Finger',['finger','thumb','hand','safe','clean','small'],'My finger is clean.','finger','Describe parts of a hand.',['body-quality','look-quality']),day(124,'week-18','Knee and Leg',['knee','leg','foot','safe','pain','care'],'My leg is safe.','leg','Describe a leg and care.',['body-quality','look-quality']),day(125,'week-18','Face and Neck',['lip','neck','nose','face','cold','warm'],'My nose is cold.','nose','Describe parts of the face.',['body-quality','look-quality']),day(126,'week-18','Week 18 Personal Story',['dress','pocket','watch','ring','finger','trousers','tooth','toe'],'I look at my watch.','watch','Tell a story about personal things.',['body-quality','look-quality'])]};
export const week19:Week={id:'week-19',number:19,title:'Food and Cooking',goal:'Describe food, taste, cooking, and food things.',days:[day(127,'week-19','Cooking',['cook','food','heat','warm','good','water'],'I cook food.','cook','Say what you do with food.',['cook-food','food-quality']),day(128,'week-19','Milk Food',['cheese','butter','milk','soft','white','food'],'The butter is soft.','butter','Describe food from milk.',['food-quality','look-quality']),day(129,'week-19','Egg and Meat',['egg','meat','food','warm','white','eat'],'The egg is white.','egg','Describe simple food.',['food-quality','cook-food']),day(130,'week-19','The Oven and Pot',['oven','pot','heat','food','warm','water'],'The food is in the oven.','oven','Describe cooking things.',['look-quality','food-quality']),day(131,'week-19','Potato and Salt',['potato','salt','pot','food','taste','good'],'The potato is in the pot.','potato','Describe food in a pot.',['look-quality','food-quality']),day(132,'week-19','Soup and Sugar',['soup','sugar','cup','warm','good','food'],'The soup is warm.','soup','Describe taste and heat.',['food-quality','cook-food']),day(133,'week-19','Week 19 Food Story',['oil','paste','tin','tray','cork','orange'],'I eat an orange.','orange','Tell a story about food and cooking.',['cook-food','food-quality'])]};
export const week17to19=[week17,week18,week19];
