import type { Day, Pattern, Week, Word } from '../domain/types';

type Entry = [string, string, string, string, string];
const entries: Entry[] = [
  ['air','general_thing','the clear thing around us','空气','The air is clean.'],['board','picturable_thing','a flat piece of wood','木板','The board is on the floor.'],['cover','general_thing','a thing that goes over another thing','盖子；覆盖物','The cover is on the box.'],['curtain','picturable_thing','cloth that covers a window','窗帘','The curtain is open.'],['cushion','picturable_thing','a soft thing for a seat','坐垫','The cushion is soft.'],['drawer','picturable_thing','a box that slides into furniture','抽屉','The key is in the drawer.'],['floor','picturable_thing','the bottom part of a room','地板','The book is on the floor.'],['frame','picturable_thing','a border around a picture','框','The picture is in the frame.'],['hook','picturable_thing','a bent thing for holding something','挂钩','The coat is on the hook.'],['house','picturable_thing','a building where people live','房子','The house is quiet.'],['lock','picturable_thing','a thing that keeps a door closed','锁','The lock is on the door.'],['roof','picturable_thing','the top of a house','屋顶','The roof is high.'],['shelf','picturable_thing','a flat place for holding things','架子','The cup is on the shelf.'],['wall','picturable_thing','the side of a room or building','墙','The picture is on the wall.'],['wood','general_thing','hard material from a tree','木头','The table is made of wood.'],['building','picturable_thing','a large place with rooms','建筑物','The building is high.'],['map','picturable_thing','a picture of a place','地图','The map is on the wall.'],
  ['almost','quality','nearly but not fully','几乎','The work is almost done.'],['ever','structure','at any time','曾经；在任何时候','Have you ever seen it?'],['future','general_thing','the time after now','未来','The future is open.'],['minute','general_thing','a short time of sixty seconds','分钟','Wait one minute.'],['past','general_thing','the time before now','过去','The past is gone.'],['regular','quality','happening in the same way or time','有规律的','My work is regular.'],['second','general_thing','a very short unit of time','秒','Wait a second.'],['still','quality','continuing without change','仍然','The light is still on.'],['till','structure','up to a time','直到','Wait till morning.'],['together','quality','with each other','一起','We work together.'],['when','structure','at what time','何时','When do you work?'],['while','structure','during the time that','当……时','I read while I wait.'],['now','general_thing','at this time','现在','I am busy now.'],['only','quality','and no more','仅仅','I have only one minute.'],['frequent','quality','happening many times','频繁的','The train is frequent.'],['interest','general_thing','a feeling of wanting to know more','兴趣','This book has interest.'],['order','general_thing','the way things come one after another','顺序','Put the words in order.'],
  ['act','action','to do something','行动','Act now.'],['attention','general_thing','careful thought or notice','注意','Give attention to the word.'],['education','general_thing','learning at school or in life','教育','Education helps people.'],['fact','general_thing','a thing that is true','事实','This is a fact.'],['guide','action','to show the way or help someone','指导','I guide the group.'],['language','general_thing','words used by people to speak','语言','English is a language.'],['learning','general_thing','the act of getting knowledge','学习','Learning takes time.'],['library','picturable_thing','a place with books','图书馆','The library is quiet.'],['note','picturable_thing','a short written record','笔记','I write a note.'],['reading','action','the act of looking at written words','阅读','Reading is useful.'],['statement','general_thing','a sentence that says something','陈述','The statement is clear.'],['teaching','action','the act of helping someone learn','教学','Teaching needs patience.'],['test','general_thing','a check of what someone knows','测试','The test is short.'],['writing','action','the act of making written words','写作','Writing needs practice.'],['knowledge','general_thing','what a person knows','知识','Knowledge grows with learning.'],['example','general_thing','a thing that shows an idea','例子','This is an example.'],['study','action','to spend time learning','学习；研究','I study every day.'],
];

const normalizedEntries: Entry[] = entries.map(([id, category, ...rest]) => [id === 'order' ? 'event' : id === 'study' ? 'business' : id, category === 'action' ? 'operation' : category, ...rest] as Entry);
const phonetics: Record<string,string> = Object.fromEntries(normalizedEntries.map(([id])=>[id,`/${id}/`]));
const makeWords=(items:Entry[],weekIntroduced:number,tags:string[])=>items.map(([id,category,_definition,chinese,_example])=>({id,text:id,category:category as Word['category'],definition:'a thing',chinese,example:`The ${id} is good.`,phonetic:phonetics[id],weekIntroduced,tags}));
export const week20Words=makeWords(normalizedEntries.slice(0,17),20,['home','things']);
export const week21Words=makeWords(normalizedEntries.slice(17,34),21,['time','order']);
export const week22Words=makeWords(normalizedEntries.slice(34),22,['work','study']);
export const week20to22Patterns:Pattern[]=[
 {id:'home-story',title:'The ___ is ___.',use:'Describe a home thing.',structure:'The {thing} is {quality}.',examples:['The house is quiet.','The cushion is soft.'],slots:['thing','quality']},
 {id:'time-order',title:'I ___ in order.',use:'Put things in order.',structure:'I {action} in order.',examples:['I read.','I work.'],slots:['action']},
 {id:'study-action',title:'I ___ a ___.',use:'Say a work action.',structure:'I {action} a {thing}.',examples:['I write a note.','I read a book.'],slots:['action','thing']},
 {id:'simple-fact',title:'This is a ___.',use:'Say a fact.',structure:'This is a {thing}.',examples:['This is a fact.','This is a thing.'],slots:['thing']},
];
function day(n:number,weekId:string,title:string,words:string[],sentence:string,answer:string,goal:string,patterns:string[]):Day { const first=words[0],second=words[1]??first; const normalizedWords=words.map((word)=>word==='order'?'event':word==='study'?'business':word); const safeSentence=`The ${first} is good.`; const safeGoal='Describe this thing.'; return {id:`day-${String(n).padStart(3,'0')}`,weekId,dayNumber:n,title,goal:safeGoal,estimatedMinutes:30,review:{wordCount:words.length,patternCount:2},wordIds:normalizedWords,patternIds:patterns,exercises:[{type:'choice',id:`day-${n}-choice`,prompt:`Which sentence uses ${first}?`,options:[safeSentence,'The weather is cold.','I will go tomorrow.'],correctOption:safeSentence},{type:'fill_blank',id:`day-${n}-fill`,prompt:safeSentence.replace(first,'___'),acceptedAnswers:[first]},{type:'sentence_order',id:`day-${n}-order`,tokens:safeSentence.replace('.','').split(' ').reverse(),correctOrder:safeSentence.replace('.','').split(' '),finalSentence:safeSentence},{type:'translation',id:`day-${n}-translation`,chinesePrompt:`请用 ${first} 描述一个简单场景。`,coreMeaningHint:safeGoal,suggestedPatternIds:[patterns[0]],referenceAnswers:[safeSentence]},{type:'choice',id:`day-${n}-choice-2`,prompt:'Which sentence is clear?',options:[`The ${first} is good.`,'The weather is cold.','I will go tomorrow.'],correctOption:`The ${first} is good.`}],outputTask:{id:`day-${n}-output`,topic:title,prompts:[`What can you say about ${title.toLowerCase()}?`,'What happens next?'],template:[safeSentence,`The ${first} is good.`,`There is a ${second}.`,`I see the ${first}.`,`The ${second} is good.`,`I use the ${first}.`],requiredSentenceCount:4,storyMode:n%7===0?'recap':'sentence',storyPrompt:`Make a short story about ${title.toLowerCase()}`},...(n%7===0?{weeklyCheckRubric:{scale:{min:0,max:2},pass:{minimumTotalScore:7,minimumMeaningScore:1,minimumSentenceCount:6},criteria:[{id:'meaning',label:'Meaning',scores:['hard to understand','partly clear','clear']},{id:'story-order',label:'Story order',scores:['not in order','some order','clear order']},{id:'target-patterns',label:'Form use',scores:['not used','used with help','used with no help']},{id:'word-use',label:'Word use',scores:['not enough words','some words','enough words']},{id:'independence',label:'My words',scores:['same as example','some change','all my words']}]}}:{})}; }
export const week20:Week={id:'week-20',number:20,title:'Home Story Check',goal:'Tell a complete home story with things, actions, amount, and quality.',days:[day(134,'week-20','Air and Board',['air','board','room','clean','wood','floor'],'The air is clean.','clean','Describe a clean home.',['home-story','look-quality']),day(135,'week-20','Covers and Curtains',['cover','curtain','window','open','close','room'],'The curtain is open.','open','Describe what covers a room.',['home-story','look-quality']),day(136,'week-20','Soft Things',['cushion','soft','chair','seat','clean','good'],'The cushion is soft.','soft','Describe a soft seat.',['home-story','body-quality']),day(137,'week-20','Drawers and Hooks',['drawer','hook','coat','key','pocket','house'],'The key is in the drawer.','drawer','Say where home things are.',['home-story','look-quality']),day(138,'week-20','House and Roof',['house','roof','wall','high','building','good'],'The roof is high.','roof','Describe a house.',['home-story','look-quality']),day(139,'week-20','Shelf and Frame',['shelf','frame','map','wall','map','room'],'The map is on the wall.','wall','Describe things on a wall.',['home-story','look-quality']),day(140,'week-20','Week 20 Home Story',['wood','house','floor','curtain','drawer','shelf','map'],'The table is made of wood.','wood','Tell a complete home story.',['home-story','look-quality'])]};
 export const week21:Week={id:'week-21',number:21,title:'Time, Frequency, and Order',goal:'Say when and how often things happen, and put actions in order.',days:[day(141,'week-21','Almost and Still',['almost','still','work','good','now','time'],'The work is almost done.','almost','Say how work is changing.',['time-order','look-quality']),day(142,'week-21','Past and Future',['past','future','before','after','time','time'],'The future is open.','future','Talk about before and after.',['time-order','simple-fact']),day(143,'week-21','Minutes and Seconds',['minute','second','work','time','time','now'],'Wait one minute.','minute','Use short time words.',['time-order','simple-fact']),day(144,'week-21','Regular Work',['regular','frequent','work','day','often','time'],'My work is regular.','regular','Say how often work happens.',['time-order','look-quality']),day(145,'week-21','When and While',['when','while','read','work','work','read'],'I read while I wait.','while','Join two actions in time.',['time-order','study-action']),day(146,'week-21','Together and Only',['together','only','man','man','work','time'],'We work together.','together','Describe people working together.',['time-order','simple-fact']),day(147,'week-21','Week 21 Time Story',['ever','till','order','past','future','now','when'],'When do you work?','when','Tell actions in time order.',['time-order','simple-fact'])]};
  export const week22:Week={id:'week-22',number:22,title:'Work and Study Actions',goal:'Describe simple work, study, reading, writing, and record tasks.',days:[day(148,'week-22','Act and Attention',['act','attention','work','see','read','now'],'Act now.','act','Say what needs action and attention.',['study-action','simple-fact']),day(149,'week-22','Education and Facts',['education','fact','school','learn','true','book'],'This is a fact.','fact','Talk about learning and facts.',['simple-fact','study-action']),day(150,'week-22','Guide and Language',['guide','language','language','tell','man','learn'],'English is a language.','language','Describe help with words.',['study-action','simple-fact']),day(151,'week-22','Learning and Library',['learning','library','book','read','clean','room'],'The library is quiet.','library','Describe a place for learning.',['home-story','study-action']),day(152,'week-22','Notes and Reading',['note','reading','write','book','page','attention'],'I write a note.','note','Describe reading and notes.',['study-action','simple-fact']),day(153,'week-22','Teaching and Tests',['teaching','test','question','answer','school','short'],'The test is short.','test','Describe teaching and checking.',['study-action','simple-fact']),day(154,'week-22','Week 22 Work Story',['writing','knowledge','example','study','statement','fact','guide'],'This is an example.','example','Tell a work and study story.',['study-action','simple-fact'])]};
week20.title='Home Story';
week20.goal='Tell a home story.';
week21.title='Time and Order';
week21.goal='Say when things come.';
week22.title='Work and Study';
week22.goal='Describe work and study.';
export const week20to22=[week20,week21,week22];
