import type { Pattern, Week, Word } from '../domain/types';

export const week4Words: Word[] = [
  { id: 'food', text: 'food', category: 'general_thing', definition: 'things people eat', chinese: '食物', example: 'I need food.', weekIntroduced: 4, tags: ['food'] },
  { id: 'drink', text: 'drink', category: 'operation', definition: 'to take liquid into the body', chinese: '喝；饮料', example: 'I drink water.', weekIntroduced: 4, tags: ['food'] },
  { id: 'bread', text: 'bread', category: 'picturable_thing', definition: 'food made from grain', chinese: '面包', example: 'I eat bread.', weekIntroduced: 4, tags: ['food'] },
  { id: 'milk', text: 'milk', category: 'general_thing', definition: 'white drink from cows or plants', chinese: '牛奶', example: 'I drink milk.', weekIntroduced: 4, tags: ['food'] },
  { id: 'rice', text: 'rice', category: 'general_thing', definition: 'small white or brown food grains', chinese: '米饭', example: 'I eat rice.', weekIntroduced: 4, tags: ['food'] },
  { id: 'fruit', text: 'fruit', category: 'general_thing', definition: 'sweet food from trees or plants', chinese: '水果', example: 'I have fruit.', weekIntroduced: 4, tags: ['food'] },
  { id: 'tea', text: 'tea', category: 'general_thing', definition: 'a warm drink made with leaves', chinese: '茶', example: 'I drink tea.', weekIntroduced: 4, tags: ['food'] },
  { id: 'eat', text: 'eat', category: 'operation', definition: 'to put food in the mouth and take it into the body', chinese: '吃', example: 'I eat food.', weekIntroduced: 4, tags: ['food'] },
  { id: 'need', text: 'need', category: 'operation', definition: 'to require something', chinese: '需要', example: 'I need water.', weekIntroduced: 4, tags: ['need'] },
  { id: 'some', text: 'some', category: 'structure', definition: 'an amount of something', chinese: '一些', example: 'I want some water.', weekIntroduced: 4, tags: ['amount'] },
  { id: 'help', text: 'help', category: 'operation', definition: 'to make something easier for another person', chinese: '帮助', example: 'Please help me.', weekIntroduced: 4, tags: ['request'] },
  { id: 'problem', text: 'problem', category: 'general_thing', definition: 'something difficult that needs an answer', chinese: '问题；困难', example: 'I have a problem.', weekIntroduced: 4, tags: ['request'] },
  { id: 'please', text: 'please', category: 'structure', definition: 'a polite word used when asking', chinese: '请', example: 'Please help me.', weekIntroduced: 4, tags: ['request'] },
  { id: 'ready', text: 'ready', category: 'quality', definition: 'prepared for use or action', chinese: '准备好的', example: 'I am ready.', weekIntroduced: 4, tags: ['quality'] },
  { id: 'shop', text: 'shop', category: 'general_thing', definition: 'a place where people buy things', chinese: '商店', example: 'I go to the shop.', weekIntroduced: 4, tags: ['shopping'] },
  { id: 'buy', text: 'buy', category: 'operation', definition: 'to get something by paying money', chinese: '买', example: 'I buy bread.', weekIntroduced: 4, tags: ['shopping'] },
  { id: 'sell', text: 'sell', category: 'operation', definition: 'to give something for money', chinese: '卖', example: 'The shop sells food.', weekIntroduced: 4, tags: ['shopping'] },
  { id: 'store', text: 'store', category: 'general_thing', definition: 'a shop', chinese: '商店', example: 'I go to the store.', weekIntroduced: 4, tags: ['shopping'] },
  { id: 'price', text: 'price', category: 'general_thing', definition: 'the money needed to buy something', chinese: '价格', example: 'The price is good.', weekIntroduced: 4, tags: ['money'] },
  { id: 'cheap', text: 'cheap', category: 'quality', definition: 'costing little money', chinese: '便宜的', example: 'The bread is cheap.', weekIntroduced: 4, tags: ['money'] },
  { id: 'dear', text: 'dear', category: 'quality', definition: 'costing much money', chinese: '昂贵的', example: 'The phone is dear.', weekIntroduced: 4, tags: ['money'] },
  { id: 'pay', text: 'pay', category: 'operation', definition: 'to give money for something', chinese: '支付', example: 'I pay for food.', weekIntroduced: 4, tags: ['money'] },
  { id: 'cost', text: 'cost', category: 'operation', definition: 'to have a price', chinese: '花费', example: 'It costs little.', weekIntroduced: 4, tags: ['money'] },
  { id: 'change', text: 'change', category: 'general_thing', definition: 'money returned after paying', chinese: '零钱；改变', example: 'I get change.', weekIntroduced: 4, tags: ['money'] },
  { id: 'little', text: 'little', category: 'quality', definition: 'small in amount', chinese: '少的；小的', example: 'It costs little.', weekIntroduced: 4, tags: ['amount'] },
  { id: 'much', text: 'much', category: 'quality', definition: 'great in amount', chinese: '多的', example: 'It costs much.', weekIntroduced: 4, tags: ['amount'] },
  { id: 'ask', text: 'ask', category: 'operation', definition: 'to say a question or request', chinese: '问；请求', example: 'I ask for help.', weekIntroduced: 4, tags: ['request'] },
  { id: 'answer', text: 'answer', category: 'general_thing', definition: 'what is said after a question', chinese: '回答', example: 'I have an answer.', weekIntroduced: 4, tags: ['request'] },
  { id: 'find', text: 'find', category: 'operation', definition: 'to get or see something after looking', chinese: '找到', example: 'I find my bag.', weekIntroduced: 4, tags: ['request'] },
  { id: 'show', text: 'show', category: 'operation', definition: 'to let someone see something', chinese: '展示', example: 'Please show me the book.', weekIntroduced: 4, tags: ['request'] },
  { id: 'bring', text: 'bring', category: 'operation', definition: 'to take something to a person or place', chinese: '带来', example: 'Please bring water.', weekIntroduced: 4, tags: ['request'] },
  { id: 'tell', text: 'tell', category: 'operation', definition: 'to give information with words', chinese: '告诉', example: 'Please tell me.', weekIntroduced: 4, tags: ['request'] },
  { id: 'more', text: 'more', category: 'quality', definition: 'a greater amount', chinese: '更多的', example: 'I need more water.', weekIntroduced: 4, tags: ['amount'] },
  { id: 'enough', text: 'enough', category: 'quality', definition: 'as much as needed', chinese: '足够的', example: 'I have enough food.', weekIntroduced: 4, tags: ['amount'] },
  { id: 'less', text: 'less', category: 'quality', definition: 'smaller in amount', chinese: '更少的', example: 'I need less food.', weekIntroduced: 4, tags: ['amount'] },
  { id: 'full', text: 'full', category: 'quality', definition: 'having no empty space', chinese: '满的', example: 'The cup is full.', weekIntroduced: 4, tags: ['amount'] },
  { id: 'empty', text: 'empty', category: 'quality', definition: 'with nothing inside', chinese: '空的', example: 'The cup is empty.', weekIntroduced: 4, tags: ['amount'] },
  { id: 'taste', text: 'taste', category: 'operation', definition: 'to sense food or drink in the mouth', chinese: '品尝；味道', example: 'The food tastes good.', weekIntroduced: 4, tags: ['food'] },
  { id: 'bad', text: 'bad', category: 'quality', definition: 'not good', chinese: '坏的；不好的', example: 'The food is bad.', weekIntroduced: 4, tags: ['quality'] },
];

export const week4Patterns: Pattern[] = [
  { id: 'i-eat', title: 'I eat ___.', use: 'Say food you eat.', structure: 'I eat {food}.', examples: ['I eat bread.', 'I eat rice.'], slots: ['food'] },
  { id: 'i-drink', title: 'I drink ___.', use: 'Say what you drink.', structure: 'I drink {drink}.', examples: ['I drink water.', 'I drink tea.'], slots: ['drink'] },
  { id: 'i-want-some', title: 'I want some ___.', use: 'Ask for or express wanting an amount.', structure: 'I want some {thing}.', examples: ['I want some water.', 'I want some bread.'], slots: ['thing'] },
  { id: 'i-need', title: 'I need ___.', use: 'Say what is necessary.', structure: 'I need {thing}.', examples: ['I need food.', 'I need help.'], slots: ['thing'] },
  { id: 'i-have-enough', title: 'I have enough ___.', use: 'Say you have the right amount.', structure: 'I have enough {thing}.', examples: ['I have enough money.', 'I have enough food.'], slots: ['thing'] },
  { id: 'i-go-to-shop', title: 'I go to the shop.', use: 'Say going to buy things.', structure: 'I go to the shop.', examples: ['I go to the shop.'], slots: [] },
  { id: 'i-buy', title: 'I buy ___.', use: 'Say what you buy.', structure: 'I buy {thing}.', examples: ['I buy bread.', 'I buy milk.'], slots: ['thing'] },
  { id: 'i-get-from-shop', title: 'I get ___ from the shop.', use: 'Say what you get from a shop.', structure: 'I get {thing} from the shop.', examples: ['I get bread from the shop.', 'I get milk from the shop.'], slots: ['thing'] },
  { id: 'i-pay-for', title: 'I pay for ___.', use: 'Say what you pay for.', structure: 'I pay for {thing}.', examples: ['I pay for food.', 'I pay for bread.'], slots: ['thing'] },
  { id: 'the-price-is', title: 'The price is ___.', use: 'Describe price simply.', structure: 'The price is {description}.', examples: ['The price is good.', 'The price is dear.'], slots: ['description'] },
  { id: 'it-costs', title: 'It costs ___.', use: 'Say cost amount simply.', structure: 'It costs {amount}.', examples: ['It costs little.', 'It costs much.'], slots: ['amount'] },
  { id: 'please-help-me', title: 'Please help me.', use: 'Ask for help politely.', structure: 'Please help me.', examples: ['Please help me.'], slots: [] },
  { id: 'can-you', title: 'Can you ___?', use: 'Ask another person to do something.', structure: 'Can you {action}?', examples: ['Can you help me?', 'Can you show me the book?'], slots: ['action'] },
  { id: 'i-ask-for', title: 'I ask for ___.', use: 'Say what help or thing you request.', structure: 'I ask for {thing}.', examples: ['I ask for help.', 'I ask for water.'], slots: ['thing'] },
  { id: 'i-need-more', title: 'I need more ___.', use: 'Say more is needed.', structure: 'I need more {thing}.', examples: ['I need more water.', 'I need more food.'], slots: ['thing'] },
  { id: 'the-thing-is-good', title: 'The ___ is good.', use: 'Say something is good.', structure: 'The {thing} is good.', examples: ['The food is good.', 'The tea is good.'], slots: ['thing'] },
];

export const week4: Week = {
  id: 'week-04',
  number: 4,
  title: 'Food, Shopping & Needs',
  goal: 'Say what food and drink you want or need, and ask for simple help when shopping.',
  days: [
    {
      id: 'day-022',
      weekId: 'week-04',
      dayNumber: 22,
      title: 'Food and Drink',
      goal: 'Say simple foods and drinks you eat or drink.',
      estimatedMinutes: 30,
      review: { wordCount: 7, patternCount: 3 },
      wordIds: ['food', 'drink', 'bread', 'milk', 'rice', 'fruit', 'tea', 'eat', 'water'],
      patternIds: ['i-eat', 'i-drink', 'i-have'],
      exercises: [
        { type: 'choice', id: 'day-022-choice-001', prompt: 'Which sentence is about food?', options: ['I eat bread.', 'The key is under the chair.', 'I go with my friend.'], correctOption: 'I eat bread.' },
        { type: 'fill_blank', id: 'day-022-fill-001', prompt: 'I drink ___.', acceptedAnswers: ['milk', 'tea', 'water'] },
        { type: 'replacement', id: 'day-022-replace-001', patternId: 'i-eat', slotValues: { food: 'bread' }, referenceAnswer: 'I eat bread.' },
        { type: 'replacement', id: 'day-022-replace-002', patternId: 'i-drink', slotValues: { drink: 'milk' }, referenceAnswer: 'I drink milk.' },
        { type: 'sentence_order', id: 'day-022-order-001', tokens: ['eat', 'rice', 'I'], correctOrder: ['I', 'eat', 'rice'], finalSentence: 'I eat rice.' },
        { type: 'translation', id: 'day-022-translation-001', chinesePrompt: '我吃面包。我喝牛奶。', coreMeaningHint: 'Say food and drink.', suggestedPatternIds: ['i-eat', 'i-drink'], referenceAnswers: ['I eat bread. I drink milk.'] },
      ],
      outputTask: {
        id: 'day-022-output',
        topic: 'Food and Drink',
        prompts: ['What food do you eat?', 'What do you drink?'],
        template: ['I eat ___.', 'I drink ___.', 'I have ___.', 'I need food.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-023',
      weekId: 'week-04',
      dayNumber: 23,
      title: 'Want and Need',
      goal: 'Say what you want, need, and have enough of.',
      estimatedMinutes: 30,
      review: { wordCount: 7, patternCount: 3 },
      wordIds: ['need', 'some', 'more', 'enough', 'help', 'problem', 'please', 'ready', 'want', 'water', 'food'],
      patternIds: ['i-want-some', 'i-need', 'i-have-enough'],
      exercises: [
        { type: 'choice', id: 'day-023-choice-001', prompt: 'Which sentence asks for an amount?', options: ['I want some water.', 'The cup is on the table.', 'First I open the book.'], correctOption: 'I want some water.' },
        { type: 'fill_blank', id: 'day-023-fill-001', prompt: 'I need ___.', acceptedAnswers: ['food', 'water', 'help'] },
        { type: 'replacement', id: 'day-023-replace-001', patternId: 'i-want-some', slotValues: { thing: 'water' }, referenceAnswer: 'I want some water.' },
        { type: 'replacement', id: 'day-023-replace-002', patternId: 'i-need', slotValues: { thing: 'help' }, referenceAnswer: 'I need help.' },
        { type: 'sentence_order', id: 'day-023-order-001', tokens: ['food', 'enough', 'have', 'I'], correctOrder: ['I', 'have', 'enough', 'food'], finalSentence: 'I have enough food.' },
        { type: 'translation', id: 'day-023-translation-001', chinesePrompt: '我想要一些水。我需要帮助。', coreMeaningHint: 'Say wants and needs.', suggestedPatternIds: ['i-want-some', 'i-need'], referenceAnswers: ['I want some water. I need help.'] },
      ],
      outputTask: {
        id: 'day-023-output',
        topic: 'What I Want and Need',
        prompts: ['What do you want?', 'What do you need?', 'Do you have enough?'],
        template: ['I want some ___.', 'I need ___.', 'Please help me.', 'I have enough ___.', 'I am ready.'],
        requiredSentenceCount: 5,
      },
    },
    {
      id: 'day-024',
      weekId: 'week-04',
      dayNumber: 24,
      title: 'Buying Simple Things',
      goal: 'Say what you get from a shop or store.',
      estimatedMinutes: 30,
      review: { wordCount: 7, patternCount: 3 },
      wordIds: ['shop', 'buy', 'sell', 'get', 'thing', 'store', 'bread', 'cup', 'money'],
      patternIds: ['i-go-to-shop', 'i-buy', 'i-get-from-shop'],
      exercises: [
        { type: 'choice', id: 'day-024-choice-001', prompt: 'Which sentence is about shopping?', options: ['I go to the shop.', 'I wash my face.', 'At night I sleep.'], correctOption: 'I go to the shop.' },
        { type: 'fill_blank', id: 'day-024-fill-001', prompt: 'I buy ___.', acceptedAnswers: ['bread', 'milk', 'a cup'] },
        { type: 'replacement', id: 'day-024-replace-001', patternId: 'i-buy', slotValues: { thing: 'bread' }, referenceAnswer: 'I buy bread.' },
        { type: 'replacement', id: 'day-024-replace-002', patternId: 'i-get-from-shop', slotValues: { thing: 'milk' }, referenceAnswer: 'I get milk from the shop.' },
        { type: 'sentence_order', id: 'day-024-order-001', tokens: ['buy', 'bread', 'I'], correctOrder: ['I', 'buy', 'bread'], finalSentence: 'I buy bread.' },
        { type: 'translation', id: 'day-024-translation-001', chinesePrompt: '我去商店。我买面包。', coreMeaningHint: 'Say simple shopping actions.', suggestedPatternIds: ['i-go-to-shop', 'i-buy'], referenceAnswers: ['I go to the shop. I buy bread.'] },
      ],
      outputTask: {
        id: 'day-024-output',
        topic: 'At the Shop',
        prompts: ['What shop or store do you go to?', 'What do you buy or get?'],
        template: ['I go to the shop.', 'I buy ___.', 'I get ___ from the shop.', 'The shop sells ___.', 'I have money.'],
        requiredSentenceCount: 5,
      },
    },
    {
      id: 'day-025',
      weekId: 'week-04',
      dayNumber: 25,
      title: 'Money and Price',
      goal: 'Describe price and paying with simple words.',
      estimatedMinutes: 30,
      review: { wordCount: 7, patternCount: 3 },
      wordIds: ['price', 'cheap', 'dear', 'pay', 'cost', 'change', 'little', 'much', 'money', 'buy'],
      patternIds: ['i-pay-for', 'the-price-is', 'it-costs'],
      exercises: [
        { type: 'choice', id: 'day-025-choice-001', prompt: 'Which sentence tells a price idea?', options: ['It costs little.', 'I sleep at night.', 'This is my friend.'], correctOption: 'It costs little.' },
        { type: 'fill_blank', id: 'day-025-fill-001', prompt: 'The price is ___.', acceptedAnswers: ['good', 'cheap', 'dear'] },
        { type: 'replacement', id: 'day-025-replace-001', patternId: 'i-pay-for', slotValues: { thing: 'food' }, referenceAnswer: 'I pay for food.' },
        { type: 'replacement', id: 'day-025-replace-002', patternId: 'it-costs', slotValues: { amount: 'little' }, referenceAnswer: 'It costs little.' },
        { type: 'sentence_order', id: 'day-025-order-001', tokens: ['is', 'good', 'price', 'The'], correctOrder: ['The', 'price', 'is', 'good'], finalSentence: 'The price is good.' },
        { type: 'translation', id: 'day-025-translation-001', chinesePrompt: '价格很好。我付食物的钱。', coreMeaningHint: 'Talk about price and paying.', suggestedPatternIds: ['the-price-is', 'i-pay-for'], referenceAnswers: ['The price is good. I pay for food.'] },
      ],
      outputTask: {
        id: 'day-025-output',
        topic: 'Price and Money',
        prompts: ['What do you pay for?', 'Is the price cheap or dear?'],
        template: ['I buy ___.', 'The price is ___.', 'It costs ___.', 'I pay for ___.', 'I get change.'],
        requiredSentenceCount: 5,
      },
    },
    {
      id: 'day-026',
      weekId: 'week-04',
      dayNumber: 26,
      title: 'Asking for Help',
      goal: 'Ask another person for simple help.',
      estimatedMinutes: 30,
      review: { wordCount: 7, patternCount: 3 },
      wordIds: ['ask', 'answer', 'help', 'please', 'find', 'show', 'bring', 'tell', 'problem'],
      patternIds: ['please-help-me', 'can-you', 'i-ask-for'],
      exercises: [
        { type: 'choice', id: 'day-026-choice-001', prompt: 'Which sentence asks for help?', options: ['Please help me.', 'The rice is on the table.', 'I often read.'], correctOption: 'Please help me.' },
        { type: 'fill_blank', id: 'day-026-fill-001', prompt: 'Can you ___ me the book?', acceptedAnswers: ['show', 'bring'] },
        { type: 'replacement', id: 'day-026-replace-001', patternId: 'can-you', slotValues: { action: 'show me the book' }, referenceAnswer: 'Can you show me the book?' },
        { type: 'replacement', id: 'day-026-replace-002', patternId: 'i-ask-for', slotValues: { thing: 'help' }, referenceAnswer: 'I ask for help.' },
        { type: 'sentence_order', id: 'day-026-order-001', tokens: ['help', 'Please', 'me'], correctOrder: ['Please', 'help', 'me'], finalSentence: 'Please help me.' },
        { type: 'translation', id: 'day-026-translation-001', chinesePrompt: '请帮助我。你能把书给我看吗？', coreMeaningHint: 'Ask for help politely.', suggestedPatternIds: ['please-help-me', 'can-you'], referenceAnswers: ['Please help me. Can you show me the book?'] },
      ],
      outputTask: {
        id: 'day-026-output',
        topic: 'Help Please',
        prompts: ['What help do you need?', 'What can you ask another person?'],
        template: ['Please help me.', 'Can you ___?', 'I ask for ___.', 'I have a problem.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-027',
      weekId: 'week-04',
      dayNumber: 27,
      title: 'More, Enough, and Good',
      goal: 'Say if food or drink is enough, more, good, or bad.',
      estimatedMinutes: 30,
      review: { wordCount: 7, patternCount: 3 },
      wordIds: ['more', 'enough', 'less', 'full', 'empty', 'taste', 'good', 'bad', 'food', 'drink'],
      patternIds: ['i-need-more', 'i-have-enough', 'the-thing-is-good'],
      exercises: [
        { type: 'choice', id: 'day-027-choice-001', prompt: 'Which sentence says more is needed?', options: ['I need more water.', 'I am from China.', 'The bag is old.'], correctOption: 'I need more water.' },
        { type: 'fill_blank', id: 'day-027-fill-001', prompt: 'The cup is ___.', acceptedAnswers: ['full', 'empty'] },
        { type: 'replacement', id: 'day-027-replace-001', patternId: 'i-need-more', slotValues: { thing: 'water' }, referenceAnswer: 'I need more water.' },
        { type: 'replacement', id: 'day-027-replace-002', patternId: 'the-thing-is-good', slotValues: { thing: 'food' }, referenceAnswer: 'The food is good.' },
        { type: 'sentence_order', id: 'day-027-order-001', tokens: ['is', 'empty', 'cup', 'The'], correctOrder: ['The', 'cup', 'is', 'empty'], finalSentence: 'The cup is empty.' },
        { type: 'translation', id: 'day-027-translation-001', chinesePrompt: '我需要更多的水。食物很好。', coreMeaningHint: 'Say amounts and quality.', suggestedPatternIds: ['i-need-more', 'the-thing-is-good'], referenceAnswers: ['I need more water. The food is good.'] },
      ],
      outputTask: {
        id: 'day-027-output',
        topic: 'Enough Food and Drink',
        prompts: ['Do you need more?', 'Is it enough or good?'],
        template: ['I need more ___.', 'I have enough ___.', 'The cup is ___.', 'The ___ is good.', 'The food is bad.'],
        requiredSentenceCount: 5,
      },
    },
    {
      id: 'day-028',
      weekId: 'week-04',
      dayNumber: 28,
      title: 'Week 4 Check',
      goal: 'Describe a simple meal or shopping scene with wants, needs, and help.',
      estimatedMinutes: 35,
      review: { wordCount: 10, patternCount: 4 },
      wordIds: ['food', 'drink', 'bread', 'milk', 'buy', 'shop', 'money', 'price', 'want', 'need', 'help', 'more', 'enough'],
      patternIds: ['i-want-some', 'i-need', 'i-buy', 'please-help-me'],
      exercises: [
        { type: 'choice', id: 'day-028-choice-001', prompt: 'Choose the best meal or shopping sentence.', options: ['I buy food at the shop.', 'The road is under the bus.', 'Happy name from.'], correctOption: 'I buy food at the shop.' },
        { type: 'fill_blank', id: 'day-028-fill-001', prompt: 'I need more ___.', acceptedAnswers: ['water', 'food', 'milk'] },
        { type: 'replacement', id: 'day-028-replace-001', patternId: 'i-want-some', slotValues: { thing: 'bread' }, referenceAnswer: 'I want some bread.' },
        { type: 'replacement', id: 'day-028-replace-002', patternId: 'i-buy', slotValues: { thing: 'food' }, referenceAnswer: 'I buy food.' },
        { type: 'sentence_order', id: 'day-028-order-001', tokens: ['need', 'help', 'I'], correctOrder: ['I', 'need', 'help'], finalSentence: 'I need help.' },
        { type: 'translation', id: 'day-028-translation-001', chinesePrompt: '我买食物。我需要更多的水。请帮助我。', coreMeaningHint: 'Describe a meal or shopping scene.', suggestedPatternIds: ['i-buy', 'i-need', 'please-help-me'], referenceAnswers: ['I buy food. I need more water. Please help me.'] },
      ],
      outputTask: {
        id: 'day-028-output',
        topic: 'Meal and Shopping Check',
        prompts: ['What food or drink do you buy?', 'What do you want or need?', 'Can you ask for help?'],
        template: ['I go to the shop.', 'I buy ___.', 'I want some ___.', 'I need ___.', 'Please help me.', 'The food is good.'],
        requiredSentenceCount: 6,
      },
      weeklyCheckRubric: {
        scale: { min: 0, max: 2 },
        pass: { minimumTotalScore: 7, minimumMeaningScore: 1, minimumSentenceCount: 6 },
        criteria: [
          { id: 'meaning', label: 'Meaning', scores: ['hard to understand', 'partly clear', 'clear'] },
          { id: 'shopping-meal', label: 'Shopping or meal detail', scores: ['no shopping or meal detail', 'some shopping or meal detail', 'clear shopping or meal scene'] },
          { id: 'target-patterns', label: 'Target patterns', scores: ['not used', 'used with help', 'used independently'] },
          { id: 'word-use', label: 'Word use', scores: ['few food or shopping words', 'some food or shopping words', 'several food or shopping words'] },
          { id: 'independence', label: 'Independence', scores: ['copied template', 'partly changed template', 'mostly own content'] },
        ],
      },
    },
  ],
};
