import type { Course, Pattern, Word } from '../domain/types';

const wordsWithoutDefinitions: Array<Omit<Word, 'definition' | 'phonetic'>> = [
  { id: 'name', text: 'name', category: 'general_thing', chinese: '名字', example: 'My name is Li.', weekIntroduced: 1, tags: ['identity'] },
  { id: 'my', text: 'my', category: 'structure', chinese: '我的', example: 'My friend is here.', weekIntroduced: 1, tags: ['pronoun'] },
  { id: 'i', text: 'I', category: 'structure', chinese: '我', example: 'I am a student.', weekIntroduced: 1, tags: ['pronoun'] },
  { id: 'am', text: 'am', category: 'operation', chinese: '是', example: 'I am from China.', weekIntroduced: 1, tags: ['be'] },
  { id: 'from', text: 'from', category: 'structure', chinese: '来自', example: 'I am from China.', weekIntroduced: 1, tags: ['place'] },
  { id: 'china', text: 'China', category: 'general_thing', chinese: '中国', example: 'I am from China.', weekIntroduced: 1, tags: ['place'] },
  { id: 'student', text: 'student', category: 'general_thing', chinese: '学生', example: 'I am a student.', weekIntroduced: 1, tags: ['identity'] },
  { id: 'happy', text: 'happy', category: 'quality', chinese: '高兴的', example: 'I am happy today.', weekIntroduced: 1, tags: ['feeling'] },
  { id: 'have', text: 'have', category: 'operation', chinese: '有', example: 'I have a question.', weekIntroduced: 1, tags: ['possession'] },
  { id: 'question', text: 'question', category: 'general_thing', chinese: '问题', example: 'I have a question.', weekIntroduced: 1, tags: ['study'] },
  { id: 'friend', text: 'friend', category: 'general_thing', chinese: '朋友', example: 'This is my friend.', weekIntroduced: 1, tags: ['people'] },
  { id: 'this', text: 'this', category: 'structure', chinese: '这个', example: 'This is my friend.', weekIntroduced: 1, tags: ['demonstrative'] },
  { id: 'he', text: 'he', category: 'structure', chinese: '他', example: 'He is kind.', weekIntroduced: 1, tags: ['pronoun'] },
  { id: 'she', text: 'she', category: 'structure', chinese: '她', example: 'She is kind.', weekIntroduced: 1, tags: ['pronoun'] },
  { id: 'kind', text: 'kind', category: 'quality', chinese: '友好的', example: 'She is kind.', weekIntroduced: 1, tags: ['people'] },
  { id: 'study', text: 'study', category: 'operation', chinese: '学习', example: 'I study English.', weekIntroduced: 1, tags: ['study'] },
  { id: 'english', text: 'English', category: 'general_thing', chinese: '英语', example: 'I study English.', weekIntroduced: 1, tags: ['study'] },
  { id: 'because', text: 'because', category: 'structure', chinese: '因为', example: 'I study English because it is useful.', weekIntroduced: 1, tags: ['reason'] },
  { id: 'want', text: 'want', category: 'operation', chinese: '想要', example: 'I want to learn English.', weekIntroduced: 1, tags: ['desire'] },
  { id: 'learn', text: 'learn', category: 'operation', chinese: '学习', example: 'I want to learn English.', weekIntroduced: 1, tags: ['study'] },
];

const phoneticByWordId: Record<string, string> = {
  name: '/ne\u026am/',
  my: '/ma\u026a/',
  i: '/a\u026a/',
  am: '/\u00e6m/',
  from: '/fr\u0252m/',
  china: '/\u02c8t\u0283a\u026an\u0259/',
  student: '/\u02c8stju\u02d0d\u0259nt/',
  happy: '/\u02c8h\u00e6pi/',
  have: '/h\u00e6v/',
  question: '/\u02c8kwest\u0283\u0259n/',
  friend: '/frend/',
  this: '/\u00f0\u026as/',
  he: '/hi\u02d0/',
  she: '/\u0283i\u02d0/',
  kind: '/ka\u026and/',
  study: '/\u02c8st\u028cdi/',
  english: '/\u02c8\u026a\u014b\u0261l\u026a\u0283/',
  because: '/b\u026a\u02c8k\u0252z/',
  want: '/w\u0252nt/',
  learn: '/l\u025c\u02d0n/',
};

const wordDefinitions: Record<string, string> = {
  name: 'the word for a person or thing',
  my: 'of me',
  i: 'the person speaking',
  am: 'the present form of be used with I',
  from: 'starting at a place or coming out of a place',
  china: 'a country in the east',
  student: 'a person who studies',
  happy: 'feeling good',
  have: 'to get or keep something',
  question: 'something you ask',
  friend: 'a person you like',
  this: 'the person or thing near you',
  he: 'a male person named before',
  she: 'a female person named before',
  kind: 'good and ready to help',
  study: 'to learn about something',
  english: 'the English language',
  because: 'for the reason that',
  want: 'to have a desire for something',
  learn: 'to get knowledge',
};

const words: Word[] = wordsWithoutDefinitions.map((word) => ({
  ...word,
  phonetic: phoneticByWordId[word.id] ?? '',
  definition: wordDefinitions[word.id] ?? '',
}));

const patterns: Pattern[] = [
  { id: 'my-name-is', title: 'My name is ___.', use: '说出自己的名字。', structure: 'My name is {name}.', examples: ['My name is Li.', 'My name is Anna.'], slots: ['name'] },
  { id: 'i-am-from', title: 'I am from ___.', use: '说明自己来自哪里。', structure: 'I am from {place}.', examples: ['I am from China.', 'I am from Shanghai.'], slots: ['place'] },
  { id: 'i-am', title: 'I am ___.', use: '描述身份或状态。', structure: 'I am {description}.', examples: ['I am a student.', 'I am happy today.'], slots: ['description'] },
  { id: 'i-have', title: 'I have ___.', use: '表达自己有什么。', structure: 'I have {thing}.', examples: ['I have a question.', 'I have a friend.'], slots: ['thing'] },
  { id: 'this-is', title: 'This is ___.', use: '介绍一个人或物。', structure: 'This is {personOrThing}.', examples: ['This is my friend.', 'This is my book.'], slots: ['personOrThing'] },
  { id: 'he-she-is', title: 'He/She is ___.', use: '描述另一个人。', structure: '{pronoun} is {description}.', examples: ['He is kind.', 'She is a student.'], slots: ['pronoun', 'description'] },
  { id: 'study-because', title: 'I study English because ___.', use: '说明学习英语的原因。', structure: 'I study English because {reason}.', examples: ['I study English because it is useful.', 'I study English because I want to speak.'], slots: ['reason'] },
];

export const week1Course: Course = {
  id: 'basic-english-12-weeks',
  title: 'Basic English 12 Weeks',
  contentVersion: '1.0.0',
  schemaVersion: 1,
  words,
  patterns,
  weeks: [
    {
      id: 'week-01',
      number: 1,
      title: 'Persons and Basic Sentences',
      goal: 'Introduce you and another person using simple Basic English.',
      days: [
        {
          id: 'day-001',
          weekId: 'week-01',
          dayNumber: 1,
          title: 'My Name',
          goal: 'Say your name and where you are from.',
          estimatedMinutes: 25,
          review: { wordCount: 0, patternCount: 0 },
          wordIds: ['name', 'my', 'i', 'am', 'from', 'china'],
          patternIds: ['my-name-is', 'i-am-from'],
          exercises: [
            { type: 'choice', id: 'day-001-choice-001', prompt: 'What does "name" mean?', options: ['名字', '问题', '朋友'], correctOption: '名字' },
            { type: 'fill_blank', id: 'day-001-fill-001', prompt: 'My ___ is Li.', acceptedAnswers: ['name'] },
            { type: 'sentence_order', id: 'day-001-order-001', tokens: ['from', 'China', 'am', 'I'], correctOrder: ['I', 'am', 'from', 'China'], finalSentence: 'I am from China.' },
            { type: 'replacement', id: 'day-001-replace-001', patternId: 'my-name-is', slotValues: { name: 'Anna' }, referenceAnswer: 'My name is Anna.' },
            { type: 'translation', id: 'day-001-translation-001', chinesePrompt: '我的名字是李。', coreMeaningHint: 'Say your name.', suggestedPatternIds: ['my-name-is'], referenceAnswers: ['My name is Li.'] },
          ],
          outputTask: {
            id: 'day-001-output',
            topic: 'My Name',
            prompts: ['What is your name?', 'Where are you from?'],
            template: ['My name is ___.', 'I am from ___.', 'I study English.'],
            requiredSentenceCount: 4,
          },
        },
        {
          id: 'day-002',
          weekId: 'week-01',
          dayNumber: 2,
          title: 'I Am',
          goal: 'Describe who you are and how you feel.',
          estimatedMinutes: 25,
          review: { wordCount: 3, patternCount: 1 },
          wordIds: ['student', 'happy', 'i', 'am', 'english', 'study'],
          patternIds: ['i-am'],
          exercises: [
            { type: 'choice', id: 'day-002-choice-001', prompt: 'Which sentence is correct?', options: ['I am a student.', 'I a student am.', 'Am I student a.'], correctOption: 'I am a student.' },
            { type: 'fill_blank', id: 'day-002-fill-001', prompt: 'I ___ happy today.', acceptedAnswers: ['am'] },
            { type: 'replacement', id: 'day-002-replace-001', patternId: 'i-am', slotValues: { description: 'a student' }, referenceAnswer: 'I am a student.' },
            { type: 'translation', id: 'day-002-translation-001', chinesePrompt: '我是学生。', coreMeaningHint: 'Say your identity.', suggestedPatternIds: ['i-am'], referenceAnswers: ['I am a student.'] },
            { type: 'sentence_order', id: 'day-002-order-001', tokens: ['happy', 'am', 'I', 'today'], correctOrder: ['I', 'am', 'happy', 'today'], finalSentence: 'I am happy today.' },
          ],
          outputTask: {
            id: 'day-002-output',
            topic: 'I Am',
            prompts: ['Who are you?', 'How do you feel today?'],
            template: ['I am ___.', 'I am from ___.', 'I am ___ today.'],
            requiredSentenceCount: 4,
          },
        },
        {
          id: 'day-003',
          weekId: 'week-01',
          dayNumber: 3,
          title: 'I Have',
          goal: 'Say what you have for you or study.',
          estimatedMinutes: 25,
          review: { wordCount: 3, patternCount: 1 },
          wordIds: ['have', 'question', 'friend', 'english', 'study', 'my'],
          patternIds: ['i-have'],
          exercises: [
            { type: 'choice', id: 'day-003-choice-001', prompt: 'What does "question" mean?', options: ['问题', '名字', '中国'], correctOption: '问题' },
            { type: 'fill_blank', id: 'day-003-fill-001', prompt: 'I ___ a question.', acceptedAnswers: ['have'] },
            { type: 'replacement', id: 'day-003-replace-001', patternId: 'i-have', slotValues: { thing: 'a friend' }, referenceAnswer: 'I have a friend.' },
            { type: 'translation', id: 'day-003-translation-001', chinesePrompt: '我有一个问题。', coreMeaningHint: 'Say what you have.', suggestedPatternIds: ['i-have'], referenceAnswers: ['I have a question.'] },
            { type: 'sentence_order', id: 'day-003-order-001', tokens: ['a', 'have', 'friend', 'I'], correctOrder: ['I', 'have', 'a', 'friend'], finalSentence: 'I have a friend.' },
          ],
          outputTask: {
            id: 'day-003-output',
            topic: 'What I Have',
            prompts: ['What do you have?', 'Do you have a question?'],
            template: ['I have ___.', 'I have a question.', 'I study English.'],
            requiredSentenceCount: 4,
          },
        },
        {
          id: 'day-004',
          weekId: 'week-01',
          dayNumber: 4,
          title: 'This Is',
          goal: 'Introduce a person or thing.',
          estimatedMinutes: 25,
          review: { wordCount: 3, patternCount: 1 },
          wordIds: ['this', 'friend', 'my', 'name', 'happy', 'kind'],
          patternIds: ['this-is'],
          exercises: [
            { type: 'choice', id: 'day-004-choice-001', prompt: 'Which sentence introduces a friend?', options: ['This is my friend.', 'I have from China.', 'Name my is Li.'], correctOption: 'This is my friend.' },
            { type: 'fill_blank', id: 'day-004-fill-001', prompt: 'This ___ my friend.', acceptedAnswers: ['is'] },
            { type: 'replacement', id: 'day-004-replace-001', patternId: 'this-is', slotValues: { personOrThing: 'my friend' }, referenceAnswer: 'This is my friend.' },
            { type: 'translation', id: 'day-004-translation-001', chinesePrompt: '这是我的朋友。', coreMeaningHint: 'Introduce a friend.', suggestedPatternIds: ['this-is'], referenceAnswers: ['This is my friend.'] },
            { type: 'sentence_order', id: 'day-004-order-001', tokens: ['my', 'This', 'friend', 'is'], correctOrder: ['This', 'is', 'my', 'friend'], finalSentence: 'This is my friend.' },
          ],
          outputTask: {
            id: 'day-004-output',
            topic: 'My Friend',
            prompts: ['Who is this?', 'What is his or her name?'],
            template: ['This is my ___.', 'His/Her name is ___.', 'He/She is ___.'],
            requiredSentenceCount: 4,
          },
        },
        {
          id: 'day-005',
          weekId: 'week-01',
          dayNumber: 5,
          title: 'He and She',
          goal: 'Describe another person.',
          estimatedMinutes: 25,
          review: { wordCount: 3, patternCount: 1 },
          wordIds: ['he', 'she', 'kind', 'friend', 'student', 'happy'],
          patternIds: ['he-she-is'],
          exercises: [
            { type: 'choice', id: 'day-005-choice-001', prompt: 'Which means "她很友好"?', options: ['She is kind.', 'He is from China.', 'I have a question.'], correctOption: 'She is kind.' },
            { type: 'fill_blank', id: 'day-005-fill-001', prompt: 'She ___ kind.', acceptedAnswers: ['is'] },
            { type: 'replacement', id: 'day-005-replace-001', patternId: 'he-she-is', slotValues: { pronoun: 'He', description: 'a student' }, referenceAnswer: 'He is a student.' },
            { type: 'translation', id: 'day-005-translation-001', chinesePrompt: '他是学生。', coreMeaningHint: 'Describe another person.', suggestedPatternIds: ['he-she-is'], referenceAnswers: ['He is a student.'] },
            { type: 'sentence_order', id: 'day-005-order-001', tokens: ['kind', 'is', 'She'], correctOrder: ['She', 'is', 'kind'], finalSentence: 'She is kind.' },
          ],
          outputTask: {
            id: 'day-005-output',
            topic: 'Describe a Person',
            prompts: ['Who is this person?', 'What is this person like?'],
            template: ['This is my ___.', 'He/She is ___.', 'He/She is kind.'],
            requiredSentenceCount: 4,
          },
        },
        {
          id: 'day-006',
          weekId: 'week-01',
          dayNumber: 6,
          title: 'Why I Study English',
          goal: 'Give a simple reason for studying English.',
          estimatedMinutes: 30,
          review: { wordCount: 4, patternCount: 1 },
          wordIds: ['study', 'english', 'because', 'want', 'learn', 'question'],
          patternIds: ['study-because'],
          exercises: [
            { type: 'choice', id: 'day-006-choice-001', prompt: 'What does "because" show?', options: ['原因', '名字', '朋友'], correctOption: '原因' },
            { type: 'fill_blank', id: 'day-006-fill-001', prompt: 'I study English ___ it is useful.', acceptedAnswers: ['because'] },
            { type: 'replacement', id: 'day-006-replace-001', patternId: 'study-because', slotValues: { reason: 'I want to learn' }, referenceAnswer: 'I study English because I want to learn.' },
            { type: 'translation', id: 'day-006-translation-001', chinesePrompt: '我学习英语，因为我想学习。', coreMeaningHint: 'Give a reason.', suggestedPatternIds: ['study-because'], referenceAnswers: ['I study English because I want to learn.'] },
            { type: 'sentence_order', id: 'day-006-order-001', tokens: ['English', 'study', 'I', 'because', 'learn', 'want', 'to', 'I'], correctOrder: ['I', 'study', 'English', 'because', 'I', 'want', 'to', 'learn'], finalSentence: 'I study English because I want to learn.' },
          ],
          outputTask: {
            id: 'day-006-output',
            topic: 'Why I Study English',
            prompts: ['Why do you study English?', 'What do you want?'],
            template: ['I study English because ___.', 'I want to ___.', 'English is important for me.'],
            requiredSentenceCount: 5,
          },
        },
        {
          id: 'day-007',
          weekId: 'week-01',
          dayNumber: 7,
          title: 'Week 1 Story',
          goal: 'Introduce you with your words.',
          estimatedMinutes: 35,
          review: { wordCount: 8, patternCount: 3 },
          wordIds: ['name', 'my', 'i', 'am', 'from', 'student', 'have', 'friend', 'study', 'english', 'because', 'want', 'learn'],
          patternIds: ['my-name-is', 'i-am-from', 'i-am', 'i-have', 'study-because'],
          exercises: [
            { type: 'choice', id: 'day-007-choice-001', prompt: 'Choose the best self-introduction sentence.', options: ['My name is Li.', 'Friend my is Li.', 'Because name my.'], correctOption: 'My name is Li.' },
            { type: 'fill_blank', id: 'day-007-fill-001', prompt: 'I study English ___ I want to learn.', acceptedAnswers: ['because'] },
            { type: 'sentence_order', id: 'day-007-order-001', tokens: ['have', 'I', 'a', 'question'], correctOrder: ['I', 'have', 'a', 'question'], finalSentence: 'I have a question.' },
            { type: 'translation', id: 'day-007-translation-001', chinesePrompt: '我来自中国。我学习英语，因为我想学习。', coreMeaningHint: 'Introduce place and reason.', suggestedPatternIds: ['i-am-from', 'study-because'], referenceAnswers: ['I am from China. I study English because I want to learn.'] },
            { type: 'replacement', id: 'day-007-replace-001', patternId: 'i-am', slotValues: { description: 'happy today' }, referenceAnswer: 'I am happy today.' },
          ],
          outputTask: {
            id: 'day-007-output',
            topic: 'Week 1 Self Introduction',
            prompts: ['What is your name?', 'Where are you from?', 'Who are you?', 'Why do you study English?'],
            template: ['My name is ___.', 'I am from ___.', 'I am ___.', 'I have ___.', 'I study English because ___.'],
            requiredSentenceCount: 6,
          },
          weeklyCheckRubric: {
            scale: { min: 0, max: 2 },
            pass: {
              minimumTotalScore: 7,
              minimumMeaningScore: 1,
              minimumSentenceCount: 5,
            },
            criteria: [
              { id: 'meaning', label: 'Meaning', scores: ['hard to understand', 'partly clear', 'clear'] },
              {
                id: 'sentence-control',
                label: 'Sentence control',
                scores: ['not complete', 'some complete sentences', 'complete sentences'],
              },
              { id: 'target-patterns', label: 'Form use', scores: ['not used', 'used with help', 'used with no help'] },
              { id: 'word-use', label: 'Word use', scores: ['little new words', 'some new words', 'much new words'] },
              { id: 'independence', label: 'My words', scores: ['same as example', 'some change from example', 'all my words'] },
            ],
          },
        },
      ],
    },
  ],
};

export const week1Words = words;
export const week1Patterns = patterns;
export const week1 = week1Course.weeks[0];
