import type { Pattern, Week, Word } from '../domain/types';

export const week5Words: Word[] = [
  { id: 'outside', text: 'outside', category: 'structure', definition: 'not in a house or room', chinese: '外面', example: 'I go outside.', weekIntroduced: 5, tags: ['going-out'] },
  { id: 'way', text: 'way', category: 'general_thing', definition: 'a road or direction for going', chinese: '路；路线', example: 'This way is good.', weekIntroduced: 5, tags: ['going-out'] },
  { id: 'stop', text: 'stop', category: 'operation', definition: 'to not go on', chinese: '停下', example: 'I stop here.', weekIntroduced: 5, tags: ['going-out'] },
  { id: 'far', text: 'far', category: 'quality', definition: 'not near', chinese: '远的', example: 'The shop is far.', weekIntroduced: 5, tags: ['place'] },
  { id: 'transport', text: 'transport', category: 'general_thing', definition: 'a way of moving persons or things', chinese: '交通；运输', example: 'I take the bus.', weekIntroduced: 5, tags: ['transport'] },
  { id: 'waiting', text: 'waiting', category: 'operation', definition: 'waiting for something to come', chinese: '等待', example: 'I am waiting for the bus.', weekIntroduced: 5, tags: ['transport'] },
  { id: 'seat', text: 'seat', category: 'picturable_thing', definition: 'a place for one person', chinese: '座位', example: 'The seat is here.', weekIntroduced: 5, tags: ['transport'] },
  { id: 'left', text: 'left', category: 'structure', definition: 'the side opposite right', chinese: '左边', example: 'I turn left.', weekIntroduced: 5, tags: ['direction'] },
  { id: 'right', text: 'right', category: 'structure', definition: 'the side opposite left', chinese: '右边', example: 'I turn right.', weekIntroduced: 5, tags: ['direction'] },
  { id: 'straight', text: 'straight', category: 'quality', definition: 'not turning', chinese: '直的；直走', example: 'I go straight.', weekIntroduced: 5, tags: ['direction'] },
  { id: 'line', text: 'line', category: 'general_thing', definition: 'persons or things one after another', chinese: '队伍；排队', example: 'I am in line.', weekIntroduced: 5, tags: ['public'] },
  { id: 'turn', text: 'turn', category: 'operation', definition: 'to change direction', chinese: '转弯', example: 'I turn left.', weekIntroduced: 5, tags: ['direction'] },
  { id: 'list', text: 'list', category: 'general_thing', definition: 'words for things to keep', chinese: '清单', example: 'I have a list.', weekIntroduced: 5, tags: ['going-out'] },
  { id: 'carry', text: 'carry', category: 'operation', definition: 'to take something in your hand or bag', chinese: '携带；拿着', example: 'I carry my bag.', weekIntroduced: 5, tags: ['going-out'] },
  { id: 'back', text: 'back', category: 'structure', definition: 'to the place before', chinese: '回去；返回', example: 'I go back home.', weekIntroduced: 5, tags: ['going-out'] },
  { id: 'weight', text: 'weight', category: 'general_thing', definition: 'how much pull a thing has', chinese: '重量', example: 'The bag has much weight.', weekIntroduced: 5, tags: ['quality'] },
  { id: 'light', text: 'light', category: 'quality', definition: 'with little weight', chinese: '轻的', example: 'The bag is light.', weekIntroduced: 5, tags: ['quality'] },
];

export const week5Patterns: Pattern[] = [
  { id: 'i-go-outside', title: 'I go outside.', use: 'Say going out.', structure: 'I go outside.', examples: ['I go outside.'], slots: [] },
  { id: 'the-way-is', title: 'The way is ___.', use: 'Say what a way is like.', structure: 'The way is {quality}.', examples: ['The way is good.', 'The way is straight.'], slots: ['quality'] },
  { id: 'i-stop-at', title: 'I stop at ___.', use: 'Say where you stop.', structure: 'I stop at {place}.', examples: ['I stop at the shop.', 'I stop at the road.'], slots: ['place'] },
  { id: 'it-is-far', title: 'It is far.', use: 'Say a place is not near.', structure: 'It is far.', examples: ['It is far.'], slots: [] },
  { id: 'i-go-by', title: 'I go by ___.', use: 'Say how you go.', structure: 'I go by {transport}.', examples: ['I go by bus.'], slots: ['transport'] },
  { id: 'i-am-waiting-for', title: 'I am waiting for ___.', use: 'Say what you are waiting for.', structure: 'I am waiting for {thing}.', examples: ['I am waiting for the bus.', 'I am waiting for my friend.'], slots: ['thing'] },
  { id: 'the-seat-is', title: 'The seat is ___.', use: 'Say where a seat is.', structure: 'The seat is {place}.', examples: ['The seat is here.', 'The seat is near me.'], slots: ['place'] },
  { id: 'i-turn', title: 'I turn ___.', use: 'Say left or right.', structure: 'I turn {side}.', examples: ['I turn left.', 'I turn right.'], slots: ['side'] },
  { id: 'i-go-straight', title: 'I go straight.', use: 'Say going with no turn.', structure: 'I go straight.', examples: ['I go straight.'], slots: [] },
  { id: 'i-am-in-line', title: 'I am in line.', use: 'Say waiting in a line.', structure: 'I am in line.', examples: ['I am in line.'], slots: [] },
  { id: 'i-am-in-line-at', title: 'I am in line at ___.', use: 'Say where you are in line.', structure: 'I am in line at {place}.', examples: ['I am in line at the shop.', 'I am in line at the store.'], slots: ['place'] },
  { id: 'i-have-a-list', title: 'I have a list.', use: 'Say you have words for things.', structure: 'I have a list.', examples: ['I have a list.'], slots: [] },
  { id: 'i-carry', title: 'I carry ___.', use: 'Say what you take with you.', structure: 'I carry {thing}.', examples: ['I carry my bag.', 'I carry a book.'], slots: ['thing'] },
  { id: 'the-bag-has-weight', title: 'The bag has ___ weight.', use: 'Say if a bag has much or little weight.', structure: 'The bag has {amount} weight.', examples: ['The bag has much weight.', 'The bag has little weight.'], slots: ['amount'] },
  { id: 'i-go-back-home', title: 'I go back home.', use: 'Say going back home.', structure: 'I go back home.', examples: ['I go back home.'], slots: [] },
];

export const week5: Week = {
  id: 'week-05',
  number: 5,
  title: 'Going Outside for Things',
  goal: 'Go outside, take a way, use a bus, and bring things back.',
  days: [
    {
      id: 'day-029',
      weekId: 'week-05',
      dayNumber: 29,
      title: 'Going Outside',
      goal: 'Say that you go outside and take a way.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['outside', 'way', 'stop', 'far', 'go', 'road', 'shop'],
      patternIds: ['i-go-outside', 'the-way-is', 'i-stop-at'],
      exercises: [
        { type: 'choice', id: 'day-029-choice-001', prompt: 'Which sentence says going out?', options: ['I go outside.', 'I sleep at night.', 'The cup is full.'], correctOption: 'I go outside.' },
        { type: 'fill_blank', id: 'day-029-fill-001', prompt: 'The way is ___.', acceptedAnswers: ['good', 'straight'] },
        { type: 'replacement', id: 'day-029-replace-001', patternId: 'the-way-is', slotValues: { quality: 'good' }, referenceAnswer: 'The way is good.' },
        { type: 'replacement', id: 'day-029-replace-002', patternId: 'i-stop-at', slotValues: { place: 'the shop' }, referenceAnswer: 'I stop at the shop.' },
        { type: 'sentence_order', id: 'day-029-order-001', tokens: ['go', 'outside', 'I'], correctOrder: ['I', 'go', 'outside'], finalSentence: 'I go outside.' },
        { type: 'translation', id: 'day-029-translation-001', chinesePrompt: '我去外面，在商店停下。', coreMeaningHint: 'Say a simple way outside.', suggestedPatternIds: ['i-go-outside', 'i-stop-at'], referenceAnswers: ['I go outside. I stop at the shop.'] },
      ],
      outputTask: {
        id: 'day-029-output',
        topic: 'Going Outside',
        prompts: ['Where do you go?', 'Where do you stop?'],
        template: ['I go outside.', 'The way is ___.', 'I stop at ___.', 'It is far.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about going outside and stopping at a place.',
      },
    },
    {
      id: 'day-030',
      weekId: 'week-05',
      dayNumber: 30,
      title: 'Bus and Seat',
      goal: 'Say how you go and where the seat is.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['transport', 'waiting', 'seat', 'bus', 'road', 'go', 'friend'],
      patternIds: ['i-go-by', 'i-am-waiting-for', 'the-seat-is'],
      exercises: [
        { type: 'choice', id: 'day-030-choice-001', prompt: 'Which sentence is about a bus?', options: ['I am waiting for the bus.', 'I wash my face.', 'The bread is cheap.'], correctOption: 'I am waiting for the bus.' },
        { type: 'fill_blank', id: 'day-030-fill-001', prompt: 'I go by ___.', acceptedAnswers: ['bus'] },
        { type: 'replacement', id: 'day-030-replace-001', patternId: 'i-go-by', slotValues: { transport: 'bus' }, referenceAnswer: 'I go by bus.' },
        { type: 'replacement', id: 'day-030-replace-002', patternId: 'i-am-waiting-for', slotValues: { thing: 'the bus' }, referenceAnswer: 'I am waiting for the bus.' },
        { type: 'sentence_order', id: 'day-030-order-001', tokens: ['is', 'here', 'seat', 'The'], correctOrder: ['The', 'seat', 'is', 'here'], finalSentence: 'The seat is here.' },
        { type: 'translation', id: 'day-030-translation-001', chinesePrompt: '我在等公共汽车，座位在这里。', coreMeaningHint: 'Say bus and seat actions.', suggestedPatternIds: ['i-am-waiting-for', 'the-seat-is'], referenceAnswers: ['I am waiting for the bus. The seat is here.'] },
      ],
      outputTask: {
        id: 'day-030-output',
        topic: 'By Bus',
        prompts: ['What are you waiting for?', 'Where is the seat?'],
        template: ['I am waiting for ___.', 'I go by ___.', 'I take the bus.', 'The seat is ___.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about being in line for a bus and getting a seat.',
      },
    },
    {
      id: 'day-031',
      weekId: 'week-05',
      dayNumber: 31,
      title: 'Left and Right',
      goal: 'Say simple directions outside.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['left', 'right', 'straight', 'turn', 'way', 'road', 'near'],
      patternIds: ['i-turn', 'i-go-straight', 'the-way-is'],
      exercises: [
        { type: 'choice', id: 'day-031-choice-001', prompt: 'Which sentence gives a direction?', options: ['I turn left.', 'I eat rice.', 'The room is clean.'], correctOption: 'I turn left.' },
        { type: 'fill_blank', id: 'day-031-fill-001', prompt: 'I turn ___.', acceptedAnswers: ['left', 'right'] },
        { type: 'replacement', id: 'day-031-replace-001', patternId: 'i-turn', slotValues: { side: 'left' }, referenceAnswer: 'I turn left.' },
        { type: 'replacement', id: 'day-031-replace-002', patternId: 'the-way-is', slotValues: { quality: 'straight' }, referenceAnswer: 'The way is straight.' },
        { type: 'sentence_order', id: 'day-031-order-001', tokens: ['go', 'straight', 'I'], correctOrder: ['I', 'go', 'straight'], finalSentence: 'I go straight.' },
        { type: 'translation', id: 'day-031-translation-001', chinesePrompt: '我直走，然后向右转。', coreMeaningHint: 'Say simple directions.', suggestedPatternIds: ['i-go-straight', 'i-turn'], referenceAnswers: ['I go straight. I turn right.'] },
      ],
      outputTask: {
        id: 'day-031-output',
        topic: 'Simple Directions',
        prompts: ['Do you go straight?', 'Do you turn left or right?'],
        template: ['I go straight.', 'I turn ___.', 'The way is ___.', 'The road is near.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about going straight and turning one way.',
      },
    },
    {
      id: 'day-032',
      weekId: 'week-05',
      dayNumber: 32,
      title: 'Waiting in Line',
      goal: 'Say that you are in line outside.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['line', 'waiting', 'stop', 'outside', 'shop', 'friend', 'thing'],
      patternIds: ['i-am-in-line', 'i-am-in-line-at', 'i-stop-at'],
      exercises: [
        { type: 'choice', id: 'day-032-choice-001', prompt: 'Which sentence says being in a line?', options: ['I am in line.', 'I make food.', 'The pen is blue.'], correctOption: 'I am in line.' },
        { type: 'fill_blank', id: 'day-032-fill-001', prompt: 'I am in line at ___.', acceptedAnswers: ['the shop', 'the store'] },
        { type: 'replacement', id: 'day-032-replace-001', patternId: 'i-am-in-line-at', slotValues: { place: 'the shop' }, referenceAnswer: 'I am in line at the shop.' },
        { type: 'replacement', id: 'day-032-replace-002', patternId: 'i-stop-at', slotValues: { place: 'the line' }, referenceAnswer: 'I stop at the line.' },
        { type: 'sentence_order', id: 'day-032-order-001', tokens: ['line', 'in', 'am', 'I'], correctOrder: ['I', 'am', 'in', 'line'], finalSentence: 'I am in line.' },
        { type: 'translation', id: 'day-032-translation-001', chinesePrompt: '我在商店排队。', coreMeaningHint: 'Say being in line.', suggestedPatternIds: ['i-am-in-line', 'i-am-in-line-at'], referenceAnswers: ['I am in line. I am in line at the shop.'] },
      ],
      outputTask: {
        id: 'day-032-output',
        topic: 'In Line',
        prompts: ['Where is the line?', 'Where do you stop?'],
        template: ['I go outside.', 'I am in line.', 'I am in line at ___.', 'I stop at ___.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about being in line outside a shop.',
      },
    },
    {
      id: 'day-033',
      weekId: 'week-05',
      dayNumber: 33,
      title: 'List and Bag',
      goal: 'Say what you carry and what is on your list.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['list', 'carry', 'weight', 'light', 'bag', 'food', 'bread', 'milk'],
      patternIds: ['i-have-a-list', 'i-carry', 'the-bag-has-weight'],
      exercises: [
        { type: 'choice', id: 'day-033-choice-001', prompt: 'Which sentence is about a list?', options: ['I have a list.', 'The bus is late.', 'I sleep at home.'], correctOption: 'I have a list.' },
        { type: 'fill_blank', id: 'day-033-fill-001', prompt: 'The bag has ___ weight.', acceptedAnswers: ['much', 'little'] },
        { type: 'replacement', id: 'day-033-replace-001', patternId: 'i-carry', slotValues: { thing: 'my bag' }, referenceAnswer: 'I carry my bag.' },
        { type: 'replacement', id: 'day-033-replace-002', patternId: 'the-bag-has-weight', slotValues: { amount: 'much' }, referenceAnswer: 'The bag has much weight.' },
        { type: 'sentence_order', id: 'day-033-order-001', tokens: ['a', 'have', 'list', 'I'], correctOrder: ['I', 'have', 'a', 'list'], finalSentence: 'I have a list.' },
        { type: 'translation', id: 'day-033-translation-001', chinesePrompt: '我带着包，也有一张清单。', coreMeaningHint: 'Say list and bag sentences.', suggestedPatternIds: ['i-have-a-list', 'i-carry'], referenceAnswers: ['I have a list. I carry my bag.'] },
      ],
      outputTask: {
        id: 'day-033-output',
        topic: 'My List',
        prompts: ['What do you carry?', 'Does your bag have much or little weight?'],
        template: ['I have a list.', 'I carry ___.', 'The bag has ___ weight.', 'I need ___.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about a list and a bag you carry.',
      },
    },
    {
      id: 'day-034',
      weekId: 'week-05',
      dayNumber: 34,
      title: 'Going Back',
      goal: 'Say what you bring back home.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['back', 'carry', 'outside', 'home', 'bring', 'bag', 'food', 'shop'],
      patternIds: ['i-go-back-home', 'i-carry', 'i-get-from-shop'],
      exercises: [
        { type: 'choice', id: 'day-034-choice-001', prompt: 'Which sentence says going back?', options: ['I go back home.', 'I turn left.', 'The chair is red.'], correctOption: 'I go back home.' },
        { type: 'fill_blank', id: 'day-034-fill-001', prompt: 'I go back ___.', acceptedAnswers: ['home'] },
        { type: 'replacement', id: 'day-034-replace-001', patternId: 'i-carry', slotValues: { thing: 'food' }, referenceAnswer: 'I carry food.' },
        { type: 'replacement', id: 'day-034-replace-002', patternId: 'i-get-from-shop', slotValues: { thing: 'bread' }, referenceAnswer: 'I get bread from the shop.' },
        { type: 'sentence_order', id: 'day-034-order-001', tokens: ['back', 'home', 'go', 'I'], correctOrder: ['I', 'go', 'back', 'home'], finalSentence: 'I go back home.' },
        { type: 'translation', id: 'day-034-translation-001', chinesePrompt: '我从商店拿到食物，然后回家。', coreMeaningHint: 'Say coming back with things.', suggestedPatternIds: ['i-go-back-home', 'i-get-from-shop'], referenceAnswers: ['I get bread from the shop. I go back home.'] },
      ],
      outputTask: {
        id: 'day-034-output',
        topic: 'Back Home',
        prompts: ['What do you get?', 'What do you carry back?'],
        template: ['I get ___ from the shop.', 'I carry ___.', 'The bag is ___.', 'I go back home.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about getting one thing and going back home.',
      },
    },
    {
      id: 'day-035',
      weekId: 'week-05',
      dayNumber: 35,
      title: 'Week 5 Story',
      goal: 'Tell a simple going-out story from home to coming back.',
      estimatedMinutes: 35,
      review: { wordCount: 10, patternCount: 4 },
      wordIds: ['outside', 'way', 'waiting', 'bus', 'left', 'right', 'straight', 'list', 'carry', 'back', 'weight', 'light'],
      patternIds: ['i-go-outside', 'i-am-waiting-for', 'i-turn', 'i-have-a-list', 'i-go-back-home'],
      exercises: [
        { type: 'choice', id: 'day-035-choice-001', prompt: 'Which sentence is good for a going-out story?', options: ['I go outside with my list.', 'The milk is in the cup.', 'My name is Anna.'], correctOption: 'I go outside with my list.' },
        { type: 'fill_blank', id: 'day-035-fill-001', prompt: 'I turn ___.', acceptedAnswers: ['left', 'right'] },
        { type: 'replacement', id: 'day-035-replace-001', patternId: 'i-am-waiting-for', slotValues: { thing: 'the bus' }, referenceAnswer: 'I am waiting for the bus.' },
        { type: 'replacement', id: 'day-035-replace-002', patternId: 'i-turn', slotValues: { side: 'right' }, referenceAnswer: 'I turn right.' },
        { type: 'sentence_order', id: 'day-035-order-001', tokens: ['list', 'a', 'have', 'I'], correctOrder: ['I', 'have', 'a', 'list'], finalSentence: 'I have a list.' },
        { type: 'translation', id: 'day-035-translation-001', chinesePrompt: '我去外面，排队，转弯，然后回家。', coreMeaningHint: 'Tell a full going-out story.', suggestedPatternIds: ['i-go-outside', 'i-am-waiting-for', 'i-turn', 'i-go-back-home'], referenceAnswers: ['I go outside. I am waiting for the bus. I turn right. I go back home.'] },
      ],
      outputTask: {
        id: 'day-035-output',
        topic: 'Going Out Story',
        prompts: ['How do you go outside?', 'What do you do before you go back home?'],
        template: ['I go outside.', 'I have a list.', 'I am waiting for ___.', 'I turn ___.', 'I carry ___.', 'I go back home.'],
        requiredSentenceCount: 6,
        storyMode: 'recap',
        storyPrompt: 'Make a full story about going outside, being in line, turning, carrying a thing, and going back home.',
      },
      weeklyCheckRubric: {
        scale: { min: 0, max: 2 },
        pass: { minimumTotalScore: 7, minimumMeaningScore: 1, minimumSentenceCount: 6 },
        criteria: [
          { id: 'meaning', label: 'Meaning', scores: ['hard to understand', 'partly clear', 'clear'] },
          { id: 'going-out-order', label: 'Going out order', scores: ['no clear order', 'some order', 'clear going out and back order'] },
          { id: 'target-patterns', label: 'Form use', scores: ['not used', 'used with help', 'used with no help'] },
          { id: 'word-use', label: 'Word use', scores: ['little outside words', 'some outside words', 'much outside words'] },
          { id: 'independence', label: 'My words', scores: ['same as example', 'some change from example', 'all my words'] },
        ],
      },
    },
  ],
};
