import type { Pattern, Week, Word } from '../domain/types';

export const week7Words: Word[] = [
  { id: 'body', text: 'body', category: 'picturable_thing', definition: 'all of a person', phonetic: '/ˈbɒdi/', chinese: '身体', example: 'My body needs care.', weekIntroduced: 7, tags: ['body'] },
  { id: 'head', text: 'head', category: 'picturable_thing', definition: 'the part over the neck', phonetic: '/hed/', chinese: '头', example: 'This is my head.', weekIntroduced: 7, tags: ['body'] },
  { id: 'hand', text: 'hand', category: 'picturable_thing', definition: 'the part at the end of the arm', phonetic: '/hænd/', chinese: '手', example: 'This is my hand.', weekIntroduced: 7, tags: ['body'] },
  { id: 'foot', text: 'foot', category: 'picturable_thing', definition: 'the part at the end of the leg', phonetic: '/fʊt/', chinese: '脚', example: 'This is my foot.', weekIntroduced: 7, tags: ['body'] },
  { id: 'pain', text: 'pain', category: 'general_thing', definition: 'a bad feeling in the body', phonetic: '/peɪn/', chinese: '疼痛', example: 'I have pain in my head.', weekIntroduced: 7, tags: ['body', 'problem'] },
  { id: 'ill', text: 'ill', category: 'quality', definition: 'not healthy', phonetic: '/ɪl/', chinese: '生病的', example: 'I feel ill.', weekIntroduced: 7, tags: ['body', 'problem'] },
  { id: 'tired', text: 'tired', category: 'quality', definition: 'needing sleep or rest', phonetic: '/ˈtaɪəd/', chinese: '累的', example: 'I am tired.', weekIntroduced: 7, tags: ['body'] },
  { id: 'rest', text: 'rest', category: 'operation', definition: 'quiet time after work', phonetic: '/rest/', chinese: '休息', example: 'I need rest.', weekIntroduced: 7, tags: ['care'] },
  { id: 'care', text: 'care', category: 'operation', definition: 'help for a person or body', phonetic: '/keə/', chinese: '照顾', example: 'I need care.', weekIntroduced: 7, tags: ['care'] },
  { id: 'warm', text: 'warm', category: 'quality', definition: 'not cold and with heat', phonetic: '/wɔːm/', chinese: '温暖的', example: 'I keep warm.', weekIntroduced: 7, tags: ['care'] },
];

export const week7Patterns: Pattern[] = [
  { id: 'this-is-my-part', title: 'This is my ___.', use: 'Say one body part.', structure: 'This is my {part}.', examples: ['This is my head.', 'This is my hand.'], slots: ['part'] },
  { id: 'i-have-pain-in-my', title: 'I have pain in my ___.', use: 'Say where the body pain is.', structure: 'I have pain in my {part}.', examples: ['I have pain in my head.', 'I have pain in my foot.'], slots: ['part'] },
  { id: 'i-feel-ill', title: 'I feel ill.', use: 'Say you are not healthy.', structure: 'I feel ill.', examples: ['I feel ill.'], slots: [] },
  { id: 'i-am-tired', title: 'I am tired.', use: 'Say you need rest.', structure: 'I am tired.', examples: ['I am tired.'], slots: [] },
  { id: 'i-need-rest', title: 'I need rest.', use: 'Say you need quiet time.', structure: 'I need rest.', examples: ['I need rest.'], slots: [] },
  { id: 'i-need-care', title: 'I need care.', use: 'Ask for simple care.', structure: 'I need care.', examples: ['I need care.'], slots: [] },
  { id: 'i-keep-warm', title: 'I keep warm.', use: 'Say you keep the body warm.', structure: 'I keep warm.', examples: ['I keep warm.'], slots: [] },
];

export const week7: Week = {
  id: 'week-07',
  number: 7,
  title: 'Body and Care',
  goal: 'Say simple body problems and ask for care.',
  days: [
    {
      id: 'day-043',
      weekId: 'week-07',
      dayNumber: 43,
      title: 'Body Parts',
      goal: 'Say your head, hand, foot, and body.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['body', 'head', 'hand', 'foot', 'face', 'this', 'my'],
      patternIds: ['this-is-my-part'],
      exercises: [
        { type: 'choice', id: 'day-043-choice-001', prompt: 'Which sentence names a body part?', options: ['This is my head.', 'I buy bread.', 'The road is far.'], correctOption: 'This is my head.' },
        { type: 'fill_blank', id: 'day-043-fill-001', prompt: 'This is my ___.', acceptedAnswers: ['head', 'hand', 'foot'] },
        { type: 'replacement', id: 'day-043-replace-001', patternId: 'this-is-my-part', slotValues: { part: 'hand' }, referenceAnswer: 'This is my hand.' },
        { type: 'sentence_order', id: 'day-043-order-001', tokens: ['my', 'head', 'is', 'This'], correctOrder: ['This', 'is', 'my', 'head'], finalSentence: 'This is my head.' },
        { type: 'fill_blank', id: 'day-043-fill-002', prompt: 'My ___ is here.', acceptedAnswers: ['body', 'head', 'hand', 'foot'] },
        { type: 'translation', id: 'day-043-translation-001', chinesePrompt: '这是我的头和手。', coreMeaningHint: 'Name body parts.', suggestedPatternIds: ['this-is-my-part'], referenceAnswers: ['This is my head. This is my hand.'] },
      ],
      outputTask: {
        id: 'day-043-output',
        topic: 'My Body',
        prompts: ['What body part can you name?', 'What part is here?'],
        template: ['This is my head.', 'This is my hand.', 'This is my foot.', 'This is my body.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story naming simple body parts.',
      },
    },
    {
      id: 'day-044',
      weekId: 'week-07',
      dayNumber: 44,
      title: 'Feel Ill',
      goal: 'Say when you feel ill or tired.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['ill', 'tired', 'rest', 'water', 'bad', 'good', 'body'],
      patternIds: ['i-feel-ill', 'i-am-tired', 'i-need-rest'],
      exercises: [
        { type: 'choice', id: 'day-044-choice-001', prompt: 'Which sentence says a body problem?', options: ['I feel ill.', 'The cup is full.', 'I turn left.'], correctOption: 'I feel ill.' },
        { type: 'fill_blank', id: 'day-044-fill-001', prompt: 'I feel ___.', acceptedAnswers: ['ill', 'bad'] },
        { type: 'sentence_order', id: 'day-044-order-001', tokens: ['feel', 'ill', 'I'], correctOrder: ['I', 'feel', 'ill'], finalSentence: 'I feel ill.' },
        { type: 'fill_blank', id: 'day-044-fill-002', prompt: 'I am ___.', acceptedAnswers: ['tired'] },
        { type: 'choice', id: 'day-044-choice-002', prompt: 'What do you need when you are tired?', options: ['I need rest.', 'I need a road.', 'I need a price.'], correctOption: 'I need rest.' },
        { type: 'translation', id: 'day-044-translation-001', chinesePrompt: '我感觉不舒服，也很累，需要休息。', coreMeaningHint: 'Say how the body feels.', suggestedPatternIds: ['i-feel-ill', 'i-am-tired', 'i-need-rest'], referenceAnswers: ['I feel ill. I am tired. I need rest.'] },
      ],
      outputTask: {
        id: 'day-044-output',
        topic: 'How I Feel',
        prompts: ['How do you feel?', 'What do you need?'],
        template: ['I feel ill.', 'I am tired.', 'I need rest.', 'I need water.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about feeling ill, being tired, and needing rest.',
      },
    },
    {
      id: 'day-045',
      weekId: 'week-07',
      dayNumber: 45,
      title: 'Body Pain',
      goal: 'Say where you have body pain.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['pain', 'head', 'hand', 'foot', 'body', 'care', 'help'],
      patternIds: ['i-have-pain-in-my', 'this-is-my-part', 'i-need-care'],
      exercises: [
        { type: 'choice', id: 'day-045-choice-001', prompt: 'Which sentence says where pain is?', options: ['I have pain in my head.', 'I have rice in my bag.', 'I walk to the store.'], correctOption: 'I have pain in my head.' },
        { type: 'fill_blank', id: 'day-045-fill-001', prompt: 'I have ___ in my head.', acceptedAnswers: ['pain'] },
        { type: 'replacement', id: 'day-045-replace-001', patternId: 'i-have-pain-in-my', slotValues: { part: 'foot' }, referenceAnswer: 'I have pain in my foot.' },
        { type: 'sentence_order', id: 'day-045-order-001', tokens: ['pain', 'my', 'in', 'hand', 'have', 'I'], correctOrder: ['I', 'have', 'pain', 'in', 'my', 'hand'], finalSentence: 'I have pain in my hand.' },
        { type: 'fill_blank', id: 'day-045-fill-002', prompt: 'I need ___.', acceptedAnswers: ['care', 'help'] },
        { type: 'translation', id: 'day-045-translation-001', chinesePrompt: '我的脚疼，我需要照顾。', coreMeaningHint: 'Say body pain and care.', suggestedPatternIds: ['i-have-pain-in-my', 'i-need-care'], referenceAnswers: ['I have pain in my foot. I need care.'] },
      ],
      outputTask: {
        id: 'day-045-output',
        topic: 'Body Pain',
        prompts: ['Where is the pain?', 'What care do you need?'],
        template: ['I have pain in my head.', 'I have pain in my hand.', 'I have pain in my foot.', 'I need care.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about body pain and care.',
      },
    },
    {
      id: 'day-046',
      weekId: 'week-07',
      dayNumber: 46,
      title: 'Need Rest',
      goal: 'Ask for rest, water, and help.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['rest', 'water', 'tired', 'ill', 'help', 'care', 'bed'],
      patternIds: ['i-need-rest', 'i-need-care', 'please-help-me'],
      exercises: [
        { type: 'choice', id: 'day-046-choice-001', prompt: 'Which sentence asks for rest?', options: ['I need rest.', 'I need another way.', 'I need a price.'], correctOption: 'I need rest.' },
        { type: 'fill_blank', id: 'day-046-fill-001', prompt: 'I need ___.', acceptedAnswers: ['rest', 'water', 'care', 'help'] },
        { type: 'sentence_order', id: 'day-046-order-001', tokens: ['rest', 'need', 'I'], correctOrder: ['I', 'need', 'rest'], finalSentence: 'I need rest.' },
        { type: 'choice', id: 'day-046-choice-002', prompt: 'Which sentence asks for help?', options: ['Please help me.', 'I am in line.', 'The door is open.'], correctOption: 'Please help me.' },
        { type: 'fill_blank', id: 'day-046-fill-002', prompt: 'Please ___ me.', acceptedAnswers: ['help'] },
        { type: 'translation', id: 'day-046-translation-001', chinesePrompt: '我需要休息和水，请帮帮我。', coreMeaningHint: 'Ask for rest and help.', suggestedPatternIds: ['i-need-rest', 'please-help-me'], referenceAnswers: ['I need rest. I need water. Please help me.'] },
      ],
      outputTask: {
        id: 'day-046-output',
        topic: 'Rest and Help',
        prompts: ['What do you need?', 'Who can help?'],
        template: ['I am tired.', 'I need rest.', 'I need water.', 'Please help me.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about being tired and asking for rest and help.',
      },
    },
    {
      id: 'day-047',
      weekId: 'week-07',
      dayNumber: 47,
      title: 'Warm Care',
      goal: 'Say simple care for an ill body.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['warm', 'care', 'water', 'body', 'ill', 'rest', 'safe'],
      patternIds: ['i-keep-warm', 'i-need-care', 'i-need-rest'],
      exercises: [
        { type: 'choice', id: 'day-047-choice-001', prompt: 'Which sentence is care for the body?', options: ['I keep warm.', 'I pay for bread.', 'I turn right.'], correctOption: 'I keep warm.' },
        { type: 'fill_blank', id: 'day-047-fill-001', prompt: 'I keep ___.', acceptedAnswers: ['warm'] },
        { type: 'sentence_order', id: 'day-047-order-001', tokens: ['keep', 'warm', 'I'], correctOrder: ['I', 'keep', 'warm'], finalSentence: 'I keep warm.' },
        { type: 'fill_blank', id: 'day-047-fill-002', prompt: 'My body needs ___.', acceptedAnswers: ['care', 'rest', 'water'] },
        { type: 'choice', id: 'day-047-choice-002', prompt: 'Which sentence asks for care?', options: ['I need care.', 'I need a list.', 'I need change.'], correctOption: 'I need care.' },
        { type: 'translation', id: 'day-047-translation-001', chinesePrompt: '我不舒服。我需要照顾、休息并保持温暖。', coreMeaningHint: 'Say simple care for an ill body.', suggestedPatternIds: ['i-need-care', 'i-need-rest', 'i-keep-warm'], referenceAnswers: ['I feel ill. I need care. I need rest. I keep warm.'] },
      ],
      outputTask: {
        id: 'day-047-output',
        topic: 'Simple Care',
        prompts: ['What care do you need?', 'How do you keep the body safe?'],
        template: ['I feel ill.', 'I need care.', 'I need rest.', 'I keep warm.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about simple care, rest, and keeping warm.',
      },
    },
    {
      id: 'day-048',
      weekId: 'week-07',
      dayNumber: 48,
      title: 'Tell the Body Problem',
      goal: 'Tell a person what is wrong with your body.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['tell', 'problem', 'body', 'pain', 'ill', 'help', 'care'],
      patternIds: ['i-have-pain-in-my', 'i-feel-ill', 'please-help-me', 'i-need-care'],
      exercises: [
        { type: 'choice', id: 'day-048-choice-001', prompt: 'Which sentence tells a body problem?', options: ['I feel ill and need care.', 'I buy milk at the store.', 'The way is straight.'], correctOption: 'I feel ill and need care.' },
        { type: 'fill_blank', id: 'day-048-fill-001', prompt: 'I have a body ___.', acceptedAnswers: ['problem'] },
        { type: 'replacement', id: 'day-048-replace-001', patternId: 'i-have-pain-in-my', slotValues: { part: 'head' }, referenceAnswer: 'I have pain in my head.' },
        { type: 'sentence_order', id: 'day-048-order-001', tokens: ['help', 'Please', 'me'], correctOrder: ['Please', 'help', 'me'], finalSentence: 'Please help me.' },
        { type: 'fill_blank', id: 'day-048-fill-002', prompt: 'I need ___.', acceptedAnswers: ['care', 'help'] },
        { type: 'translation', id: 'day-048-translation-001', chinesePrompt: '我感觉不舒服，头疼，请帮帮我。', coreMeaningHint: 'Tell a body problem and ask for help.', suggestedPatternIds: ['i-feel-ill', 'i-have-pain-in-my', 'please-help-me'], referenceAnswers: ['I feel ill. I have pain in my head. Please help me.'] },
      ],
      outputTask: {
        id: 'day-048-output',
        topic: 'Tell the Problem',
        prompts: ['What is wrong?', 'What help do you need?'],
        template: ['I have a body problem.', 'I feel ill.', 'I have pain in my head.', 'Please help me.'],
        requiredSentenceCount: 4,
        storyMode: 'sentence',
        storyPrompt: 'Make a short story about telling a person your body problem and asking for help.',
      },
    },
    {
      id: 'day-049',
      weekId: 'week-07',
      dayNumber: 49,
      title: 'Week 7 Care Story',
      goal: 'Tell a body problem story from pain to care.',
      estimatedMinutes: 35,
      review: { wordCount: 10, patternCount: 5 },
      wordIds: ['body', 'head', 'pain', 'ill', 'tired', 'rest', 'care', 'warm', 'help', 'water'],
      patternIds: ['i-have-pain-in-my', 'i-feel-ill', 'i-am-tired', 'i-need-rest', 'i-need-care'],
      exercises: [
        { type: 'choice', id: 'day-049-choice-001', prompt: 'Which sentence starts a body care story?', options: ['I feel ill. I have pain in my head.', 'I am in the store.', 'The road is far.'], correctOption: 'I feel ill. I have pain in my head.' },
        { type: 'fill_blank', id: 'day-049-fill-001', prompt: 'I have pain in my ___.', acceptedAnswers: ['head', 'hand', 'foot'] },
        { type: 'replacement', id: 'day-049-replace-001', patternId: 'i-have-pain-in-my', slotValues: { part: 'head' }, referenceAnswer: 'I have pain in my head.' },
        { type: 'sentence_order', id: 'day-049-order-001', tokens: ['need', 'care', 'I'], correctOrder: ['I', 'need', 'care'], finalSentence: 'I need care.' },
        { type: 'fill_blank', id: 'day-049-fill-002', prompt: 'I need ___ and water.', acceptedAnswers: ['rest', 'care', 'help'] },
        { type: 'translation', id: 'day-049-translation-001', chinesePrompt: '我不舒服，头疼。我需要休息、喝水和照顾。', coreMeaningHint: 'Tell a full body care story.', suggestedPatternIds: ['i-feel-ill', 'i-have-pain-in-my', 'i-need-rest', 'i-need-care'], referenceAnswers: ['I feel ill. I have pain in my head. I need rest. I need water. I need care.'] },
      ],
      outputTask: {
        id: 'day-049-output',
        topic: 'Body Care Story',
        prompts: ['How do you feel?', 'Where is the pain?', 'What care do you need?'],
        template: ['I feel ill.', 'I am tired.', 'I have pain in my head.', 'I need rest.', 'I need water.', 'I need care.'],
        requiredSentenceCount: 6,
        storyMode: 'recap',
        storyPrompt: 'Make a full story about body pain, feeling ill, rest, water, care, and help.',
      },
      weeklyCheckRubric: {
        scale: { min: 0, max: 2 },
        pass: { minimumTotalScore: 7, minimumMeaningScore: 1, minimumSentenceCount: 6 },
        criteria: [
          { id: 'meaning', label: 'Meaning', scores: ['hard to understand', 'partly clear', 'clear'] },
          { id: 'body-problem', label: 'Body problem', scores: ['problem is not clear', 'some body problem words', 'clear body problem and care'] },
          { id: 'target-patterns', label: 'Form use', scores: ['not used', 'used with help', 'used with no help'] },
          { id: 'word-use', label: 'Word use', scores: ['little body words', 'some body words', 'much body words'] },
          { id: 'independence', label: 'My words', scores: ['same as example', 'some change from example', 'all my words'] },
        ],
      },
    },
  ],
};
