import type { Pattern, Week, Word } from '../domain/types';

export const week2Words: Word[] = [
  { id: 'room', text: 'room', category: 'picturable_thing', definition: 'a part of a building in walls', chinese: '房间', example: 'This is my room.', weekIntroduced: 2, tags: ['home'] },
  { id: 'home', text: 'home', category: 'general_thing', definition: 'the place where you have your house', chinese: '家', example: 'My home is small.', weekIntroduced: 2, tags: ['home'] },
  { id: 'table', text: 'table', category: 'picturable_thing', definition: 'a thing with a flat top for work or food', chinese: '桌子', example: 'There is a book on the table.', weekIntroduced: 2, tags: ['home', 'study'] },
  { id: 'chair', text: 'chair', category: 'picturable_thing', definition: 'a seat for one person', chinese: '椅子', example: 'There is a chair near the table.', weekIntroduced: 2, tags: ['home'] },
  { id: 'bed', text: 'bed', category: 'picturable_thing', definition: 'a thing for sleeping on', chinese: '床', example: 'My bed is clean.', weekIntroduced: 2, tags: ['home'] },
  { id: 'door', text: 'door', category: 'picturable_thing', definition: 'a thing you open to go in a room', chinese: '门', example: 'The bag is near the door.', weekIntroduced: 2, tags: ['home'] },
  { id: 'window', text: 'window', category: 'picturable_thing', definition: 'an opening with glass for light and air', chinese: '窗户', example: 'The table is near the window.', weekIntroduced: 2, tags: ['home'] },
  { id: 'book', text: 'book', category: 'picturable_thing', definition: 'pages with words or pictures', chinese: '书', example: 'I have a book.', weekIntroduced: 2, tags: ['study'] },
  { id: 'phone', text: 'phone', category: 'picturable_thing', definition: 'a small machine used for talking and writing', chinese: '手机', example: 'I use my phone every day.', weekIntroduced: 2, tags: ['personal'] },
  { id: 'bag', text: 'bag', category: 'picturable_thing', definition: 'a thing for carrying other things', chinese: '包', example: 'My bag is under the table.', weekIntroduced: 2, tags: ['personal'] },
  { id: 'box', text: 'box', category: 'picturable_thing', definition: 'a thing with sides for keeping things', chinese: '盒子', example: 'There is a key in the box.', weekIntroduced: 2, tags: ['home'] },
  { id: 'cup', text: 'cup', category: 'picturable_thing', definition: 'a small thing used for drinking', chinese: '杯子', example: 'The cup is on the table.', weekIntroduced: 2, tags: ['home'] },
  { id: 'pen', text: 'pen', category: 'picturable_thing', definition: 'a small thing for writing', chinese: '笔', example: 'I have a new pen.', weekIntroduced: 2, tags: ['study'] },
  { id: 'paper', text: 'paper', category: 'general_thing', definition: 'thin material used for writing', chinese: '纸', example: 'There is paper on my table.', weekIntroduced: 2, tags: ['study'] },
  { id: 'thing', text: 'thing', category: 'general_thing', definition: 'a word when you do not need the name', chinese: '东西', example: 'This thing is useful.', weekIntroduced: 2, tags: ['general'] },
  { id: 'in', text: 'in', category: 'structure', definition: 'in a place or thing', chinese: '在里面', example: 'The key is in the bag.', weekIntroduced: 2, tags: ['place'] },
  { id: 'on', text: 'on', category: 'structure', definition: 'touching the top of something', chinese: '在上面', example: 'The book is on the table.', weekIntroduced: 2, tags: ['place'] },
  { id: 'under', text: 'under', category: 'structure', definition: 'below something', chinese: '在下面', example: 'The bag is under the chair.', weekIntroduced: 2, tags: ['place'] },
  { id: 'near', text: 'near', category: 'structure', definition: 'not far from something', chinese: '在附近', example: 'The chair is near the bed.', weekIntroduced: 2, tags: ['place'] },
  { id: 'small', text: 'small', category: 'quality', definition: 'not big', chinese: '小的', example: 'My room is small.', weekIntroduced: 2, tags: ['quality'] },
  { id: 'big', text: 'big', category: 'quality', definition: 'great in size', chinese: '大的', example: 'The table is big.', weekIntroduced: 2, tags: ['quality'] },
  { id: 'clean', text: 'clean', category: 'quality', definition: 'not dirty', chinese: '干净的', example: 'My room is clean.', weekIntroduced: 2, tags: ['quality'] },
  { id: 'new', text: 'new', category: 'quality', definition: 'not old', chinese: '新的', example: 'This is my new phone.', weekIntroduced: 2, tags: ['quality'] },
  { id: 'old', text: 'old', category: 'quality', definition: 'not new', chinese: '旧的', example: 'My bag is old.', weekIntroduced: 2, tags: ['quality'] },
  { id: 'useful', text: 'useful', category: 'quality', definition: 'helping you do something', chinese: '有用的', example: 'My phone is useful.', weekIntroduced: 2, tags: ['quality'] },
  { id: 'important', text: 'important', category: 'quality', definition: 'having great value or need', chinese: '重要的', example: 'My key is important.', weekIntroduced: 2, tags: ['quality'] },
  { id: 'good', text: 'good', category: 'quality', definition: 'right or useful', chinese: '好的', example: 'This is a good room.', weekIntroduced: 2, tags: ['quality'] },
  { id: 'use', text: 'use', category: 'operation', definition: 'to do something with a thing', chinese: '使用', example: 'I use a pen every day.', weekIntroduced: 2, tags: ['action'] },
  { id: 'every', text: 'every', category: 'structure', definition: 'all in a group or time', chinese: '每个', example: 'I use it every day.', weekIntroduced: 2, tags: ['time'] },
  { id: 'day', text: 'day', category: 'general_thing', definition: 'a time from morning to night', chinese: '天', example: 'I use it every day.', weekIntroduced: 2, tags: ['time'] },
  { id: 'money', text: 'money', category: 'general_thing', definition: 'what persons use to buy things', chinese: '钱', example: 'Money is important.', weekIntroduced: 2, tags: ['personal'] },
  { id: 'card', text: 'card', category: 'picturable_thing', definition: 'a small flat thing used for money or words', chinese: '卡', example: 'My card is in my bag.', weekIntroduced: 2, tags: ['personal'] },
  { id: 'key', text: 'key', category: 'picturable_thing', definition: 'a small thing used to open a door', chinese: '钥匙', example: 'My key is important.', weekIntroduced: 2, tags: ['personal'] },
];

export const week2Patterns: Pattern[] = [
  { id: 'this-is-my', title: 'This is my ___.', use: 'Introduce something that belongs to you.', structure: 'This is my {thing}.', examples: ['This is my room.', 'This is my phone.'], slots: ['thing'] },
  { id: 'my-thing-is', title: 'My ___ is ___.', use: 'Describe one of your things.', structure: 'My {thing} is {description}.', examples: ['My room is clean.', 'My bag is old.'], slots: ['thing', 'description'] },
  { id: 'i-have-a', title: 'I have a ___.', use: 'Say one thing you have.', structure: 'I have a {thing}.', examples: ['I have a book.', 'I have a key.'], slots: ['thing'] },
  { id: 'there-is', title: 'There is ___.', use: 'Say that one thing is in a place.', structure: 'There is {thing}.', examples: ['There is a table.', 'There is a book on my table.'], slots: ['thing'] },
  { id: 'there-are', title: 'There are ___.', use: 'Say that more than one thing is in a place.', structure: 'There are {things}.', examples: ['There are books.', 'There are pens on my table.'], slots: ['things'] },
  { id: 'thing-is-on', title: 'The ___ is on ___.', use: 'Say where something is, using on.', structure: 'The {thing} is on {place}.', examples: ['The book is on the table.', 'The cup is on my table.'], slots: ['thing', 'place'] },
  { id: 'thing-is-in', title: 'The ___ is in ___.', use: 'Say where something is, using in.', structure: 'The {thing} is in {place}.', examples: ['The key is in the bag.', 'The pen is in the box.'], slots: ['thing', 'place'] },
  { id: 'thing-is-under', title: 'The ___ is under ___.', use: 'Say where something is, using under.', structure: 'The {thing} is under {place}.', examples: ['The bag is under the table.', 'The box is under the bed.'], slots: ['thing', 'place'] },
  { id: 'thing-is-near', title: 'The ___ is near ___.', use: 'Say where something is, using near.', structure: 'The {thing} is near {place}.', examples: ['The chair is near the table.', 'The bed is near the window.'], slots: ['thing', 'place'] },
  { id: 'it-is-useful', title: 'It is useful.', use: 'Say that something helps you.', structure: 'It is useful.', examples: ['It is useful.', 'My phone is useful.'], slots: [] },
  { id: 'it-is-important', title: 'It is important.', use: 'Say that something has value or need.', structure: 'It is important.', examples: ['It is important.', 'My key is important.'], slots: [] },
  { id: 'i-use-it-every-day', title: 'I use it every day.', use: 'Say that you use something often.', structure: 'I use it every day.', examples: ['I use it every day.', 'I use my phone every day.'], slots: [] },
  { id: 'i-use-it-because', title: 'I use it because ___.', use: 'Give a reason for using something.', structure: 'I use it because {reason}.', examples: ['I use it because it is useful.', 'I use it because I study English.'], slots: ['reason'] },
];

export const week2: Week = {
  id: 'week-02',
  number: 2,
  title: 'Home & Things',
  goal: 'Describe your room, personal things, and where things are.',
  days: [
    {
      id: 'day-008',
      weekId: 'week-02',
      dayNumber: 8,
      title: 'My Room',
      goal: 'Describe your room with simple sentences.',
      estimatedMinutes: 25,
      review: { wordCount: 4, patternCount: 2 },
      wordIds: ['room', 'home', 'table', 'chair', 'bed', 'door', 'window', 'small', 'big', 'clean', 'good'],
      patternIds: ['this-is-my', 'my-thing-is', 'there-is'],
      exercises: [
        { type: 'choice', id: 'day-008-choice-001', prompt: 'Which sentence describes a room?', options: ['My room is clean.', 'Clean my is room.', 'Room table under.'], correctOption: 'My room is clean.' },
        { type: 'fill_blank', id: 'day-008-fill-001', prompt: 'This is my ___.', acceptedAnswers: ['room', 'home'] },
        { type: 'replacement', id: 'day-008-replace-001', patternId: 'this-is-my', slotValues: { thing: 'room' }, referenceAnswer: 'This is my room.' },
        { type: 'sentence_order', id: 'day-008-order-001', tokens: ['room', 'is', 'clean', 'My'], correctOrder: ['My', 'room', 'is', 'clean'], finalSentence: 'My room is clean.' },
        { type: 'translation', id: 'day-008-translation-001', chinesePrompt: '这是我的房间。我的房间很干净。', coreMeaningHint: 'Describe your room.', suggestedPatternIds: ['this-is-my', 'my-thing-is'], referenceAnswers: ['This is my room. My room is clean.'] },
        { type: 'replacement', id: 'day-008-replace-002', patternId: 'there-is', slotValues: { thing: 'a bed in my room' }, referenceAnswer: 'There is a bed in my room.' },
      ],
      outputTask: {
        id: 'day-008-output',
        topic: 'My Room',
        prompts: ['What is in your room?', 'Is your room small, big, or clean?'],
        template: ['This is my room.', 'My room is ___.', 'There is a ___ in my room.', 'There is a ___ near the door.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-009',
      weekId: 'week-02',
      dayNumber: 9,
      title: 'Things in My Room',
      goal: 'Say what things are in your room.',
      estimatedMinutes: 25,
      review: { wordCount: 5, patternCount: 2 },
      wordIds: ['book', 'phone', 'bag', 'box', 'cup', 'pen', 'paper', 'thing', 'room', 'table', 'chair'],
      patternIds: ['i-have-a', 'there-is', 'there-are', 'this-is-my'],
      exercises: [
        { type: 'choice', id: 'day-009-choice-001', prompt: 'Which sentence says one thing is in the room?', options: ['There is a box in my room.', 'There are a box in my room.', 'Box room is.'], correctOption: 'There is a box in my room.' },
        { type: 'fill_blank', id: 'day-009-fill-001', prompt: 'I have a ___.', acceptedAnswers: ['book', 'phone', 'bag', 'pen'] },
        { type: 'replacement', id: 'day-009-replace-001', patternId: 'i-have-a', slotValues: { thing: 'book' }, referenceAnswer: 'I have a book.' },
        { type: 'replacement', id: 'day-009-replace-002', patternId: 'there-are', slotValues: { things: 'books on my table' }, referenceAnswer: 'There are books on my table.' },
        { type: 'sentence_order', id: 'day-009-order-001', tokens: ['a', 'phone', 'have', 'I'], correctOrder: ['I', 'have', 'a', 'phone'], finalSentence: 'I have a phone.' },
        { type: 'translation', id: 'day-009-translation-001', chinesePrompt: '我的房间里有书。我的房间里有笔。', coreMeaningHint: 'Say things in your room.', suggestedPatternIds: ['there-are'], referenceAnswers: ['There are books in my room. There are pens in my room.'] },
      ],
      outputTask: {
        id: 'day-009-output',
        topic: 'Things in My Room',
        prompts: ['What things are in your room?', 'What things do you have?'],
        template: ['There is a ___ in my room.', 'There are ___ on my table.', 'I have a ___.', 'This is my ___.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-010',
      weekId: 'week-02',
      dayNumber: 10,
      title: 'On / In / Under',
      goal: 'Say where things are.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['in', 'on', 'under', 'near', 'book', 'bag', 'box', 'cup', 'key', 'table', 'bed', 'chair'],
      patternIds: ['thing-is-on', 'thing-is-in', 'thing-is-under', 'thing-is-near'],
      exercises: [
        { type: 'choice', id: 'day-010-choice-001', prompt: 'Which word means below something?', options: ['under', 'on', 'near'], correctOption: 'under' },
        { type: 'fill_blank', id: 'day-010-fill-001', prompt: 'The book is ___ the table.', acceptedAnswers: ['on'] },
        { type: 'replacement', id: 'day-010-replace-001', patternId: 'thing-is-on', slotValues: { thing: 'book', place: 'the table' }, referenceAnswer: 'The book is on the table.' },
        { type: 'replacement', id: 'day-010-replace-002', patternId: 'thing-is-in', slotValues: { thing: 'key', place: 'the bag' }, referenceAnswer: 'The key is in the bag.' },
        { type: 'sentence_order', id: 'day-010-order-001', tokens: ['under', 'The', 'is', 'bag', 'the', 'chair'], correctOrder: ['The', 'bag', 'is', 'under', 'the', 'chair'], finalSentence: 'The bag is under the chair.' },
        { type: 'translation', id: 'day-010-translation-001', chinesePrompt: '书在桌子上。包在椅子下面。', coreMeaningHint: 'Say where things are.', suggestedPatternIds: ['thing-is-on', 'thing-is-under'], referenceAnswers: ['The book is on the table. The bag is under the chair.'] },
      ],
      outputTask: {
        id: 'day-010-output',
        topic: 'Where Things Are',
        prompts: ['What is on your table?', 'What is in your bag?', 'What is under your chair?'],
        template: ['The ___ is on ___.', 'The ___ is in ___.', 'The ___ is under ___.', 'The ___ is near ___.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-011',
      weekId: 'week-02',
      dayNumber: 11,
      title: 'My Table',
      goal: 'Describe your table and study things.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['table', 'book', 'pen', 'paper', 'cup', 'phone', 'new', 'old', 'clean', 'small', 'useful'],
      patternIds: ['this-is-my', 'my-thing-is', 'there-is', 'thing-is-on', 'there-are'],
      exercises: [
        { type: 'choice', id: 'day-011-choice-001', prompt: 'Which sentence is about a study place?', options: ['My table is clean.', 'My door is every.', 'Useful is under I.'], correctOption: 'My table is clean.' },
        { type: 'fill_blank', id: 'day-011-fill-001', prompt: 'There is paper ___ my table.', acceptedAnswers: ['on'] },
        { type: 'replacement', id: 'day-011-replace-001', patternId: 'my-thing-is', slotValues: { thing: 'table', description: 'clean' }, referenceAnswer: 'My table is clean.' },
        { type: 'replacement', id: 'day-011-replace-002', patternId: 'thing-is-on', slotValues: { thing: 'pen', place: 'my table' }, referenceAnswer: 'The pen is on my table.' },
        { type: 'sentence_order', id: 'day-011-order-001', tokens: ['on', 'paper', 'There', 'my', 'is', 'table'], correctOrder: ['There', 'is', 'paper', 'on', 'my', 'table'], finalSentence: 'There is paper on my table.' },
        { type: 'translation', id: 'day-011-translation-001', chinesePrompt: '这是我的桌子。桌子上有一本书。', coreMeaningHint: 'Describe your table.', suggestedPatternIds: ['this-is-my', 'thing-is-on'], referenceAnswers: ['This is my table. The book is on my table.'] },
      ],
      outputTask: {
        id: 'day-011-output',
        topic: 'My Table',
        prompts: ['What is your table like?', 'What study things are on it?'],
        template: ['This is my table.', 'My table is ___.', 'The ___ is on my table.', 'There are ___ on my table.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-012',
      weekId: 'week-02',
      dayNumber: 12,
      title: 'My Phone and Bag',
      goal: 'Describe personal things you use every day.',
      estimatedMinutes: 30,
      review: { wordCount: 6, patternCount: 3 },
      wordIds: ['phone', 'bag', 'card', 'key', 'money', 'use', 'every', 'day', 'new', 'old', 'important', 'useful'],
      patternIds: ['this-is-my', 'my-thing-is', 'thing-is-in', 'i-use-it-every-day', 'it-is-useful'],
      exercises: [
        { type: 'choice', id: 'day-012-choice-001', prompt: 'Which sentence says you use something often?', options: ['I use it every day.', 'Every use it I day.', 'It is under every.'], correctOption: 'I use it every day.' },
        { type: 'fill_blank', id: 'day-012-fill-001', prompt: 'My key is ___ my bag.', acceptedAnswers: ['in'] },
        { type: 'replacement', id: 'day-012-replace-001', patternId: 'this-is-my', slotValues: { thing: 'phone' }, referenceAnswer: 'This is my phone.' },
        { type: 'replacement', id: 'day-012-replace-002', patternId: 'thing-is-in', slotValues: { thing: 'card', place: 'my bag' }, referenceAnswer: 'The card is in my bag.' },
        { type: 'sentence_order', id: 'day-012-order-001', tokens: ['use', 'I', 'it', 'day', 'every'], correctOrder: ['I', 'use', 'it', 'every', 'day'], finalSentence: 'I use it every day.' },
        { type: 'translation', id: 'day-012-translation-001', chinesePrompt: '这是我的手机。我每天使用它。', coreMeaningHint: 'Describe a daily thing.', suggestedPatternIds: ['this-is-my', 'i-use-it-every-day'], referenceAnswers: ['This is my phone. I use it every day.'] },
      ],
      outputTask: {
        id: 'day-012-output',
        topic: 'My Phone and Bag',
        prompts: ['What personal things do you use every day?', 'What is in your bag?'],
        template: ['This is my ___.', 'My ___ is ___.', 'The ___ is in my bag.', 'I use it every day.'],
        requiredSentenceCount: 4,
      },
    },
    {
      id: 'day-013',
      weekId: 'week-02',
      dayNumber: 13,
      title: 'Useful and Important Things',
      goal: 'Say why a thing is useful or important.',
      estimatedMinutes: 30,
      review: { wordCount: 7, patternCount: 4 },
      wordIds: ['useful', 'important', 'good', 'use', 'because', 'phone', 'book', 'key', 'money', 'card', 'thing', 'every', 'day'],
      patternIds: ['it-is-useful', 'it-is-important', 'i-use-it-every-day', 'i-use-it-because', 'my-thing-is'],
      exercises: [
        { type: 'choice', id: 'day-013-choice-001', prompt: 'Which sentence gives a reason?', options: ['I use it because it is useful.', 'It because use useful.', 'There are because.'], correctOption: 'I use it because it is useful.' },
        { type: 'fill_blank', id: 'day-013-fill-001', prompt: 'It is ___.', acceptedAnswers: ['useful', 'important', 'good'] },
        { type: 'replacement', id: 'day-013-replace-001', patternId: 'my-thing-is', slotValues: { thing: 'key', description: 'important' }, referenceAnswer: 'My key is important.' },
        { type: 'replacement', id: 'day-013-replace-002', patternId: 'i-use-it-because', slotValues: { reason: 'it is useful' }, referenceAnswer: 'I use it because it is useful.' },
        { type: 'sentence_order', id: 'day-013-order-001', tokens: ['is', 'It', 'important'], correctOrder: ['It', 'is', 'important'], finalSentence: 'It is important.' },
        { type: 'translation', id: 'day-013-translation-001', chinesePrompt: '我的钥匙很重要。我使用它，因为它有用。', coreMeaningHint: 'Say why a thing matters.', suggestedPatternIds: ['my-thing-is', 'i-use-it-because'], referenceAnswers: ['My key is important. I use it because it is useful.'] },
      ],
      outputTask: {
        id: 'day-013-output',
        topic: 'Useful and Important Things',
        prompts: ['What things are useful to you?', 'Why are they important?'],
        template: ['My ___ is important.', 'It is useful.', 'I use it every day.', 'I use it because ___.', 'This thing is good.'],
        requiredSentenceCount: 5,
      },
    },
    {
      id: 'day-014',
      weekId: 'week-02',
      dayNumber: 14,
      title: 'Week 2 Story',
      goal: 'Describe your room and things with your words.',
      estimatedMinutes: 35,
      review: { wordCount: 10, patternCount: 5 },
      wordIds: ['room', 'home', 'table', 'chair', 'bed', 'book', 'phone', 'bag', 'key', 'in', 'on', 'under', 'near'],
      patternIds: ['this-is-my', 'my-thing-is', 'there-is', 'thing-is-on', 'i-use-it-because'],
      exercises: [
        { type: 'choice', id: 'day-014-choice-001', prompt: 'Choose the best room description.', options: ['This is my room. My room is clean.', 'Room my clean is.', 'Because table there.'], correctOption: 'This is my room. My room is clean.' },
        { type: 'fill_blank', id: 'day-014-fill-001', prompt: 'The book is ___ the table.', acceptedAnswers: ['on'] },
        { type: 'replacement', id: 'day-014-replace-001', patternId: 'there-is', slotValues: { thing: 'a phone on my table' }, referenceAnswer: 'There is a phone on my table.' },
        { type: 'sentence_order', id: 'day-014-order-001', tokens: ['near', 'chair', 'The', 'the', 'is', 'table'], correctOrder: ['The', 'chair', 'is', 'near', 'the', 'table'], finalSentence: 'The chair is near the table.' },
        { type: 'translation', id: 'day-014-translation-001', chinesePrompt: '这是我的房间。书在桌子上。我使用它，因为它有用。', coreMeaningHint: 'Describe your room, a place, and a reason.', suggestedPatternIds: ['this-is-my', 'thing-is-on', 'i-use-it-because'], referenceAnswers: ['This is my room. The book is on the table. I use it because it is useful.'] },
        { type: 'replacement', id: 'day-014-replace-002', patternId: 'my-thing-is', slotValues: { thing: 'room', description: 'small and clean' }, referenceAnswer: 'My room is small and clean.' },
      ],
      outputTask: {
        id: 'day-014-output',
        topic: 'Week 2 Room and Things',
        prompts: ['What is your room like?', 'What things are in your room?', 'Where are they?', 'What things are useful or important?'],
        template: ['This is my room.', 'My room is ___.', 'There is a ___ in my room.', 'The ___ is on ___.', 'I use it every day.', 'I use it because ___.'],
        requiredSentenceCount: 6,
      },
      weeklyCheckRubric: {
        scale: { min: 0, max: 2 },
        pass: {
          minimumTotalScore: 7,
          minimumMeaningScore: 1,
          minimumSentenceCount: 6,
        },
        criteria: [
          { id: 'meaning', label: 'Meaning', scores: ['hard to understand', 'partly clear', 'clear'] },
          {
            id: 'sentence-control',
            label: 'Sentence control',
            scores: ['not complete', 'some complete sentences', 'complete sentences'],
          },
          { id: 'target-patterns', label: 'Form use', scores: ['not used', 'used with help', 'used with no help'] },
          { id: 'word-use', label: 'Word use', scores: ['little Week 2 words', 'some Week 2 words', 'much Week 2 words'] },
          { id: 'independence', label: 'My words', scores: ['same as example', 'some change from example', 'all my words'] },
        ],
      },
    },
  ],
};
